//! [test-run] The generated harness: a Salvo program that runs the tests.
//!
//! `salvo test` synthesizes **one Salvo module** and compiles it with the rest
//! of the sources, exactly as `salvo run` would (user decision 2026-09-23,
//! TF-4 option A). Nothing about running tests is backend-specific as a
//! result: the two backends already agree about the language, so they agree
//! about the harness, and neither emitter needed a line of test-shaped code.
//!
//! The harness prints a **protocol**, not the report:
//!
//! ```text
//! ##salvo-test begin heap :: one element comes back out
//! ##salvo-test ok
//! ##salvo-test fail expected 9, got 5
//! ```
//!
//! and the runner renders what the user reads [test-report]. Two reasons,
//! both decided rather than incidental: the report is coloured, and Salvo
//! string literals have no escape for the ESC byte — a language question, not
//! a testing one; and the per-test milliseconds come from timing the protocol
//! lines as they stream, so a test needs no clock capability and the report's
//! shape stays identical on both backends by construction.

use salvo_core::TestCase;

/// The module the harness is synthesized into. Underscore-leading, so no
/// user module path can collide with it ([name-casing] reserves nothing here,
/// but a Salvo file is never named this).
pub const HARNESS_MODULE: &str = "__salvo_test_main";

/// The line the harness prints before running a test, followed by its id.
pub const BEGIN: &str = "##salvo-test begin ";
/// The line the harness prints after a test that completed.
pub const OK: &str = "##salvo-test ok";
/// The line the harness prints after a test that threw, followed by the
/// failure's text.
pub const FAIL: &str = "##salvo-test fail ";

/// [test-run] The harness module's source, for `tests` in report order.
///
/// One `try` per test [test-fail]: a test that completes is `Ok`, a test whose
/// assertion threw is `Thrown Failure`, and `when` reads the two arms like any
/// other union — which is the whole of why the failure channel needed no new
/// language surface.
pub fn harness_source(tests: &[TestCase]) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `salvo test` — the test harness [test-run].\n\
         //\n\
         // Not written to disk anywhere the compiler reads sources from: it is\n\
         // synthesized into the source set, compiled with the program, and\n\
         // prints the protocol the runner renders as the report.\n\
         import test\n",
    );
    // One import per annex module: the synthesized test fns are exported from
    // the annex they were written in [test-run].
    let mut annexes: Vec<String> = tests
        .iter()
        .map(|t| format!("{}.test", t.tested))
        .collect();
    annexes.sort();
    annexes.dedup();
    for annex in &annexes {
        out.push_str(&format!("import {annex}\n"));
    }
    out.push_str("\nfn main() [use] {\n    use StdOutConsole()\n");
    for (i, test) in tests.iter().enumerate() {
        out.push_str(&format!(
            "\n    println(\"{BEGIN}{}\")\n\
             \x20   let outcome{i} = try {{\n\
             \x20       {}()\n\
             \x20   }}\n\
             \x20   when outcome{i} {{\n\
             \x20       is Ok {{\n\
             \x20           println(\"{OK}\")\n\
             \x20       }}\n\
             \x20       is Thrown {{\n\
             \x20           let why{i}: Failure = outcome{i}\n\
             \x20           println(\"{FAIL}${{to_str(why{i})}}\")\n\
             \x20       }}\n\
             \x20   }}\n",
            escape(&test.id()),
            test.fn_name,
        ));
    }
    out.push_str("}\n");
    out
}

/// A test name reaching a Salvo string literal. Names come from source, so
/// they can hold quotes, backslashes and `$`.
fn escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '$' => out.push_str("\\$"),
            '\n' => out.push_str("\\n"),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use salvo_core::ModulePath;

    fn case(name: &str, fn_name: &str) -> TestCase {
        TestCase {
            file: 0,
            tested: ModulePath(vec!["heap".to_string()]),
            name: name.to_string(),
            fn_name: fn_name.to_string(),
        }
    }

    /// [test-run] The harness imports each annex once and delimits every test
    /// with its own `try`.
    #[test]
    fn synthesizes_one_try_per_test() {
        let src = harness_source(&[case("pops in order", "__salvo_test_heap_test_0")]);
        assert!(src.contains("import heap.test\n"), "{src}");
        assert!(
            src.contains("let outcome0 = try {") && src.contains("__salvo_test_heap_test_0()"),
            "{src}"
        );
        assert!(
            src.contains("println(\"##salvo-test begin heap :: pops in order\")"),
            "{src}"
        );
        assert_eq!(src.matches("import heap.test").count(), 1);
    }

    /// A name is source text, so it is escaped into the literal.
    #[test]
    fn escapes_names() {
        let src = harness_source(&[case("a \"quoted\" ${name}", "__salvo_test_heap_test_0")]);
        assert!(
            src.contains("begin heap :: a \\\"quoted\\\" \\${name}"),
            "{src}"
        );
    }
}
