// Generated by the Salvo compiler: the lazy iterator type.
use std::rc::Rc;

/// One **pass** — one walk over a producer's elements.
///
/// `advance` hands over the next element, and `close` releases what the body
/// still holds: pending `defer` blocks, latest first, and any nested pass
/// [iter-generator]. `close` is **idempotent** (the machine guards each
/// deferred block with its own flag), which is what lets a single call after
/// the consumer's loop cover `break`, `return` and exhaustion alike.
///
/// A pass is not a `std::iter::Iterator`, because an iterator has nowhere to
/// put `close`: dropping one runs no Salvo code, and a producer's deferred
/// block is Salvo code that must run on the path the consumer abandoned.
/// `SalvoPassIter` adapts one *to* an iterator where a Rust iterator is what
/// is wanted.
pub trait SalvoPass<T> {
    fn advance(&mut self) -> Option<T>;
    /// The release path. The default is right for a walk over data that is
    /// already there: there is nothing held and nothing to release.
    fn close(&mut self) {}
}

/// A walk over elements that already exist (a collection's, a string's).
/// Nothing is suspended, so `close` is the default no-op.
pub struct SalvoWalk<I>(pub I);

impl<T, I: Iterator<Item = T>> SalvoPass<T> for SalvoWalk<I> {
    fn advance(&mut self) -> Option<T> {
        self.0.next()
    }
}

/// `Iter<T>`: a factory of passes, which is what Kotlin's `Iterable<T>` is.
///
/// A *pass* — one walk over the elements — is a struct the compiler writes
/// for each `yield` function [iter-generator], or a collection's own
/// iterator; this type is what mints one on demand, so two `for` loops over
/// the same value both start from the beginning.
pub struct SalvoIter<T>(Rc<dyn Fn() -> Box<dyn SalvoPass<T>>>);

impl<T: Clone + 'static> SalvoIter<T> {
    pub fn from_factory(factory: Rc<dyn Fn() -> Box<dyn SalvoPass<T>>>) -> Self {
        SalvoIter(factory)
    }

    /// A collection's `iter()`: the elements are already there, so a pass
    /// is a walk over a copy of them.
    pub fn from_vec(items: Vec<T>) -> Self {
        SalvoIter(Rc::new(move || {
            Box::new(SalvoWalk(items.clone().into_iter()))
        }))
    }

    /// Every element, for the places that need them all at once.
    pub fn to_vec(&self) -> Vec<T> {
        self.into_iter().collect()
    }
}

impl<T> SalvoIter<T> {
    /// One pass. The caller drives it and closes it — which is what a `for`
    /// over an `Iter<T>` lowers to.
    pub fn mint(&self) -> Box<dyn SalvoPass<T>> {
        (self.0)()
    }
}

impl<T> Clone for SalvoIter<T> {
    fn clone(&self) -> Self {
        SalvoIter(self.0.clone())
    }
}

impl<T> std::fmt::Debug for SalvoIter<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Iter")
    }
}

/// A pass as a Rust iterator, for the positions that want one (`collect`, a
/// `for` over a subject with nothing to release). Dropping it does *not*
/// close the pass: a consumer that may abandon a producer part-way drives the
/// pass directly, so that the `close` is written where the loop ends.
pub struct SalvoPassIter<T>(Box<dyn SalvoPass<T>>);

impl<T> Iterator for SalvoPassIter<T> {
    type Item = T;
    fn next(&mut self) -> Option<T> {
        self.0.advance()
    }
}

impl<T> IntoIterator for SalvoIter<T> {
    type Item = T;
    type IntoIter = SalvoPassIter<T>;
    fn into_iter(self) -> Self::IntoIter {
        SalvoPassIter((self.0)())
    }
}

impl<T> IntoIterator for &SalvoIter<T> {
    type Item = T;
    type IntoIter = SalvoPassIter<T>;
    fn into_iter(self) -> Self::IntoIter {
        SalvoPassIter((self.0)())
    }
}
