// Generated by the Salvo compiler: enums for union types.

#[derive(Clone, Debug, PartialEq)]
pub enum Union2<T1, T2> {
    U1(T1),
    U2(T2),
}

impl<T1, T2> Union2<T1, T2> {
    pub fn u1(&self) -> &T1 {
        match self {
            Union2::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u1_mut(&mut self) -> &mut T1 {
        match self {
            Union2::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2(&self) -> &T2 {
        match self {
            Union2::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2_mut(&mut self) -> &mut T2 {
        match self {
            Union2::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
}

impl<T1, T2> std::fmt::Display for Union2<T1, T2>
where
    T1: std::fmt::Display,
    T2: std::fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Union2::U1(v) => write!(f, "{}", v),
            Union2::U2(v) => write!(f, "{}", v),
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Union8<T1, T2, T3, T4, T5, T6, T7, T8> {
    U1(T1),
    U2(T2),
    U3(T3),
    U4(T4),
    U5(T5),
    U6(T6),
    U7(T7),
    U8(T8),
}

impl<T1, T2, T3, T4, T5, T6, T7, T8> Union8<T1, T2, T3, T4, T5, T6, T7, T8> {
    pub fn u1(&self) -> &T1 {
        match self {
            Union8::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u1_mut(&mut self) -> &mut T1 {
        match self {
            Union8::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2(&self) -> &T2 {
        match self {
            Union8::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2_mut(&mut self) -> &mut T2 {
        match self {
            Union8::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3(&self) -> &T3 {
        match self {
            Union8::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3_mut(&mut self) -> &mut T3 {
        match self {
            Union8::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4(&self) -> &T4 {
        match self {
            Union8::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4_mut(&mut self) -> &mut T4 {
        match self {
            Union8::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5(&self) -> &T5 {
        match self {
            Union8::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5_mut(&mut self) -> &mut T5 {
        match self {
            Union8::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6(&self) -> &T6 {
        match self {
            Union8::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6_mut(&mut self) -> &mut T6 {
        match self {
            Union8::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7(&self) -> &T7 {
        match self {
            Union8::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7_mut(&mut self) -> &mut T7 {
        match self {
            Union8::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u8(&self) -> &T8 {
        match self {
            Union8::U8(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u8_mut(&mut self) -> &mut T8 {
        match self {
            Union8::U8(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
}

impl<T1, T2, T3, T4, T5, T6, T7, T8> std::fmt::Display for Union8<T1, T2, T3, T4, T5, T6, T7, T8>
where
    T1: std::fmt::Display,
    T2: std::fmt::Display,
    T3: std::fmt::Display,
    T4: std::fmt::Display,
    T5: std::fmt::Display,
    T6: std::fmt::Display,
    T7: std::fmt::Display,
    T8: std::fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Union8::U1(v) => write!(f, "{}", v),
            Union8::U2(v) => write!(f, "{}", v),
            Union8::U3(v) => write!(f, "{}", v),
            Union8::U4(v) => write!(f, "{}", v),
            Union8::U5(v) => write!(f, "{}", v),
            Union8::U6(v) => write!(f, "{}", v),
            Union8::U7(v) => write!(f, "{}", v),
            Union8::U8(v) => write!(f, "{}", v),
        }
    }
}
