// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 00a4643b6b12f596
// [platform-value-type] std's string, for `core.string`'s
// `platform type Str canbe Mut` (ROADMAP 0.7): a `Str` is a `String` and a
// `Mut Str` a `StringBuilder`.
package salvo.platform.core.string

typealias Str = String
typealias MutStr = StringBuilder

// [platform-iterable] The host's loop over a string, or a `Mut Str`: its characters.
fun each(str: CharSequence): Iterable<Char> = str.asIterable()

// [platform-value-type] The copy generated code makes of a `Mut Str`.
fun copy(str: MutStr): MutStr = StringBuilder(str)

fun emptyStr(): MutStr = StringBuilder()

fun size(str: String): Int = str.length

// The UTF-8 byte count [fs-token].
fun byteSize(str: String): Long = str.toByteArray(Charsets.UTF_8).size.toLong()

fun charAt(str: String, index: Int): Char? = str.getOrNull(index)

fun split(str: String, sep: String): MutableList<String> = str.split(sep).toMutableList()

fun indexOf(str: String, needle: String): Int? = str.indexOf(needle).takeIf { it >= 0 }

fun indexOfFrom(str: String, needle: String, from: Int): Int? =
    str.indexOf(needle, from.coerceAtLeast(0)).takeIf { it >= 0 }

fun lastIndexOf(str: String, needle: String): Int? = str.lastIndexOf(needle).takeIf { it >= 0 }

fun replace(str: String, from: String, to: String): String = str.replace(from, to)

fun trimStart(str: String): String = str.trimStart()

fun trimEnd(str: String): String = str.trimEnd()

fun contains(str: String, needle: String): Boolean = str.contains(needle)

fun startsWith(str: String, prefix: String): Boolean = str.startsWith(prefix)

fun endsWith(str: String, suffix: String): Boolean = str.endsWith(suffix)

fun trim(str: String): String = str.trim()

fun trimPrefix(str: String, prefix: String): String = str.removePrefix(prefix)

fun trimSuffix(str: String, suffix: String): String = str.removeSuffix(suffix)

fun substr(str: String, start: Int, end: Int): String? =
    if (start >= 0 && end >= start && end <= str.length) str.substring(start, end) else null

fun toUpper(str: String): String = str.uppercase()

fun toLower(str: String): String = str.lowercase()

fun join(parts: List<String>, sep: String): String = parts.joinToString(sep)

fun parseInt(str: String): Int? = str.toIntOrNull()

fun append(str: MutStr, text: String) {
    str.append(text)
}

// [col-bounds] Out of range writes nothing and answers `false`.
fun set(str: MutStr, index: Int, chr: Char): Boolean =
    if (index >= 0 && index < str.length) {
        str.setCharAt(index, chr)
        true
    } else {
        false
    }

fun clear(str: MutStr) {
    str.clear()
}
