// Generated by the Salvo compiler: effect accessor interfaces [kt-effect-fusion].
package salvo

import salvo.core.actor.*
import salvo.core.array.*
import salvo.core.bytes.*
import salvo.core.console.*
import salvo.core.fs.*
import salvo.core.iterator.*
import salvo.core.list.*
import salvo.core.map.*
import salvo.core.nonempty.*
import salvo.core.result.*
import salvo.core.seq.*
import salvo.core.set.*
import salvo.core.sorted.*
import salvo.core.string.*
import salvo.main.*

interface __Has_Console {
    val __fx_Console: Console
}

interface __Has_Counter {
    val __fx_Counter: Counter
}

interface __Has_Fs {
    val __fx_Fs: Fs
}
