// Generated by the Salvo compiler: effect accessor interfaces [kt-effect-fusion].
package salvo

import salvo.core.actor.*
import salvo.core.checked.*
import salvo.core.console.*
import salvo.core.iterator.*
import salvo.core.list.*
import salvo.core.map.*
import salvo.core.set.*
import salvo.core.sorted.*
import salvo.core.string.*
import salvo.main.*

interface __Has_Console {
    val __fx_Console: Console
}

class __One_Console(private val __e: Console) : __Has_Console {
    override val __fx_Console: Console get() = __e
}

interface __Has_Counter {
    val __fx_Counter: Counter
}

class __One_Counter(private val __e: Counter) : __Has_Counter {
    override val __fx_Counter: Counter get() = __e
}
