// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 00a4643b6b12f596

#[derive(Clone, Debug, PartialEq)]
pub struct Mailbox {
    pub capacity: i32,
}

impl crate::wire::__Wire for Mailbox {
    fn __enc(&self, out: &mut Vec<u8>) {
        crate::wire::__Wire::__enc(&self.capacity, out);
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        Some(Self {
            capacity: crate::wire::__Wire::__dec(r)?,
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Fault {
    pub reason: String,
}

impl crate::wire::__Wire for Fault {
    fn __enc(&self, out: &mut Vec<u8>) {
        crate::wire::__Wire::__enc(&self.reason, out);
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        Some(Self {
            reason: crate::wire::__Wire::__dec(r)?,
        })
    }
}

pub trait __Stateless_Faults: Send + Sync {
    fn faulted(&self, fault: Fault);
}

pub trait __Stateful_Faults: Send {
    fn faulted(&mut self, fault: Fault);
}

pub struct __Stub_Faults {
    addr: usize,
}

impl __Stub_Faults {
    pub fn new(addr: usize) -> Self {
        Self { addr }
    }
}

impl __Stateless_Faults for __Stub_Faults {
    fn faulted(&self, fault: Fault) {
        crate::scheduler::salvo_send_wire(self.addr, __Msg_Faults::Faulted(fault), crate::core_actor::__PROTO_Faults);
    }
}

pub struct Faults {
    inner: __Inner_Faults,
}

pub enum __Inner_Faults {
    Shared(std::sync::Arc<dyn __Stateless_Faults>),
    Locked(std::sync::Arc<std::sync::Mutex<dyn __Stateful_Faults>>),
}

impl Clone for Faults {
    fn clone(&self) -> Self {
        Self { inner: match &self.inner {
            __Inner_Faults::Shared(h) => __Inner_Faults::Shared(h.clone()),
            __Inner_Faults::Locked(h) => __Inner_Faults::Locked(h.clone()),
        } }
    }
}

impl Faults {
    pub fn shared<__H: __Stateless_Faults + 'static>(inner: __H) -> Self {
        Self { inner: __Inner_Faults::Shared(std::sync::Arc::new(inner)) }
    }
    pub fn share_shared(inner: std::sync::Arc<dyn __Stateless_Faults>) -> Self {
        Self { inner: __Inner_Faults::Shared(inner) }
    }
    pub fn locked<__H: __Stateful_Faults + 'static>(inner: __H) -> Self {
        Self { inner: __Inner_Faults::Locked(std::sync::Arc::new(std::sync::Mutex::new(inner))) }
    }
    pub fn share_locked(inner: std::sync::Arc<std::sync::Mutex<dyn __Stateful_Faults>>) -> Self {
        Self { inner: __Inner_Faults::Locked(inner) }
    }
    pub fn faulted(&self, fault: Fault) {
        match &self.inner {
            __Inner_Faults::Shared(h) => h.faulted(fault),
            __Inner_Faults::Locked(h) => h.lock().unwrap().faulted(fault),
        }
    }
}

pub enum __Msg_Faults {
    Faulted(Fault),
}

impl crate::wire::__Wire for __Msg_Faults {
    fn __enc(&self, out: &mut Vec<u8>) {
        match self {
            __Msg_Faults::Faulted(__p0) => {
                out.push(0);
                crate::wire::__Wire::__enc(__p0, out);
            }
        }
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        match r.u8()? {
            0 => Some(__Msg_Faults::Faulted(crate::wire::__Wire::__dec(r)?)),
            _ => None,
        }
    }
}

/// [protocol-hash] The canonical hash of `Faults`.
pub const __PROTO_Faults: &str = "b2ab28f759af3855";

#[derive(Clone, Debug, PartialEq)]
pub struct Exit {
    pub reason: String,
}

impl crate::wire::__Wire for Exit {
    fn __enc(&self, out: &mut Vec<u8>) {
        crate::wire::__Wire::__enc(&self.reason, out);
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        Some(Self {
            reason: crate::wire::__Wire::__dec(r)?,
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Idle {
    pub parked_gates: i32,
    pub parked_tokens: i32,
}

impl crate::wire::__Wire for Idle {
    fn __enc(&self, out: &mut Vec<u8>) {
        crate::wire::__Wire::__enc(&self.parked_gates, out);
        crate::wire::__Wire::__enc(&self.parked_tokens, out);
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        Some(Self {
            parked_gates: crate::wire::__Wire::__dec(r)?,
            parked_tokens: crate::wire::__Wire::__dec(r)?,
        })
    }
}
