// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 45c241eb24943931
package salvo.core.bytes

fun emptyBytesPlatform(): salvo.platform.core.bytes.MutBytes {
    return salvo.platform.core.bytes.emptyBytes()
}

fun toBytesPlatform(str: String): salvo.platform.core.bytes.Bytes {
    return salvo.platform.core.bytes.toBytes(str)
}

fun strOfBytesPlatform(data: salvo.platform.core.bytes.Bytes): String? {
    return salvo.platform.core.bytes.strOfBytes(data)
}

fun eqPlatform(a: salvo.platform.core.bytes.Bytes, b: salvo.platform.core.bytes.Bytes): Boolean {
    return salvo.platform.core.bytes.eq(a, b)
}

fun sizePlatform(data: salvo.platform.core.bytes.Bytes): Int {
    return salvo.platform.core.bytes.size(data)
}

fun getPlatform(data: salvo.platform.core.bytes.Bytes, index: Int): UByte? {
    return salvo.platform.core.bytes.get(data, index)
}

fun slicePlatform(data: salvo.platform.core.bytes.Bytes, start: Int, end: Int): salvo.platform.core.bytes.Bytes? {
    return salvo.platform.core.bytes.slice(data, start, end)
}

fun indexOfPlatform(data: salvo.platform.core.bytes.Bytes, byte: UByte): Int? {
    return salvo.platform.core.bytes.indexOf(data, byte)
}

fun addPlatform(data: salvo.platform.core.bytes.MutBytes, byte: UByte) {
    return salvo.platform.core.bytes.add(data, byte)
}

fun appendPlatform(data: salvo.platform.core.bytes.MutBytes, more: salvo.platform.core.bytes.Bytes) {
    return salvo.platform.core.bytes.append(data, more)
}

fun setPlatform(data: salvo.platform.core.bytes.MutBytes, index: Int, byte: UByte): Boolean {
    return salvo.platform.core.bytes.set(data, index, byte)
}

fun clearPlatform(data: salvo.platform.core.bytes.MutBytes) {
    return salvo.platform.core.bytes.clear(data)
}

fun toStrPlatform(data: salvo.platform.core.bytes.Bytes): String {
    return salvo.platform.core.bytes.toStr(data)
}

fun toHexPlatform(data: salvo.platform.core.bytes.Bytes): String {
    return salvo.platform.core.bytes.toHex(data)
}
