// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 5ecf120cea852ac5

/// [platform-type] The host's `Deque`.
pub use crate::platform_core_deque::Deque;
const _: fn() = || { fn __contract<T: Send + 'static + Clone + std::fmt::Debug + PartialEq + Eq + std::hash::Hash>() {} __contract::<Deque<i32>>(); };
const _: fn() = || { fn __each(x: &Deque<i32>) -> impl Iterator<Item = i32> + '_ { crate::platform_core_deque::each(x).map(|e| e.clone()) } let _ = __each; };
const _: fn() = || { fn __each_ref(x: &Deque<i32>) -> impl Iterator<Item = &i32> + '_ { crate::platform_core_deque::each(x) } fn __each_mut(x: &mut Deque<i32>) -> impl Iterator<Item = &mut i32> + '_ { crate::platform_core_deque::each_mut(x) } fn __into_each(x: Deque<i32>) -> impl Iterator<Item = i32> { crate::platform_core_deque::into_each(x) } let _ = (__each_ref, __each_mut, __into_each); };

pub fn empty_deque_platform<T>() -> std::collections::VecDeque<T> {
    crate::platform_core_deque::empty_deque()
}

pub fn deque_from_platform<T: Clone>(first: T, rest: Vec<T>) -> std::collections::VecDeque<T> {
    crate::platform_core_deque::deque_from(first, rest)
}

pub fn into_mut_platform<T>(d: std::collections::VecDeque<T>) -> std::collections::VecDeque<T> {
    crate::platform_core_deque::into_mut(d)
}

pub fn end_empty_platform<T>(mut d: std::collections::VecDeque<T>) {
    crate::platform_core_deque::end_empty(d)
}

pub fn add_last_platform<T>(d: &mut std::collections::VecDeque<T>, elem: T) {
    crate::platform_core_deque::add_last(d, elem)
}

pub fn add_first_platform<T>(d: &mut std::collections::VecDeque<T>, elem: T) {
    crate::platform_core_deque::add_first(d, elem)
}

pub fn remove_first_platform<T>(d: &mut std::collections::VecDeque<T>) -> Option<T> {
    crate::platform_core_deque::remove_first(d)
}

pub fn remove_last_platform<T>(d: &mut std::collections::VecDeque<T>) -> Option<T> {
    crate::platform_core_deque::remove_last(d)
}

pub fn remove_at_platform<T>(d: &mut std::collections::VecDeque<T>, index: i32) -> Option<T> {
    crate::platform_core_deque::remove_at(d, index)
}

pub fn get_platform<T>(d: &std::collections::VecDeque<T>, index: i32) -> Option<&T> {
    crate::platform_core_deque::get(d, index)
}

pub fn first_platform<T>(d: &std::collections::VecDeque<T>) -> Option<&T> {
    crate::platform_core_deque::first(d)
}

pub fn last_platform<T>(d: &std::collections::VecDeque<T>) -> Option<&T> {
    crate::platform_core_deque::last(d)
}

pub fn size_platform<T>(d: &std::collections::VecDeque<T>) -> i32 {
    crate::platform_core_deque::size(d)
}
