// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 5ecf120cea852ac5
package salvo.core.list

import salvo.core.bytes.*
import salvo.core.deque.*
import salvo.core.string.*

fun<T> getPlatform(list: List<T>, index: Int): T? {
    return salvo.platform.core.list.get(list, index)
}

fun<T> addPlatform(list: salvo.platform.core.list.MutList<T>, elem: T) {
    return salvo.platform.core.list.add(list, elem)
}

fun<T> removeFirstPlatform(list: salvo.platform.core.list.MutList<T>): T? {
    return salvo.platform.core.list.removeFirst(list)
}

fun<T> removeAtPlatform(list: salvo.platform.core.list.MutList<T>, index: Int): T? {
    return salvo.platform.core.list.removeAt(list, index)
}

fun<T> insertAtPlatform(list: salvo.platform.core.list.MutList<T>, index: Int, elem: T): T? {
    return salvo.platform.core.list.insertAt(list, index, elem)
}

fun<T> removeRangePlatform(list: salvo.platform.core.list.MutList<T>, from: Int, to: Int): salvo.platform.core.list.MutList<T> {
    return salvo.platform.core.list.removeRange(list, from, to)
}

fun<T> swapAtPlatform(list: salvo.platform.core.list.MutList<T>, i: Int, j: Int): Boolean {
    return salvo.platform.core.list.swapAt(list, i, j)
}

fun<T> intoMutPlatform(list: List<T>): salvo.platform.core.list.MutList<T> {
    return salvo.platform.core.list.intoMut(list)
}

fun<T> endEmptyPlatform(list: salvo.platform.core.list.MutList<T>) {
    return salvo.platform.core.list.endEmpty(list)
}

fun<T> removeLastPlatform(list: salvo.platform.core.list.MutList<T>): T? {
    return salvo.platform.core.list.removeLast(list)
}

fun<T> firstPlatform(list: List<T>): T? {
    return salvo.platform.core.list.first(list)
}

fun<T> sizePlatform(list: List<T>): Int {
    return salvo.platform.core.list.size(list)
}

fun<T> sortByPlatform(list: List<T>, cmp: (T, T) -> Int): salvo.platform.core.list.MutList<T> {
    return salvo.platform.core.list.sortBy(list, cmp)
}

fun<T> insertSortedByPlatform(list: salvo.platform.core.list.MutList<T>, elem: T, cmp: (T, T) -> Int) {
    return salvo.platform.core.list.insertSortedBy(list, elem, cmp)
}

fun<T> searchSortedByPlatform(list: List<T>, elem: T, cmp: (T, T) -> Int): Int? {
    return salvo.platform.core.list.searchSortedBy(list, elem, cmp)
}
