// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 5ecf120cea852ac5
package salvo.core.seq


fun<T> filterPlatform(list: List<T>, keep: (T) -> Boolean): salvo.platform.core.list.MutList<T> {
    return salvo.platform.core.seq.filter(list, keep)
}
