// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 d6d03ef668743535
package salvo.core.set

import salvo.*
import salvo.core.iterator.Finished
import salvo.core.iterator.emitted
import salvo.core.iterator.finished
import salvo.core.list.at
import salvo.core.string.appendPlatform
import salvo.core.string.mutStr

fun<T> addPlatform(set: salvo.platform.core.set.MutSet<T>, elem: T): Boolean {
    return salvo.platform.core.set.add(set, elem)
}

fun<T> removePlatform(set: salvo.platform.core.set.MutSet<T>, elem: T): Boolean {
    return salvo.platform.core.set.remove(set, elem)
}

fun<T> containsPlatform(set: Set<T>, elem: T): Boolean {
    return salvo.platform.core.set.contains(set, elem)
}

fun<T> sizePlatform(set: Set<T>): Int {
    return salvo.platform.core.set.size(set)
}

fun<T> toStr(set: Set<T>, toStr: (T) -> String): String {
    val out = mutStr(arrayOf("{"))
    var i = 0
    for (x in salvo.platform.core.set.each(set)) {
        if (i > 0) {
            appendPlatform(out, ", ")
        }
        appendPlatform(out, toStr(x))
        i = i + 1
    }
    appendPlatform(out, "}")
    return out.toString()
}

fun<T> toListPlatform(set: Set<T>): List<T> {
    return salvo.platform.core.set.toList(set)
}

fun<T> iter(set: Set<T>): SetYield<T> {
    return SetYield(items = toListPlatform(set), at = 0)
}

data class SetYield<T>(
    var items: List<T>,
    var at: Int,
)

class __Codec_SetYield<T>(private val __c_T: salvo.WireCodec<T>) : salvo.WireCodec<SetYield<T>> {
    override fun enc(v: SetYield<T>, out: salvo.WireOut) {
        salvo.ListCodec(__c_T).enc(v.items, out)
        salvo.IntCodec.enc(v.at, out)
    }
    override fun dec(inp: salvo.WireIn): SetYield<T> = SetYield(salvo.ListCodec(__c_T).dec(inp), salvo.IntCodec.dec(inp))
}

fun<T> next(p: SetYield<T>): Union2<T, Finished> {
    val elem = p.items.getOrNull(p.at)
    if (elem == null) {
        return Union2.U2<T, Finished>(finished())
    }
    p.at = p.at + 1
    return Union2.U1<T, Finished>(emitted(elem))
}

fun<T> NonEmpty_qualifies(set: Set<T>): Boolean {
    return sizePlatform(set) > 0
}
