//! Rust backend for the Salvo compiler.

mod emit;
mod intrinsics;

pub use emit::{
    emit_abi, emit_program, emit_program_reporting, emit_program_with_entry,
    platform_skeletons, EmittedFile,
};

use std::path::{Path, PathBuf};

use salvo_backend::{run_tool, Backend, BackendError, Emitted};
use salvo_core::{HostDeps, ModulePath, Program};

/// Where the linked binary goes inside the target directory [rs-run].
/// Dot-prefixed so a target nested in the source tree stays invisible to
/// source discovery [mod-ignore].
const BIN_DIR: &str = ".salvo_bin";
/// [rs-cargo] The Cargo manifest written beside the crate root when crates are
/// declared [platform-host-deps].
const CARGO_MANIFEST: &str = "Cargo.toml";
/// The first line of a manifest this backend wrote — how a stale one is told
/// from a hand-written one before being removed.
const CARGO_HEADER: &str =
    "# Written by `salvo`: the host libraries the platform companions declared [platform-host-deps].";

/// [platform-abi] The first lines of every generated file of a platform
/// root: never edited, never read by the build.
const ABI_HEADER: &str = "// GENERATED by salvo for the host project of this platform root [platform-abi]:\n\
    // the declarations the platform code uses, as the build emits them. Rewritten\n\
    // by every build — do not edit; the build never reads this file.";

pub struct RustBackend;

impl Backend for RustBackend {
    fn name(&self) -> &'static str {
        "rust"
    }

    fn file_extension(&self) -> &'static str {
        "rs"
    }

    /// [rs-crate] The crate root is the `main`-declaring module, so a
    /// program with several candidates needs `entry` to say which — building
    /// the wrong one leaves the `mod` declarations behind and rustc reports
    /// unresolved imports.
    fn emit(
        &self,
        program: &Program,
        target_dir: &Path,
        entry: Option<&ModulePath>,
    ) -> Result<Emitted, BackendError> {
        let (files, warnings) = emit::emit_program_reporting(program, entry)
            .map_err(BackendError::Codegen)?;
        let mut written = Vec::with_capacity(files.len());
        for file in files {
            let path = target_dir.join(&file.rel_path);
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&path, &file.content)?;
            written.push(file.rel_path);
        }
        Ok(Emitted {
            files: written,
            warnings,
        })
    }

    /// [platform-tree] The crate root is still the file to build: when the
    /// host owns `main`, the root's own `fn main` delegates to it, so the
    /// `rustc` invocation is unchanged.
    fn entry_hint(
        &self,
        target_dir: &Path,
        main_module: &ModulePath,
        _emitted: &[PathBuf],
    ) -> String {
        let root = target_dir.join(crate_root(main_module));
        // [rs-cargo] A written `Cargo.toml` means the build is Cargo's.
        if target_dir.join(CARGO_MANIFEST).is_file() {
            return format!(
                "{} (build with: cargo build --manifest-path {})",
                root.display(),
                target_dir.join(CARGO_MANIFEST).display()
            );
        }
        format!(
            "{} (build with: rustc --edition 2021 {})",
            root.display(),
            root.display()
        )
    }

    fn platform_skeletons(
        &self,
        program: &Program,
        entry: Option<&ModulePath>,
    ) -> Result<Vec<(PathBuf, String)>, BackendError> {
        let files =
            emit::platform_skeletons(program, entry).map_err(BackendError::Codegen)?;
        Ok(files
            .into_iter()
            .map(|f| (f.rel_path, f.content))
            .collect())
    }

    /// [platform-abi] [rs-abi] The host crate of a platform root: `emit_abi`'s
    /// declarations and crate root, and a `Cargo.toml` naming `lib.sv.rs` as
    /// the library with the declared crates as dependencies — so
    /// rust-analyzer opens the root as an ordinary crate.
    fn platform_abi(
        &self,
        program: &Program,
        entry: Option<&ModulePath>,
        host: &HostDeps,
    ) -> Result<Vec<(PathBuf, String)>, BackendError> {
        let files = emit::emit_abi(program, entry).map_err(BackendError::Codegen)?;
        if files.iter().all(|f| !f.rel_path.to_string_lossy().ends_with(".sv.rs") || f.rel_path == Path::new("lib.sv.rs")) {
            return Ok(Vec::new());
        }
        // [platform-stamp] What a consumer compares before building this root.
        let symbols = salvo_core::Symbols::collect(program);
        let stamp = salvo_core::abi::abi_stamp(program, &symbols, None).unwrap_or_default();
        let mut out: Vec<(PathBuf, String)> = files
            .into_iter()
            .map(|f| (f.rel_path, format!("{ABI_HEADER}\n// {stamp}\n{}", f.content)))
            .collect();
        out.push((
            PathBuf::from(CARGO_MANIFEST),
            format!(
                "# GENERATED by salvo [platform-abi]: the host crate of this platform root, so\n\
                 # rust-analyzer can open it. Rewritten by every build — do not edit.\n# {stamp}\n\
                 [package]\nname = \"salvo-platform\"\nversion = \"0.0.0\"\nedition = \"2021\"\n\n\
                 [lib]\npath = \"lib.sv.rs\"\n\n\
                 [workspace]\n\n\
                 {}",
                host.cargo_dependencies_section()
            ),
        ));
        Ok(out)
    }

    /// [rs-cargo] With crates declared [platform-host-deps], the program is a
    /// Cargo package: a `Cargo.toml` beside the crate root naming the binary,
    /// the dependencies verbatim, and an empty `[workspace]` so a target
    /// directory nested inside some other workspace (this repository's
    /// examples) is its own root rather than an unlisted member.
    fn write_host_manifest(
        &self,
        target_dir: &Path,
        main_module: &ModulePath,
        host: &HostDeps,
    ) -> Result<Vec<PathBuf>, BackendError> {
        let manifest_path = target_dir.join(CARGO_MANIFEST);
        if !host.has_rust() {
            // A manifest a previous build wrote is stale now; only ours is
            // removed, recognised by its header.
            if std::fs::read_to_string(&manifest_path)
                .is_ok_and(|text| text.starts_with(CARGO_HEADER))
            {
                std::fs::remove_file(&manifest_path)?;
            }
            return Ok(Vec::new());
        }
        let root = crate_root(main_module);
        let name = bin_name(main_module);
        let manifest = format!(
            "{CARGO_HEADER}\n\
             [package]\nname = \"{name}\"\nversion = \"0.0.0\"\nedition = \"2021\"\n\n\
             [[bin]]\nname = \"{name}\"\npath = \"{}\"\n\n\
             [workspace]\n\n\
             {}",
            root.display(),
            host.cargo_dependencies_section()
        );
        std::fs::create_dir_all(target_dir)?;
        std::fs::write(&manifest_path, manifest)?;
        Ok(vec![PathBuf::from(CARGO_MANIFEST)])
    }

    /// [rs-run] The module declaring `main` is the crate root, so one
    /// `rustc` invocation on that file builds the whole program (the other
    /// modules are reached through its `mod` declarations). The binary goes
    /// inside the target directory, then runs. [rs-cargo] With crates
    /// declared, `cargo build` on the emitted `Cargo.toml` replaces the
    /// `rustc` call, building into the same hidden directory.
    fn program_command(
        &self,
        target_dir: &Path,
        main_module: &ModulePath,
        _emitted: &[PathBuf],
        host: &HostDeps,
    ) -> Result<std::process::Command, BackendError> {
        use std::ffi::OsStr;

        let root = target_dir.join(crate_root(main_module));
        if !root.is_file() {
            return Err(BackendError::Other(format!(
                "nothing to run: expected the crate root `{}` to have been emitted",
                root.display()
            )));
        }
        let bin_dir = target_dir.join(BIN_DIR);
        std::fs::create_dir_all(&bin_dir)?;
        let name = bin_name(main_module);
        let bin = bin_dir.join(&name);

        if host.has_rust() {
            let manifest = target_dir.join(CARGO_MANIFEST);
            if !manifest.is_file() {
                return Err(BackendError::Other(format!(
                    "crates are declared but `{}` was not written [rs-cargo]",
                    manifest.display()
                )));
            }
            let code = salvo_backend::run_host_tool(
                &host.cargo_program(),
                "[rust] cargo",
                &[
                    OsStr::new("build"),
                    OsStr::new("--quiet"),
                    OsStr::new("--manifest-path"),
                    manifest.as_os_str(),
                    OsStr::new("--target-dir"),
                    bin_dir.as_os_str(),
                ],
            )?;
            if code != 0 {
                return Err(BackendError::Other(format!(
                    "cargo build failed with exit code {code}"
                )));
            }
            return Ok(std::process::Command::new(bin_dir.join("debug").join(&name)));
        }

        let code = run_tool(
            "rustc",
            &[
                OsStr::new("--edition"),
                OsStr::new("2021"),
                root.as_os_str(),
                OsStr::new("-o"),
                bin.as_os_str(),
            ],
        )?;
        if code != 0 {
            return Err(BackendError::Other(format!(
                "rustc failed with exit code {code}"
            )));
        }
        Ok(std::process::Command::new(bin))
    }
}

/// The binary's name: the entry module's last segment.
fn bin_name(main_module: &ModulePath) -> String {
    main_module.0.last().cloned().unwrap_or_else(|| "program".to_string())
}

/// The emitted crate-root path for the module declaring `main`
/// (`main` -> `main.rs`, `app.entry` -> `app/entry.rs`), relative to the
/// target directory. See BACKEND_SPEC.rust.md.
fn crate_root(main_module: &ModulePath) -> PathBuf {
    let mut path = PathBuf::new();
    for part in &main_module.0 {
        path.push(part);
    }
    path.set_extension("rs");
    path
}
