//! [rs-runtime-source] The backend's *runtime modules* — `runtime/*.rs`,
//! included verbatim by the emitter and written into a program's output when
//! it touches the feature — compiled directly by `rustc`.
//!
//! Why this exists: those modules used to be Rust string literals inside
//! `emit.rs`, which meant they were only ever compiled as part of a whole
//! generated program. A syntax error in one showed up as a failure in some
//! unrelated end-to-end test, and reviewing a change to one meant reviewing
//! a diff of an escaped string. As real source files they are reviewable as
//! code and verified here on their own — which is the standing form of the
//! "hand-verify the generated shape before teaching it to the emitter"
//! rule from COMPLETED.md's gotchas.
//!
//! Each module must compile **warning-free** as a library crate: it is
//! spliced into user output, where a warning is noise the user cannot fix.
//! Skipped when `rustc` is not on PATH, like every other toolchain test.

use std::process::Command;

/// Every static runtime module, with the emitter accessor that ships it.
/// A new one belongs here the moment it exists — the list is what makes
/// this test complete rather than a sample.
const RUNTIME_MODULES: &[&str] =
    &["strings.rs", "seq.rs", "collections.rs", "scheduler.rs", "hosttime.rs"];

/// The bytes the emitter will splice, read from the same path `include_str!`
/// reads at compile time.
fn runtime_source(file: &str) -> String {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("runtime")
        .join(file);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read the runtime module {}: {e}", path.display()))
}

/// Compiles one runtime module as a library crate and asserts that `rustc`
/// accepted it *and* said nothing.
fn compile_runtime_module(file: &str) {
    let rustc = salvo_testkit::rustc();
    if !rustc.available {
        return;
    }
    let source = runtime_source(file);
    // [time-timer] `scheduler.rs` reads the monotonic clock for its deadline
    // thread, so it compiles against `crate::hosttime` — mounted here exactly
    // as the emitter mounts it (the two always travel together, since a
    // `Fired` has to sit on the timeline `tick()` reports). Every other module
    // is standalone, and `hosttime.rs` is checked on its own in this same list.
    let source = if file == "scheduler.rs" {
        let hosttime = runtime_source("hosttime.rs");
        format!("pub mod hosttime {{\n{hosttime}\n}}\n{source}")
    } else {
        source
    };
    let parts: Vec<&[u8]> = vec![
        b"rust-runtime-module",
        rustc.version.as_bytes(),
        file.as_bytes(),
        source.as_bytes(),
    ];
    let Some(stamp) = salvo_testkit::cached(
        env!("CARGO_TARGET_TMPDIR"),
        &format!("rust-runtime {file}"),
        &parts,
    ) else {
        return;
    };
    let dir = salvo_testkit::scratch(env!("CARGO_TARGET_TMPDIR"), &format!("rt-{file}"));
    let src = dir.join(file);
    std::fs::write(&src, &source).expect("failed to write the runtime module");
    let out = Command::new("rustc")
        .arg("--edition")
        .arg("2021")
        .arg("--crate-type")
        .arg("lib")
        .arg(&src)
        .arg("-o")
        .arg(dir.join("libruntime.rlib"))
        .output()
        .expect("failed to run rustc");
    assert!(
        out.status.success(),
        "rustc rejected runtime/{file}:\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let noise = String::from_utf8_lossy(&out.stderr);
    assert!(
        noise.trim().is_empty(),
        "runtime/{file} compiles with warnings, which would land in user output:\n{noise}"
    );
    stamp.verified();
}

#[test]
fn every_runtime_module_compiles_warning_free() {
    for file in RUNTIME_MODULES {
        compile_runtime_module(file);
    }
}

/// The emitted content and the file on disk must be the same bytes: the
/// emitter uses `include_str!`, so a stale copy cannot drift silently, but a
/// *renamed* or accidentally rewritten module would slip past that. Reading
/// both here keeps the list above honest.
#[test]
fn runtime_modules_are_not_empty_and_are_generated_headers() {
    for file in RUNTIME_MODULES {
        let source = runtime_source(file);
        assert!(
            source.starts_with("// Generated by the Salvo compiler:"),
            "runtime/{file} must open with the generated-by header, since it is \
             spliced into user output"
        );
        assert!(
            source.ends_with('\n'),
            "runtime/{file} must end with a newline"
        );
    }
}

// ===== The scheduler's *behaviour* — asynchronous effect handlers' runtime
// ([actor-kind] … [actor-watch]) =====
//
// The module above is only compiled; a scheduler also has to *behave*, and
// the semantics are decided ones: run-to-completion activations, per-actor
// bounded queues that block the sender, replies with reserved capacity, the
// gate (while gated, only the awaited reply is delivered), death by faulted
// activation with `watch` notification, sends to the dead as silent no-ops,
// and the idle-with-parked-gates report instead of a hang. Each case below
// compiles the real runtime module together with a small driver `main` and
// asserts the program's output.
//
// **The same scenarios, with the same expected output, exist in the Kotlin
// backend's `runtime_tests.rs`** — that equality is the parity assertion:
// the two schedulers must be one design, not two implementations.

/// Runs a child process with a wall-clock limit, so a scheduler bug shows
/// up as a failing test rather than a hung suite (AGENTS.md: watch the
/// clock).
fn wait_with_timeout(mut child: std::process::Child, secs: u64) -> std::process::Output {
    let start = std::time::Instant::now();
    loop {
        if let Some(_status) = child.try_wait().expect("failed to poll the child") {
            return child
                .wait_with_output()
                .expect("failed to collect the child's output");
        }
        if start.elapsed() > std::time::Duration::from_secs(secs) {
            let _ = child.kill();
            let out = child
                .wait_with_output()
                .expect("failed to collect the child's output");
            panic!(
                "the scheduler program did not finish within {secs}s (deadlock or lost wakeup)\
                 \nstdout so far:\n{}\nstderr so far:\n{}",
                String::from_utf8_lossy(&out.stdout),
                String::from_utf8_lossy(&out.stderr)
            );
        }
        std::thread::sleep(std::time::Duration::from_millis(20));
    }
}

/// Compiles `scheduler.rs` plus a driver `main` and runs it, asserting the
/// exact stdout, whether the run succeeded, and a stderr marker.
fn run_scheduler_program(
    tag: &str,
    driver: &str,
    expected_stdout: &str,
    expect_success: bool,
    stderr_contains: &str,
) {
    let rustc = salvo_testkit::rustc();
    if !rustc.available {
        return;
    }
    let module = runtime_source("scheduler.rs");
    // [time-timer] The scheduler's deadline thread reads the monotonic clock,
    // so `hosttime.rs` is mounted beside it exactly as the emitter mounts it —
    // as `crate::hosttime`, which is the path the scheduler names.
    let hosttime = runtime_source("hosttime.rs");
    // `dead_code` is allowed because a driver exercises one slice of the
    // runtime's surface; the module itself is warning-checked above.
    let source = format!(
        "#![allow(dead_code)]\npub mod hosttime {{\n{hosttime}\n}}\n{module}\n{driver}"
    );
    let parts: Vec<&[u8]> = vec![
        b"rust-scheduler-behaviour",
        rustc.version.as_bytes(),
        tag.as_bytes(),
        source.as_bytes(),
        expected_stdout.as_bytes(),
        stderr_contains.as_bytes(),
    ];
    let Some(stamp) = salvo_testkit::cached(
        env!("CARGO_TARGET_TMPDIR"),
        &format!("rust-scheduler {tag}"),
        &parts,
    ) else {
        return;
    };
    let dir = salvo_testkit::scratch(env!("CARGO_TARGET_TMPDIR"), &format!("sched-{tag}"));
    let src = dir.join("main.rs");
    std::fs::write(&src, &source).expect("failed to write the scheduler program");
    let bin = dir.join("program");
    let compile = Command::new("rustc")
        .arg("--edition")
        .arg("2021")
        .arg(&src)
        .arg("-o")
        .arg(&bin)
        .output()
        .expect("failed to run rustc");
    assert!(
        compile.status.success(),
        "rustc rejected the scheduler program {tag}:\n{}",
        String::from_utf8_lossy(&compile.stderr)
    );
    let child = Command::new(&bin)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .expect("failed to start the scheduler program");
    let run = wait_with_timeout(child, 30);
    let stdout = String::from_utf8_lossy(&run.stdout);
    let stderr = String::from_utf8_lossy(&run.stderr);
    assert_eq!(
        stdout, expected_stdout,
        "unexpected stdout from the scheduler program {tag}\nstderr:\n{stderr}"
    );
    assert_eq!(
        run.status.success(),
        expect_success,
        "unexpected exit status from the scheduler program {tag}\nstderr:\n{stderr}"
    );
    if !stderr_contains.is_empty() {
        assert!(
            stderr.contains(stderr_contains),
            "the scheduler program {tag} did not report {stderr_contains:?}:\nstderr:\n{stderr}"
        );
    }
    stamp.verified();
    let _ = std::fs::remove_dir_all(&dir);
}

/// Sends, a bounded queue the sender has to wait on, a reply token, and the
/// `waitfor` bridge: six messages through a queue bounded at four, then a
/// request whose reply crosses back into `main`.
#[test]
fn scheduler_delivers_sends_and_replies_through_a_bounded_queue() {
    run_scheduler_program(
        "queue-and-reply",
        r#"
struct Adder {
    sum: i64,
}

impl SalvoActor for Adder {
    fn handle(&mut self, _ctx: &SalvoCtx, msg: SalvoMsg) {
        match msg.downcast::<i64>() {
            Ok(n) => self.sum += *n,
            Err(other) => {
                if let Ok(reply) = other.downcast::<SalvoReply>() {
                    reply.send(Box::new(self.sum));
                }
            }
        }
    }
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, _value: SalvoMsg) {}
}

fn main() {
    let pool = salvo_pool(2);
    let adder = salvo_spawn(pool, 4, Box::new(Adder { sum: 0 }));
    // Six user messages through a queue bounded at four: the sender blocks
    // twice and nothing is lost.
    for n in 1..=6i64 {
        salvo_send(adder, Box::new(n));
    }
    let (token, wid) = salvo_waiter();
    salvo_send(adder, Box::new(token));
    let total = salvo_wait(wid);
    println!("sum: {}", total.downcast_ref::<i64>().unwrap());
}
"#,
        "sum: 21\n",
        true,
        "",
    );
}

/// The gate: while a gated continuation is outstanding, the process serves
/// *only* the awaited reply — a user message that arrived first waits.
#[test]
fn scheduler_gate_defers_user_messages_until_the_awaited_reply() {
    run_scheduler_program(
        "gate",
        r#"
/// The gated caller: on "go" it parks on a gated reply from the echo
/// process; "late" must not be served until the reply has landed.
struct Caller {
    echo: usize,
    log: Vec<String>,
}

impl SalvoActor for Caller {
    fn handle(&mut self, ctx: &SalvoCtx, msg: SalvoMsg) {
        let text = msg.downcast::<String>();
        match text {
            Ok(word) => {
                if *word == "go" {
                    let (token, _slot) = salvo_mint_gated(ctx.addr);
                    salvo_send(self.echo, Box::new(token));
                } else {
                    self.log.push(format!("user {word}"));
                }
            }
            Err(other) => {
                if let Ok(reply) = other.downcast::<SalvoReply>() {
                    // The finishing request: report the order things ran in.
                    reply.send(Box::new(self.log.join(", ")));
                }
            }
        }
    }
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, value: SalvoMsg) {
        let word = value.downcast::<String>().unwrap();
        self.log.push(format!("reply {word}"));
    }
}

/// Answers any reply token it is sent, after a beat so the "late" user
/// message is certainly queued first.
struct Echo;

impl SalvoActor for Echo {
    fn handle(&mut self, _ctx: &SalvoCtx, msg: SalvoMsg) {
        if let Ok(reply) = msg.downcast::<SalvoReply>() {
            std::thread::sleep(std::time::Duration::from_millis(120));
            reply.send(Box::new("R".to_string()));
        }
    }
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, _value: SalvoMsg) {}
}

fn main() {
    let pool = salvo_pool(3);
    let echo = salvo_spawn(pool, 4, Box::new(Echo));
    let caller = salvo_spawn(
        pool,
        4,
        Box::new(Caller {
            echo,
            log: Vec::new(),
        }),
    );
    salvo_send(caller, Box::new("go".to_string()));
    salvo_send(caller, Box::new("late".to_string()));
    let (token, wid) = salvo_waiter();
    salvo_send(caller, Box::new(token));
    let order = salvo_wait(wid);
    // The reply is served before the user message that was enqueued first.
    println!("order: {}", order.downcast_ref::<String>().unwrap());
}
"#,
        "order: reply R, user late\n",
        true,
        "",
    );
}

/// Death: a faulted activation kills the actor, `watch` reports the
/// reason as an ordinary one-shot reply, and later sends to the corpse are
/// silent no-ops rather than errors. The `Exit` value is built by the *watch
/// site*, since the language's struct is not the runtime's to construct
/// [actor-watch].
#[test]
fn scheduler_reports_a_faulted_activation_to_watchers() {
    run_scheduler_program(
        "fault-and-watch",
        r#"
struct Fragile;

impl SalvoActor for Fragile {
    fn handle(&mut self, _ctx: &SalvoCtx, msg: SalvoMsg) {
        let word = msg.downcast::<String>().unwrap();
        if *word == "boom" {
            panic!("boom");
        }
    }
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, _value: SalvoMsg) {}
}

fn main() {
    let pool = salvo_pool(2);
    let fragile = salvo_spawn(pool, 4, Box::new(Fragile));
    let (token, wid) = salvo_waiter();
    salvo_watch(fragile, token, |reason| Box::new(format!("exit({reason})")));
    salvo_send(fragile, Box::new("boom".to_string()));
    let exit = salvo_wait(wid);
    println!("exit: {}", exit.downcast_ref::<String>().unwrap());
    // A send to the dead is a no-op: this neither blocks nor fails.
    salvo_send(fragile, Box::new("ignored".to_string()));
    // And a watch registered after the death answers immediately, with the
    // reason the death recorded.
    let (late_token, late_wid) = salvo_waiter();
    salvo_watch(fragile, late_token, |reason| Box::new(format!("exit({reason})")));
    let late = salvo_wait(late_wid);
    println!("late watch: {}", late.downcast_ref::<String>().unwrap());
}
"#,
        "exit: exit(boom)\nlate watch: exit(boom)\n",
        true,
        "",
    );
}

/// [main-pool] [waitfor-pump] `main` is the single worker of its own pool,
/// and a wait *serves* that pool: an actor spawned on the main pool runs on
/// `main`'s own thread, while `main` waits — including while it waits for an
/// answer from somewhere else entirely. `salvo_thread()`, the dedicated
/// placement, is the somewhere else.
#[test]
fn scheduler_runs_main_pool_actors_while_main_waits() {
    run_scheduler_program(
        "main-pool",
        r#"
struct Adder {
    sum: i64,
}

impl SalvoActor for Adder {
    fn handle(&mut self, _ctx: &SalvoCtx, msg: SalvoMsg) {
        match msg.downcast::<i64>() {
            Ok(n) => self.sum += *n,
            Err(other) => {
                if let Ok(reply) = other.downcast::<SalvoReply>() {
                    reply.send(Box::new(self.sum));
                }
            }
        }
    }
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, _value: SalvoMsg) {}
}

/// Answers any reply token it is sent. Placed on a dedicated thread, so it
/// runs without `main` doing anything.
struct Echo;

impl SalvoActor for Echo {
    fn handle(&mut self, _ctx: &SalvoCtx, msg: SalvoMsg) {
        if let Ok(reply) = msg.downcast::<SalvoReply>() {
            reply.send(Box::new("R".to_string()));
        }
    }
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, _value: SalvoMsg) {}
}

fn main() {
    let dedicated = salvo_thread();
    let echo = salvo_spawn(dedicated, 2, Box::new(Echo));
    // No thread serves the main pool: `main` is its single worker, so
    // nothing queued here can have run before the first wait.
    let adder = salvo_spawn(SALVO_MAIN_POOL, 4, Box::new(Adder { sum: 0 }));
    for n in 1..=3i64 {
        salvo_send(adder, Box::new(n));
    }
    println!("queued on pool {}", salvo_current_pool());
    // A wait for an answer from the *dedicated* actor still serves the main
    // pool while it waits — which is where the three sends above run.
    let (echo_token, echo_wid) = salvo_waiter();
    salvo_send(echo, Box::new(echo_token));
    println!("echo: {}", salvo_wait(echo_wid).downcast_ref::<String>().unwrap());
    let (token, wid) = salvo_waiter();
    salvo_send(adder, Box::new(token));
    let total = salvo_wait(wid);
    println!("sum: {}", total.downcast_ref::<i64>().unwrap());
}
"#,
        "queued on pool 0\necho: R\nsum: 6\n",
        true,
        "",
    );
}

/// [main-pool] The full-main-pool-mailbox report: `main` fills a main-pool
/// actor's queue past its bound, and the only thread that could drain it is
/// the one blocked on it. A named error, not a hang.
#[test]
fn scheduler_reports_a_full_main_pool_mailbox() {
    run_scheduler_program(
        "main-pool-wedge",
        r#"
struct Sink;

impl SalvoActor for Sink {
    fn handle(&mut self, _ctx: &SalvoCtx, _msg: SalvoMsg) {}
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, _value: SalvoMsg) {}
}

fn main() {
    let sink = salvo_spawn(SALVO_MAIN_POOL, 2, Box::new(Sink));
    println!("filling");
    for n in 1..=3i64 {
        salvo_send(sink, Box::new(n));
    }
    println!("unreachable");
}
"#,
        "filling\n",
        false,
        "salvo: deadlock: the main pool's actor 0 has a full mailbox",
    );
}

/// [task-mint] [task-pool-inherit] A **task**: a reply token whose fulfilment
/// schedules a detached closure on a pool instead of delivering to an actor's
/// mailbox. Two of them here — one on an ordinary pool, one on the main pool,
/// where it runs on `main`'s own thread while `main` waits [waitfor-pump].
#[test]
fn scheduler_schedules_a_task_when_its_token_is_answered() {
    run_scheduler_program(
        "task",
        r#"
/// Answers any reply token it is sent with 21.
struct Echo;

impl SalvoActor for Echo {
    fn handle(&mut self, _ctx: &SalvoCtx, msg: SalvoMsg) {
        if let Ok(reply) = msg.downcast::<SalvoReply>() {
            reply.send(Box::new(21i64));
        }
    }
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, _value: SalvoMsg) {}
}

fn main() {
    let pool = salvo_pool(2);
    let echo = salvo_spawn(pool, 4, Box::new(Echo));

    // The task doubles the answer and hands it to `main`. It has no mailbox,
    // no identity and no capacity reserved: the closure *is* the continuation.
    let (waiter, wid) = salvo_waiter();
    let task = salvo_mint_task(
        pool,
        Box::new(move |value| {
            let n = *value.downcast::<i64>().expect("the answer");
            waiter.send(Box::new(n * 2));
        }),
    );
    salvo_send(echo, Box::new(task));
    println!("doubled: {}", salvo_wait(wid).downcast_ref::<i64>().unwrap());

    // The same on the main pool: nothing serves it but `main`'s own wait.
    let (main_waiter, main_wid) = salvo_waiter();
    let on_main = salvo_mint_task(
        SALVO_MAIN_POOL,
        Box::new(move |value| {
            let n = *value.downcast::<i64>().expect("the answer");
            main_waiter.send(Box::new(format!("ran on pool {}, n={n}", salvo_current_pool())));
        }),
    );
    let echoed = salvo_spawn(pool, 4, Box::new(Echo));
    salvo_send(echoed, Box::new(on_main));
    println!("{}", salvo_wait(main_wid).downcast_ref::<String>().unwrap());
}
"#,
        "doubled: 42
ran on pool 0, n=21
",
        true,
        "",
    );
}

/// [pool-fault-sink] A task that faults has no addr to `watch`, so the fault
/// goes to the **pool's sink**: an ordinary actor, sent an ordinary message
/// the *pool creation site* built (the runtime cannot construct a Salvo
/// value). Without a sink it is the named report on stderr instead.
#[test]
fn scheduler_reports_a_faulted_task_to_the_pools_sink() {
    run_scheduler_program(
        "task-fault-sink",
        r#"
/// Holds `main`'s token, then forwards the first fault it is told about.
struct Sink {
    done: Option<SalvoReply>,
}

impl SalvoActor for Sink {
    fn handle(&mut self, _ctx: &SalvoCtx, msg: SalvoMsg) {
        match msg.downcast::<SalvoReply>() {
            Ok(reply) => self.done = Some(*reply),
            Err(other) => {
                if let Ok(text) = other.downcast::<String>() {
                    if let Some(done) = self.done.take() {
                        done.send(Box::new(format!("sink got {text}")));
                    }
                }
            }
        }
    }
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, _value: SalvoMsg) {}
}

fn main() {
    let sink_pool = salvo_pool(1);
    let sink = salvo_spawn(sink_pool, 4, Box::new(Sink { done: None }));
    let (token, wid) = salvo_waiter();
    salvo_send(sink, Box::new(token));

    // The faulting task runs on a pool whose faults go to the sink.
    let work = salvo_pool_with_sink(1, Some((sink, |reason| Box::new(format!("fault({reason})")))));
    let task = salvo_mint_task(work, Box::new(|_value| panic!("boom")));
    task.send(Box::new(0i64));
    println!("{}", salvo_wait(wid).downcast_ref::<String>().unwrap());

    // A pool with no sink names the fault on stderr instead, and the program
    // carries on: a task's death is not the program's.
    let quiet = salvo_pool(1);
    let unheard = salvo_mint_task(quiet, Box::new(|_value| panic!("unheard")));
    unheard.send(Box::new(0i64));
    let (last, last_wid) = salvo_waiter();
    let done = salvo_mint_task(quiet, Box::new(move |_value| last.send(Box::new(1i64))));
    done.send(Box::new(0i64));
    let _ = salvo_wait(last_wid);
    println!("done");
}
"#,
        "sink got fault(boom)
done
",
        true,
        "salvo: an uncaught fault on pool",
    );
}

/// The idle-with-parked-gates report: `main` waits for a reply nothing can
/// ever send, and the scheduler says so and exits non-zero instead of
/// hanging [actor-watch].
#[test]
fn scheduler_reports_idle_while_main_waits() {
    run_scheduler_program(
        "idle-report",
        r#"
struct Idle;

impl SalvoActor for Idle {
    fn handle(&mut self, _ctx: &SalvoCtx, _msg: SalvoMsg) {}
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, _value: SalvoMsg) {}
}

fn main() {
    let pool = salvo_pool(1);
    let _idle = salvo_spawn(pool, 2, Box::new(Idle));
    println!("waiting");
    // Nobody holds this token, so nothing can ever fulfil it.
    let (_token, wid) = salvo_waiter();
    let _never = salvo_wait(wid);
    println!("unreachable");
}
"#,
        "waiting\n",
        false,
        "salvo: deadlock: all actors idle while main waits",
    );
}

/// [actor-on-idle] The quiescence hook: a registered token is answered the
/// moment nothing anywhere can run, and the payload says whether the program
/// is *done* or merely *stuck*. Registered twice, so both answers are in one
/// run: first with the pool settled and nothing outstanding, then with an
/// actor gated on a reply another actor has parked and will never send.
///
/// The counts are what make the hook a test instrument rather than a bell:
/// "the work I sent has finished" is otherwise a guess about how many
/// messages the code under test sends.
#[test]
fn scheduler_answers_a_quiescence_hook_with_the_parked_counts() {
    run_scheduler_program(
        "idle-hook",
        r#"
/// Parks every token it is given and answers none: the obligation stays
/// outstanding, which is what the second report has to see.
struct Holder {
    held: Vec<SalvoReply>,
}

impl SalvoActor for Holder {
    fn handle(&mut self, _ctx: &SalvoCtx, msg: SalvoMsg) {
        self.held.push(*msg.downcast::<SalvoReply>().unwrap());
    }
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, _value: SalvoMsg) {}
}

/// Gates itself on an answer from the holder, so its mailbox is stalled for
/// good.
struct Asker {
    holder: usize,
}

impl SalvoActor for Asker {
    fn handle(&mut self, ctx: &SalvoCtx, _msg: SalvoMsg) {
        let (token, _slot) = salvo_mint_gated(ctx.addr);
        salvo_send(self.holder, Box::new(token));
    }
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, _value: SalvoMsg) {}
}

fn report(gates: i32, tokens: i32) -> SalvoMsg {
    Box::new(format!("gates {gates}, tokens {tokens}"))
}

fn main() {
    let pool = salvo_pool(1);
    let holder = salvo_spawn(pool, 4, Box::new(Holder { held: Vec::new() }));
    let asker = salvo_spawn(pool, 4, Box::new(Asker { holder }));
    // Nothing has been sent, so the answer is "done".
    let (first, w1) = salvo_waiter();
    salvo_on_idle(pool, first, report);
    println!("settled: {}", salvo_wait(w1).downcast_ref::<String>().unwrap());
    // The hook cannot fire before the message it was registered after has
    // run: a queued entry is deliverable, so the scheduler is not idle.
    salvo_send(asker, Box::new("go".to_string()));
    let (second, w2) = salvo_waiter();
    salvo_on_idle(pool, second, report);
    println!("stuck: {}", salvo_wait(w2).downcast_ref::<String>().unwrap());
}
"#,
        "settled: gates 0, tokens 0\nstuck: gates 1, tokens 1\n",
        true,
        "",
    );
}

/// [actor-on-idle] The same hook registered *by an actor*, on a continuation
/// of its own: quiescence is observed by whichever thread runs dry, so nobody
/// has to be waiting for the answer to arrive. The pool it asks about is
/// `main`'s, whose one outstanding token is the one the actor is holding — so
/// the count is 1 while the actor's own pool is clean.
#[test]
fn a_quiescence_hook_registered_by_an_actor_is_fired_by_a_worker() {
    run_scheduler_program(
        "idle-hook-actor",
        r#"
struct Watcher {
    out: Option<SalvoReply>,
}

impl SalvoActor for Watcher {
    fn handle(&mut self, ctx: &SalvoCtx, msg: SalvoMsg) {
        // `main`'s token is kept, so the main pool is owed one answer, and
        // the registration is a continuation on this actor.
        self.out = Some(*msg.downcast::<SalvoReply>().unwrap());
        let (token, _slot) = salvo_mint(ctx.addr);
        salvo_on_idle(SALVO_MAIN_POOL, token, report);
    }
    fn resume(&mut self, _ctx: &SalvoCtx, _slot: u64, value: SalvoMsg) {
        self.out.take().unwrap().send(value);
    }
}

fn report(gates: i32, tokens: i32) -> SalvoMsg {
    Box::new(format!("gates {gates}, tokens {tokens}"))
}

fn main() {
    let pool = salvo_pool(1);
    let watcher = salvo_spawn(pool, 4, Box::new(Watcher { out: None }));
    let (token, wid) = salvo_waiter();
    salvo_send(watcher, Box::new(token));
    println!(
        "from the actor: {}",
        salvo_wait(wid).downcast_ref::<String>().unwrap()
    );
}
"#,
        "from the actor: gates 0, tokens 1\n",
        true,
        "",
    );
}
