//! [rs-runtime-source] The backend's *runtime modules* — `runtime/*.rs`,
//! included verbatim by the emitter and written into a program's output when
//! it touches the feature — compiled directly by `rustc`.
//!
//! Why this exists: those modules used to be Rust string literals inside
//! `emit.rs`, which meant they were only ever compiled as part of a whole
//! generated program. A syntax error in one showed up as a failure in some
//! unrelated end-to-end test, and reviewing a change to one meant reviewing
//! a diff of an escaped string. As real source files they are reviewable as
//! code and verified here on their own — which is the standing form of the
//! "hand-verify the generated shape before teaching it to the emitter"
//! rule from COMPLETED.md's gotchas.
//!
//! Each module must compile **warning-free** as a library crate: it is
//! spliced into user output, where a warning is noise the user cannot fix.
//! Skipped when `rustc` is not on PATH, like every other toolchain test.

use std::process::Command;

/// Every static runtime module, with the emitter accessor that ships it.
/// A new one belongs here the moment it exists — the list is what makes
/// this test complete rather than a sample.
const RUNTIME_MODULES: &[&str] = &["strings.rs", "seq.rs"];

/// The bytes the emitter will splice, read from the same path `include_str!`
/// reads at compile time.
fn runtime_source(file: &str) -> String {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("runtime")
        .join(file);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read the runtime module {}: {e}", path.display()))
}

/// Compiles one runtime module as a library crate and asserts that `rustc`
/// accepted it *and* said nothing.
fn compile_runtime_module(file: &str) {
    let rustc = salvo_testkit::rustc();
    if !rustc.available {
        return;
    }
    let source = runtime_source(file);
    let parts: Vec<&[u8]> = vec![
        b"rust-runtime-module",
        rustc.version.as_bytes(),
        file.as_bytes(),
        source.as_bytes(),
    ];
    let Some(stamp) = salvo_testkit::cached(
        env!("CARGO_TARGET_TMPDIR"),
        &format!("rust-runtime {file}"),
        &parts,
    ) else {
        return;
    };
    let dir = salvo_testkit::scratch(env!("CARGO_TARGET_TMPDIR"), &format!("rt-{file}"));
    let src = dir.join(file);
    std::fs::write(&src, &source).expect("failed to write the runtime module");
    let out = Command::new("rustc")
        .arg("--edition")
        .arg("2021")
        .arg("--crate-type")
        .arg("lib")
        .arg(&src)
        .arg("-o")
        .arg(dir.join("libruntime.rlib"))
        .output()
        .expect("failed to run rustc");
    assert!(
        out.status.success(),
        "rustc rejected runtime/{file}:\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let noise = String::from_utf8_lossy(&out.stderr);
    assert!(
        noise.trim().is_empty(),
        "runtime/{file} compiles with warnings, which would land in user output:\n{noise}"
    );
    stamp.verified();
}

#[test]
fn every_runtime_module_compiles_warning_free() {
    for file in RUNTIME_MODULES {
        compile_runtime_module(file);
    }
}

/// The emitted content and the file on disk must be the same bytes: the
/// emitter uses `include_str!`, so a stale copy cannot drift silently, but a
/// *renamed* or accidentally rewritten module would slip past that. Reading
/// both here keeps the list above honest.
#[test]
fn runtime_modules_are_not_empty_and_are_generated_headers() {
    for file in RUNTIME_MODULES {
        let source = runtime_source(file);
        assert!(
            source.starts_with("// Generated by the Salvo compiler:"),
            "runtime/{file} must open with the generated-by header, since it is \
             spliced into user output"
        );
        assert!(
            source.ends_with('\n'),
            "runtime/{file} must end with a newline"
        );
    }
}
