// Generated by the Salvo compiler: insertion-ordered collections.
//
// Salvo's `Map<K, V>` and `Set<T>` iterate in **insertion order** on every
// backend [col-insertion-order]. Kotlin gets that from `LinkedHashMap` /
// `LinkedHashSet`; Rust's own `HashMap`/`HashSet` do not provide it (their
// order is unspecified and randomly seeded per process), and the standard
// library has no ordered hash map, so this file is the equivalent. The
// observable semantics are LinkedHashMap's, exactly:
//
//   * iteration yields entries in first-insertion order;
//   * overwriting an existing key updates the value and **keeps** the
//     key's original position;
//   * removal is O(1) and preserves the order of everything else;
//   * equality is order-insensitive content equality, like
//     `AbstractMap.equals` on the JVM.
//
// Representation: entries live in a `Vec` in insertion order, and a
// `HashMap` indexes key -> slot. A removed slot becomes `None` so the
// stored indices stay valid, and the slab is compacted once the dead slots
// outnumber the live ones — which keeps removal amortized O(1) without
// letting an add/remove loop grow the vector without bound.
//
// **Where the bounds sit matters.** The struct definitions carry none, and
// each operation carries only what it needs: hashing a key needs
// `Hash + Eq + Clone`, but *walking* a collection does not. That is what
// lets a generic Salvo function (`fn iter<T>(set: Set<T>)`, whose emitted
// signature has only the bounds Salvo knows about) iterate a `Set<T>` at
// all — a bound on the struct would have to be repeated by every generated
// signature that so much as mentions the type.

use std::collections::HashMap;
use std::fmt;
use std::hash::Hash;

pub struct SalvoMap<K, V> {
    slots: Vec<Option<(K, V)>>,
    index: HashMap<K, usize>,
}

// Operations that never hash a key: available for any `K`.
impl<K, V> SalvoMap<K, V> {
    pub fn new() -> Self {
        SalvoMap {
            slots: Vec::new(),
            index: HashMap::new(),
        }
    }

    pub fn len(&self) -> usize {
        self.index.len()
    }

    pub fn is_empty(&self) -> bool {
        self.index.is_empty()
    }

    /// Entries in insertion order.
    pub fn iter(&self) -> impl Iterator<Item = (&K, &V)> + '_ {
        self.slots
            .iter()
            .filter_map(|s| s.as_ref().map(|(k, v)| (k, v)))
    }

    pub fn keys(&self) -> impl Iterator<Item = &K> + '_ {
        self.iter().map(|(k, _)| k)
    }

    pub fn values(&self) -> impl Iterator<Item = &V> + '_ {
        self.iter().map(|(_, v)| v)
    }
}

// Operations that hash.
impl<K: Hash + Eq + Clone, V> SalvoMap<K, V> {
    /// The constructor lowering's entry point: `map_of(("a", 1), ...)`.
    /// A repeated key keeps the position of its first appearance and takes
    /// the value of its last [col-duplicate-keys].
    pub fn from_entries<I: IntoIterator<Item = (K, V)>>(entries: I) -> Self {
        let mut map = SalvoMap::new();
        for (k, v) in entries {
            map.insert(k, v);
        }
        map
    }

    /// Inserts or overwrites. An overwrite keeps the key's original
    /// position, so iteration order is stable under updates.
    pub fn insert(&mut self, key: K, value: V) {
        match self.index.get(&key) {
            Some(&i) => self.slots[i] = Some((key, value)),
            None => {
                self.slots.push(Some((key.clone(), value)));
                self.index.insert(key, self.slots.len() - 1);
            }
        }
    }

    pub fn get(&self, key: &K) -> Option<&V> {
        let i = *self.index.get(key)?;
        self.slots[i].as_ref().map(|(_, v)| v)
    }

    pub fn get_mut(&mut self, key: &K) -> Option<&mut V> {
        let i = *self.index.get(key)?;
        self.slots[i].as_mut().map(|(_, v)| v)
    }

    /// Removes the entry and hands its value back — the shape Salvo's
    /// `remove(map, key) -> V?` needs, so a caller can take ownership of
    /// what the map was holding.
    pub fn remove(&mut self, key: &K) -> Option<V> {
        let i = self.index.remove(key)?;
        let taken = self.slots[i].take().map(|(_, v)| v);
        self.compact_if_sparse();
        taken
    }

    pub fn contains_key(&self, key: &K) -> bool {
        self.index.contains_key(key)
    }

    fn compact_if_sparse(&mut self) {
        let live = self.index.len();
        if self.slots.len() <= 2 * live + 8 {
            return;
        }
        self.slots.retain(|s| s.is_some());
        self.index.clear();
        for (i, slot) in self.slots.iter().enumerate() {
            if let Some((k, _)) = slot {
                self.index.insert(k.clone(), i);
            }
        }
    }
}

impl<K, V> Default for SalvoMap<K, V> {
    fn default() -> Self {
        SalvoMap::new()
    }
}

// Field-wise, so no key is rehashed and no bound beyond `Clone` is needed.
impl<K: Clone, V: Clone> Clone for SalvoMap<K, V> {
    fn clone(&self) -> Self {
        SalvoMap {
            slots: self.slots.clone(),
            index: self.index.clone(),
        }
    }
}

/// Order-insensitive, matching the JVM's `AbstractMap.equals` so `==` on a
/// map means the same thing on both backends [col-equality].
impl<K: Hash + Eq + Clone, V: PartialEq> PartialEq for SalvoMap<K, V> {
    fn eq(&self, other: &Self) -> bool {
        self.len() == other.len() && self.iter().all(|(k, v)| other.get(k) == Some(v))
    }
}

impl<K: Hash + Eq + Clone, V: Eq> Eq for SalvoMap<K, V> {}

/// `{a: 1, b: 2}` — the language's format, in insertion order, matching
/// the map literal that would build it [col-to-str]. Walking only, so no
/// hashing bound.
impl<K: fmt::Display, V: fmt::Display> fmt::Display for SalvoMap<K, V> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{")?;
        for (i, (k, v)) in self.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{}: {}", k, v)?;
        }
        write!(f, "}}")
    }
}

// `{:?}` is how an interpolated struct renders its fields [rs-display], so
// a struct holding a map needs this; it prints the language's format
// rather than Rust's, for the same reason `to_str` does.
impl<K: fmt::Display, V: fmt::Display> fmt::Debug for SalvoMap<K, V> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self)
    }
}

pub struct SalvoSet<T> {
    // A set is a map to nothing: one representation, so the two cannot
    // drift apart on ordering or removal semantics.
    entries: SalvoMap<T, ()>,
}

// Operations that never hash an element.
impl<T> SalvoSet<T> {
    pub fn new() -> Self {
        SalvoSet {
            entries: SalvoMap::new(),
        }
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Elements in insertion order.
    pub fn iter(&self) -> impl Iterator<Item = &T> + '_ {
        self.entries.keys()
    }
}

// Operations that hash.
impl<T: Hash + Eq + Clone> SalvoSet<T> {
    pub fn from_elements<I: IntoIterator<Item = T>>(elems: I) -> Self {
        let mut set = SalvoSet::new();
        for e in elems {
            set.insert(e);
        }
        set
    }

    /// `true` when the element was newly added, which is what Salvo's
    /// `add(set, elem) -> Bool` reports.
    pub fn insert(&mut self, elem: T) -> bool {
        if self.entries.contains_key(&elem) {
            return false;
        }
        self.entries.insert(elem, ());
        true
    }

    /// `true` when the element was present.
    pub fn remove(&mut self, elem: &T) -> bool {
        self.entries.remove(elem).is_some()
    }

    pub fn contains(&self, elem: &T) -> bool {
        self.entries.contains_key(elem)
    }
}

impl<T> Default for SalvoSet<T> {
    fn default() -> Self {
        SalvoSet::new()
    }
}

impl<T: Clone> Clone for SalvoSet<T> {
    fn clone(&self) -> Self {
        SalvoSet {
            entries: self.entries.clone(),
        }
    }
}

/// Order-insensitive, like the JVM's `AbstractSet.equals`.
impl<T: Hash + Eq + Clone> PartialEq for SalvoSet<T> {
    fn eq(&self, other: &Self) -> bool {
        self.len() == other.len() && self.iter().all(|e| other.contains(e))
    }
}

impl<T: Hash + Eq + Clone> Eq for SalvoSet<T> {}

/// `{1, 2, 3}` — the set literal that would build it.
impl<T: fmt::Display> fmt::Display for SalvoSet<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{")?;
        for (i, e) in self.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{}", e)?;
        }
        write!(f, "}}")
    }
}

impl<T: fmt::Display> fmt::Debug for SalvoSet<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self)
    }
}
