[package]
name = "salvo-backend-kotlin"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Kotlin backend for the Salvo compiler"

[dependencies]
salvo-syntax = { workspace = true }
salvo-core = { workspace = true }
salvo-backend = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
