// Generated by the Salvo compiler: the actor scheduler — asynchronous
// effect handlers' runtime. Actors are run-to-completion: a `send`
// enqueues a member invocation, a pool worker runs one activation at a
// time per actor, and nothing here suspends. The semantics it implements are
// LANGUAGE_SPEC.md's [actor-kind] … [actor-watch]: per-actor bounded queues (bound explicit at spawn; a full
// queue blocks the sender), reply tokens with reserved capacity (a reply
// never blocks and never counts against the bound), the gate (at most one
// outstanding gated continuation per actor; while gated, only the
// awaited reply is delivered), death = a faulted activation (caught at
// the dispatch boundary; sends and replies to the dead are silent
// no-ops), `watch` notification as a one-shot reply, the quiescence hook
// ([actor-on-idle]: a registered token answered when nothing anywhere can
// run), and the deadlock report — nothing left that can run while a frame
// waits, and no hook to fire, is a named runtime error rather than a hang.
// The waiting frame need not be `main`: an activation parked in a nested wait
// holds its actor's `running` flag, so its own mailbox is stalled while it
// waits, and the report counts parked frames out of the running ones.
//
// [main-pool] [waitfor-pump] `main` is the **single worker of its own
// pool** (pool 0), which is given no OS thread: `main`'s own thread is its
// worker, and it works while it waits. A wait therefore *serves* its pool
// rather than merely blocking on it — the uniform rule is that a `waitfor`
// serves its own pool's work except activations of the actor doing the
// waiting, so a waiting actor's mailbox stays stalled (serialization is
// preserved) while `main`, which has no mailbox, serves everything placed
// on its pool. Blocking is the degenerate case of an empty queue.

use std::any::Any;
use std::cell::Cell;
use std::collections::VecDeque;
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::sync::{Condvar, Mutex, MutexGuard, OnceLock};

/// A message payload: any sendable value. The checker owns sendability
/// statically; the runtime is untyped.
pub type SalvoMsg = Box<dyn Any + Send>;

/// An actor body: state plus one entry point per kind of delivery.
/// Generated code implements `handle` as the member dispatch and `resume`
/// as the parked-continuation dispatch (by slot).
pub trait SalvoActor: Send {
    /// A user message (a `send fn` invocation).
    fn handle(&mut self, ctx: &SalvoCtx, msg: SalvoMsg);
    /// A reply delivery: the slot names the parked continuation.
    fn resume(&mut self, ctx: &SalvoCtx, slot: u64, value: SalvoMsg);
}

/// Passed to every activation: the actor's own identity.
pub struct SalvoCtx {
    pub addr: usize,
}

/// A one-shot reply capability. `send` consumes it — one shot by move in
/// the runtime too, though the *guarantee* is the checker's.
pub struct SalvoReply {
    target: Target,
    slot: u64,
    /// [actor-on-idle] Whether this token still counts as an obligation the
    /// program owes. A mint counts it; a delivery, or a handover to the
    /// scheduler itself (`salvo_watch`, `salvo_on_idle`), stops counting it —
    /// what an `Idle` payload reports is work *user code* has not answered,
    /// not registrations the scheduler will answer on its own.
    tracked: bool,
}

enum Target {
    Proc(usize),
    Waiter(usize),
    /// [task-mint] A **detached one-shot**: no mailbox, no identity, no
    /// capacity to reserve — the continuation *is* the closure, and the pool
    /// is where it will run. Chosen at the mint [task-pool-inherit], because
    /// whoever creates work pays for it.
    Task(usize, TaskBody),
}

/// [task-mint] A task body: a one-shot closure taking the answer. `FnOnce`
/// and `Send`, which is what the sendability check proves statically
/// [actor-sendable].
pub type TaskBody = Box<dyn FnOnce(SalvoMsg) + Send>;

enum Entry {
    User(SalvoMsg),
    Reply(u64, SalvoMsg),
}

struct ActorState {
    queue: VecDeque<Entry>,
    /// User entries currently queued; replies are reserved and not counted.
    user_len: usize,
    bound: usize,
    /// While `Some(slot)`, only the reply for `slot` may be delivered.
    gate: Option<u64>,
    running: bool,
    dead: bool,
    /// The host's account of the fault that killed it, kept so a watch
    /// registered *after* the death answers what the earlier watchers got.
    exit_reason: Option<String>,
    pool: usize,
    /// [actor-watch] Registered death watches: the token to fulfil and the
    /// **builder** generated code handed over with it, which turns the
    /// reason into the language's `Exit` value. The runtime cannot construct
    /// a Salvo struct, so the watch site supplies the constructor.
    watchers: Vec<(SalvoReply, ExitOf)>,
    /// [actor-on-idle] Reply tokens aimed at this actor that nobody has
    /// discharged — the continuations it is still owed. A token whose holder
    /// died stays counted, which is the honest answer: the obligation is
    /// genuinely lost.
    owed: usize,
    /// Taken out while an activation runs.
    body: Option<Box<dyn SalvoActor>>,
}

/// [actor-watch] Builds the `Exit` payload from the fault's reason. A plain
/// fn pointer, so it is `Send` without a bound.
pub type ExitOf = fn(String) -> SalvoMsg;

/// [actor-on-idle] Builds the `Idle` payload from the counts, exactly as
/// `ExitOf` builds an `Exit`: the runtime holds numbers and cannot construct a
/// Salvo struct, so the registration site supplies the constructor.
pub type IdleOf = fn(i32, i32) -> SalvoMsg;

/// [time-timer] Builds the `Fired` payload from the monotonic reading the
/// deadline came due at — `ExitOf`'s shape again, for the same reason.
pub type FiredOf = fn(i64) -> SalvoMsg;

struct WaiterState {
    value: Option<SalvoMsg>,
    /// [actor-on-idle] The pool of the frame that is waiting, which is what a
    /// token targeting this waiter is owed *by* for the purposes of an `Idle`
    /// payload.
    pool: usize,
    /// [waitfor-pump] While this waiter is parked: the actor whose activation
    /// is parked on it, if the waiting frame is one. `Some(None)` is a park
    /// that belongs to no actor (`main` or a task); `None` is not parked at
    /// all. What the deadlock report reads to name the **occupied** actors —
    /// the ones whose mailbox is stalled by a wait nested inside an
    /// activation.
    parked: Option<Option<usize>>,
}

/// [task-mint] What a pool owns besides its worker threads: a queue of
/// detached tasks, and the sink an uncaught fault on it is reported to
/// [pool-fault-sink].
struct PoolState {
    /// Tasks whose answer has arrived, in the order it arrived.
    tasks: VecDeque<(TaskBody, SalvoMsg)>,
    /// [pool-fault-sink] Where a fault on this pool goes: an actor's addr and
    /// the builder that turns the host's reason into the language's `Fault`.
    /// `None` is the named runtime report.
    sink: Option<(usize, ExitOf)>,
    /// [actor-on-idle] Undischarged tokens that belong to this pool without
    /// belonging to an actor on it: a task waiting for its answer, and the
    /// token a frame working for this pool is parked on.
    owed: usize,
}

struct Sched {
    actors: Vec<ActorState>,
    waiters: Vec<WaiterState>,
    pools: Vec<PoolState>,
    next_slot: u64,
    /// Activations currently running, across all pools.
    active: usize,
    /// [waitfor-pump] Of those, the ones parked in a `salvo_wait`: an
    /// activation or a task whose frame is alive on some thread's stack but
    /// which cannot proceed until its token arrives. It still holds its
    /// actor's `running` flag — so its mailbox is stalled and nobody else
    /// will serve it — which is why a parked frame is *not* progress and must
    /// not hide a deadlock. `active - parked_frames` is the number of frames
    /// that can still get somewhere on their own.
    parked_frames: usize,
    /// [waitfor-pump] How deep `main`'s own thread is in `salvo_wait`.
    /// `main` is the one thread that runs program code without being a frame
    /// the scheduler counts, so while it is *not* waiting it is progress the
    /// scheduler cannot see, and no deadlock may be declared.
    main_waits: usize,
    /// [actor-on-idle] Registered quiescence hooks: the pool whose
    /// obligations the answer reports, the token to fulfil, and the builder
    /// for its payload. Taken as a whole when the scheduler settles — every
    /// registration is a one-shot.
    idle_hooks: Vec<(usize, SalvoReply, IdleOf)>,
    /// [time-timer] Registered deadlines, each a monotonic reading with the
    /// token to fulfil when it passes and the builder for the `Fired` payload.
    /// Unordered: a Salvo program registers few deadlines at a time, and one
    /// scan per wake is cheaper than keeping a heap ordered under a lock the
    /// whole scheduler shares.
    timers: Vec<(i64, SalvoReply, FiredOf)>,
    /// [time-timer] Whether the deadline thread is running. Started by the
    /// first `salvo_after`, so a program that never sets a timer has no timer
    /// thread — and one that does has exactly one, never a thread per timer.
    timer_thread: bool,
}

fn state() -> &'static (Mutex<Sched>, Condvar) {
    static STATE: OnceLock<(Mutex<Sched>, Condvar)> = OnceLock::new();
    STATE.get_or_init(|| {
        (
            Mutex::new(Sched {
                actors: Vec::new(),
                waiters: Vec::new(),
                // [main-pool] Pool 0 exists from the start and belongs to
                // `main`; the first `salvo_pool` therefore answers 1.
                pools: vec![PoolState {
                    tasks: VecDeque::new(),
                    sink: None,
                    owed: 0,
                }],
                next_slot: 0,
                active: 0,
                parked_frames: 0,
                main_waits: 0,
                idle_hooks: Vec::new(),
                timers: Vec::new(),
                timer_thread: false,
            }),
            Condvar::new(),
        )
    })
}

/// [main-pool] The pool `main` is the single worker of. It is never given a
/// worker thread of its own: `main`'s thread is the worker, and it runs the
/// pool's work while it waits in `salvo_wait`.
pub const SALVO_MAIN_POOL: usize = 0;

/// Where a thread is. Saved and restored by every frame, so a nested wait
/// reads the frame it is actually inside.
#[derive(Clone, Copy)]
struct Here {
    /// The pool this thread works for — what a `spawn` or a mint with no
    /// `on` clause inherits, and the pool a wait serves [waitfor-pump].
    pool: usize,
    /// The actor whose activation this thread is currently inside (`None` on
    /// `main`, inside a task, and between activations): the one actor a wait
    /// must not serve.
    actor: Option<usize>,
    /// Whether this thread is inside a frame that counts in `active` — an
    /// activation or a task. `main`'s own thread is not one, which is what
    /// distinguishes it from a task running on the main pool. Read by
    /// `salvo_wait` to decide *which* kind of park this wait is.
    frame: bool,
}

thread_local! {
    static HERE: Cell<Here> = Cell::new(Here {
        pool: SALVO_MAIN_POOL,
        actor: None,
        frame: false,
    });
}

/// [main-pool] The pool the calling thread works for — what a `spawn` or a
/// mint with no `on` clause inherits. `main`'s thread answers the main pool.
pub fn salvo_current_pool() -> usize {
    HERE.with(|h| h.get().pool)
}

/// [waitfor-dedicated] A pool of exactly one thread, for work that may
/// occupy its thread until an answer arrives. Identical to `salvo_pool(1)`
/// at run time — what makes it different is static: the language types it as
/// a `Dedicated Pool` and the `on` clause consumes it, so a dedicated thread
/// has exactly one occupant.
pub fn salvo_thread() -> usize {
    salvo_pool(1)
}

/// The index of the first deliverable entry for an actor, honouring the
/// gate: ungated, the queue's head; gated, only the awaited reply.
fn deliverable(p: &ActorState) -> Option<usize> {
    if p.running || p.dead {
        return None;
    }
    match p.gate {
        None => {
            if p.queue.is_empty() {
                None
            } else {
                Some(0)
            }
        }
        Some(slot) => p.queue.iter().position(|e| matches!(e, Entry::Reply(s, _) if *s == slot)),
    }
}

/// True when no work is *queued* anywhere: no actor has a deliverable entry,
/// no pool has a scheduled task, no deadline is pending, and no parked frame
/// has an answer sitting in its slot.
///
/// [waitfor-pump] That last clause is a queue too, even though it looks like a
/// variable: a fulfilled waiter slot is work whose *pickup is the waiting
/// thread itself*, which will take it at the top of its next pass. Between the
/// delivery and the pickup the frame is still booked as parked, so without this
/// clause a thread that looked in that window would call a program stuck one
/// instant before it proceeds.
///
/// [time-timer] A pending deadline counts as work on its way: the timer thread
/// will deliver it, so a program waiting for a fire is neither quiescent
/// ([actor-on-idle]) nor deadlocked — it is waiting for time to pass, which is
/// the one thing that happens without anybody running.
fn quiet(s: &Sched) -> bool {
    s.actors.iter().all(|p| deliverable(p).is_none())
        && s.pools.iter().all(|p| p.tasks.is_empty())
        && s.timers.is_empty()
        && s.waiters
            .iter()
            .all(|w| !(w.parked.is_some() && w.value.is_some()))
}

/// True when nothing can ever run again without outside input: no
/// activation is running and no actor has a deliverable entry.
///
/// [actor-on-idle] What the quiescence hook fires on. A frame parked in a
/// `waitfor` counts as running here, so idleness does not fire while any wait
/// is in flight — the stated caveat of the rule.
fn idle(s: &Sched) -> bool {
    s.active == 0 && quiet(s)
}

/// True when nothing can ever run again *and* somebody is waiting for
/// something — the deadlock condition, which is weaker than `idle` in exactly
/// one way: a frame **parked in a `salvo_wait`** is not progress.
///
/// [waitfor-pump] Every clause is a thread that could still get somewhere:
///
/// * `active - parked_frames > 0` — a frame is running rather than parked (a
///   body between two waits, or a sender blocked on a full mailbox, which
///   will proceed when the mailbox drains).
/// * `main_waits == 0` — `main`'s thread is running program code, which the
///   scheduler does not count as a frame and therefore cannot see. Whatever
///   it does next may fulfil the token that is being waited on.
/// * `!quiet` — something is queued, so whoever runs next will run it.
///
/// With all of them false, every thread the scheduler knows about is parked
/// on an answer and nothing is queued to produce one: the wait cannot end.
/// The remaining blind spot is stated with [actor-on-idle] and is the same one
/// the report has always had — a platform handler with a thread of its own can
/// inject work the scheduler never saw.
fn stuck(s: &Sched) -> bool {
    s.active == s.parked_frames && s.main_waits > 0 && quiet(s)
}

/// [actor-on-idle] Marks one token as no longer outstanding, against whatever
/// it was owed by: the actor it targets, the pool a task will run on, or the
/// pool of the frame parked on it. Saturating, so a double release cannot wrap.
fn release(s: &mut Sched, target: &Target) {
    let owed = match *target {
        Target::Proc(addr) => &mut s.actors[addr].owed,
        Target::Task(pool, _) => &mut s.pools[pool].owed,
        Target::Waiter(wid) => {
            let pool = s.waiters[wid].pool;
            &mut s.pools[pool].owed
        }
    };
    *owed = owed.saturating_sub(1);
}

/// [actor-on-idle] Hands a token over to the scheduler: it stops counting as
/// an obligation the program owes, because the scheduler is now the one who
/// will answer it. Used by `salvo_watch` and `salvo_on_idle`, which is why a
/// steady-state program with registrations outstanding still reports zero.
fn untrack(s: &mut Sched, mut reply: SalvoReply) -> SalvoReply {
    if reply.tracked {
        reply.tracked = false;
        release(s, &reply.target);
    }
    reply
}

/// [actor-on-idle] What an `Idle` payload says about a pool: how many actors
/// placed there have a gated mailbox, and how many reply tokens aimed at work
/// there nobody has discharged. Both zero is "done"; either non-zero is "idle
/// and still owed something".
fn parked(s: &Sched, pool: usize) -> (i32, i32) {
    let gates = s
        .actors
        .iter()
        .filter(|p| p.pool == pool && p.gate.is_some() && !p.dead)
        .count();
    let tokens: usize = s
        .actors
        .iter()
        .filter(|p| p.pool == pool)
        .map(|p| p.owed)
        .sum::<usize>()
        + s.pools[pool].owed;
    (gates as i32, tokens as i32)
}

/// [actor-on-idle] Fires every registered quiescence hook, if the scheduler
/// has settled. Answers whether anything fired — which is *progress*, so a
/// caller about to declare a deadlock has to look again first.
///
/// Registrations are one-shots and all of them fire together: quiescence is a
/// property of the whole scheduler, so there is no order in which one hook
/// could see it and another not.
fn fire_idle(s: &mut Sched, cv: &Condvar) -> bool {
    if s.idle_hooks.is_empty() || !idle(s) {
        return false;
    }
    for (pool, notify, build) in std::mem::take(&mut s.idle_hooks) {
        let (gates, tokens) = parked(s, pool);
        deliver_reply(s, notify, build(gates, tokens));
    }
    cv.notify_all();
    true
}

/// [waitfor-pump] The next job a thread working for `pool` may run:
/// `exclude` is the actor whose own activation is waiting, which a wait must
/// never serve — re-entering an actor mid-activation is precisely what
/// serialization exists to prevent. A pool worker excludes nothing.
fn pick(s: &Sched, pool: usize, exclude: Option<usize>) -> Option<(usize, usize)> {
    s.actors
        .iter()
        .enumerate()
        .filter(|(addr, p)| p.pool == pool && Some(*addr) != exclude)
        .find_map(|(addr, p)| deliverable(p).map(|at| (addr, at)))
}

/// The deadlock report [actor-watch] [waitfor-pump]: nothing can run while a
/// frame waits, so nothing can ever change — a named error instead of a silent
/// hang. `waiter` names the frame that is waiting, which since
/// [waitfor-effect] need not be `main`.
///
/// The two lists are the two ways a mailbox comes to be unservable, and a
/// diagnosis starts by reading them: an actor **parked in a wait** holds its
/// own `running` flag, so *nothing* of its mailbox is delivered by anybody
/// until its token arrives; a **gated** actor serves only the reply it is
/// waiting for.
fn report_deadlock(s: &Sched, waiter: Option<usize>) -> ! {
    let occupied: Vec<String> = s
        .waiters
        .iter()
        .filter_map(|w| match w.parked {
            Some(Some(addr)) => Some(format!("actor {addr}")),
            _ => None,
        })
        .collect();
    let gated: Vec<String> = s
        .actors
        .iter()
        .enumerate()
        .filter(|(_, p)| p.gate.is_some() && !p.dead)
        .map(|(i, _)| format!("actor {i}"))
        .collect();
    let who = match waiter {
        None => "main".to_string(),
        Some(addr) => format!("actor {addr}"),
    };
    let mut detail = String::new();
    if !occupied.is_empty() {
        detail.push_str(&format!(" (parked in a wait: {}", occupied.join(", ")));
    }
    if !gated.is_empty() {
        detail.push_str(if detail.is_empty() { " (" } else { "; " });
        detail.push_str(&format!("parked gates: {}", gated.join(", ")));
    }
    if !detail.is_empty() {
        detail.push(')');
    }
    eprintln!("salvo: deadlock: nothing can run while {who} waits{detail}");
    std::process::exit(1);
}

/// Creates a pool of `n` worker threads and answers its id.
pub fn salvo_pool(n: usize) -> usize {
    salvo_pool_with_sink(n, None)
}

/// [pool-fault-sink] The same, with an actor to report uncaught faults to:
/// the addr and the builder that turns the host's reason into the language's
/// `Fault` value (the runtime cannot construct one, exactly as with `Exit`
/// [actor-watch]).
pub fn salvo_pool_with_sink(n: usize, sink: Option<(usize, ExitOf)>) -> usize {
    let (lock, _cv) = state();
    let pool = {
        let mut s = lock.lock().unwrap();
        s.pools.push(PoolState {
            tasks: VecDeque::new(),
            sink,
            owed: 0,
        });
        s.pools.len() - 1
    };
    for _ in 0..n {
        std::thread::spawn(move || worker(pool));
    }
    pool
}

/// [task-mint] Mints a token whose fulfilment **schedules** `body` on `pool`.
/// No capacity is reserved and no queue can be full: a task has no mailbox,
/// which is why a task mint contributes no deadlock edge.
pub fn salvo_mint_task(pool: usize, body: TaskBody) -> SalvoReply {
    let (lock, _cv) = state();
    let mut s = lock.lock().unwrap();
    s.next_slot += 1;
    let slot = s.next_slot;
    s.pools[pool].owed += 1;
    SalvoReply {
        target: Target::Task(pool, body),
        slot,
        tracked: true,
    }
}

/// Spawns an actor on a pool. The queue bound is explicit and required.
pub fn salvo_spawn(pool: usize, bound: usize, body: Box<dyn SalvoActor>) -> usize {
    let (lock, _cv) = state();
    let mut s = lock.lock().unwrap();
    s.actors.push(ActorState {
        queue: VecDeque::new(),
        user_len: 0,
        bound,
        gate: None,
        running: false,
        dead: false,
        exit_reason: None,
        pool,
        watchers: Vec::new(),
        owed: 0,
        body: Some(body),
    });
    s.actors.len() - 1
}

/// Sends a user message. Blocks while the target's queue is full; a send
/// to a dead actor is a silent no-op.
///
/// [main-pool] One block is a *guaranteed* wedge rather than back-pressure:
/// the main pool has exactly one worker — `main`'s own thread, which serves
/// work only inside a `waitfor` — so a full main-pool mailbox blocked on
/// from that same thread can never drain. Reported by name instead of hung.
pub fn salvo_send(addr: usize, msg: SalvoMsg) {
    let (lock, cv) = state();
    let mut s = lock.lock().unwrap();
    while !s.actors[addr].dead && s.actors[addr].user_len >= s.actors[addr].bound {
        if salvo_current_pool() == SALVO_MAIN_POOL && s.actors[addr].pool == SALVO_MAIN_POOL {
            report_main_pool_wedge(addr);
        }
        s = cv.wait(s).unwrap();
    }
    if s.actors[addr].dead {
        return;
    }
    s.actors[addr].queue.push_back(Entry::User(msg));
    s.actors[addr].user_len += 1;
    cv.notify_all();
}

/// [main-pool] The full-main-pool-mailbox report: a named error, since the
/// only thread that could drain the queue is the one blocked on it.
fn report_main_pool_wedge(addr: usize) -> ! {
    eprintln!(
        "salvo: deadlock: the main pool's actor {addr} has a full mailbox and the \
         only thread that could drain it is the one sending: the main pool has one \
         worker, `main` itself, and it serves work only inside a `waitfor` — send \
         fewer messages before waiting, raise the handler's `mailbox` capacity, or \
         place the actor on a pool of its own"
    );
    std::process::exit(1);
}

/// Mints a reply token targeting an actor's parked continuation `slot`.
pub fn salvo_mint(addr: usize) -> (SalvoReply, u64) {
    let (lock, _cv) = state();
    let mut s = lock.lock().unwrap();
    s.next_slot += 1;
    let slot = s.next_slot;
    s.actors[addr].owed += 1;
    (
        SalvoReply {
            target: Target::Proc(addr),
            slot,
            tracked: true,
        },
        slot,
    )
}

/// Mints a *gated* reply token: until it is delivered, the actor serves
/// nothing else. At most one gate may be outstanding — a second is a
/// fault in the calling activation.
pub fn salvo_mint_gated(addr: usize) -> (SalvoReply, u64) {
    let (lock, _cv) = state();
    let mut s = lock.lock().unwrap();
    assert!(
        s.actors[addr].gate.is_none(),
        "a gated continuation is already outstanding"
    );
    s.next_slot += 1;
    let slot = s.next_slot;
    s.actors[addr].gate = Some(slot);
    s.actors[addr].owed += 1;
    (
        SalvoReply {
            target: Target::Proc(addr),
            slot,
            tracked: true,
        },
        slot,
    )
}

/// [actor-watch] Registers a death watch: `on_exit` is sent the `Exit`
/// `exit` builds when the actor dies. Watching an already-dead actor
/// answers immediately, with the reason its death recorded — so a watch that
/// loses the race to a fast fault is not a watch that never answers.
pub fn salvo_watch(addr: usize, on_exit: SalvoReply, exit: ExitOf) {
    let (lock, cv) = state();
    let mut s = lock.lock().unwrap();
    let on_exit = untrack(&mut s, on_exit);
    if s.actors[addr].dead {
        let reason = s.actors[addr]
            .exit_reason
            .clone()
            .unwrap_or_else(|| "fault".to_string());
        deliver_reply(&mut s, on_exit, exit(reason));
        cv.notify_all();
    } else {
        s.actors[addr].watchers.push((on_exit, exit));
    }
}

/// [actor-on-idle] Registers a quiescence hook: `notify` is sent the `Idle`
/// `idle` builds the moment nothing anywhere can run, reporting what `pool` is
/// still owed. One-shot, exactly as a watch is — delivering the answer is work,
/// which ends the idleness that produced it.
///
/// The registration itself wakes every worker: the scheduler may *already* be
/// settled, in which case the next thread to look fires the hook.
pub fn salvo_on_idle(pool: usize, notify: SalvoReply, idle: IdleOf) {
    let (lock, cv) = state();
    let mut s = lock.lock().unwrap();
    let notify = untrack(&mut s, notify);
    s.idle_hooks.push((pool, notify, idle));
    cv.notify_all();
}

/// [time-timer] Registers a deadline: `done` is sent the `Fired` `fired`
/// builds once at least `delay` nanoseconds have passed, carrying the
/// monotonic reading it fired at.
///
/// One thread serves every deadline, started on the first registration and
/// parked in `wait_timeout` until the earliest one comes due — so a thousand
/// outstanding timers cost one thread and no polling, which is the constraint
/// this design was chosen under (no thread-per-timer). A registration wakes
/// it, since the new deadline may be earlier than the one it is sleeping on.
///
/// A delay of zero or less fires at the next look rather than immediately:
/// the answer is always a *later* activation, never a call inside `after`.
pub fn salvo_after(delay: i64, done: SalvoReply, fired: FiredOf) {
    let (lock, cv) = state();
    let mut s = lock.lock().unwrap();
    // The token is the scheduler's obligation now, exactly as with a watch or
    // an idle hook [actor-on-idle]: it will be answered, so it is not work the
    // program has forgotten.
    let done = untrack(&mut s, done);
    let deadline = crate::hosttime::salvo_mono_nanos().saturating_add(delay.max(0));
    s.timers.push((deadline, done, fired));
    if !s.timer_thread {
        s.timer_thread = true;
        std::thread::spawn(serve_timers);
    }
    cv.notify_all();
}

/// [time-timer] The deadline thread: delivers every timer whose deadline has
/// passed, then sleeps until the earliest one left (or until something
/// changes). It never exits — the program ends when `main` returns
/// [actor-waitfor], and pending timers die with it.
fn serve_timers() {
    let (lock, cv) = state();
    let mut s = lock.lock().unwrap();
    loop {
        let now = crate::hosttime::salvo_mono_nanos();
        let due: Vec<usize> = s
            .timers
            .iter()
            .enumerate()
            .filter(|(_, (deadline, _, _))| *deadline <= now)
            .map(|(i, _)| i)
            .collect();
        if !due.is_empty() {
            // Back to front, so removing one does not shift the next.
            for i in due.into_iter().rev() {
                let (deadline, done, fired) = s.timers.remove(i);
                let value = fired(deadline);
                deliver_reply(&mut s, done, value);
            }
            cv.notify_all();
            continue;
        }
        let sleep = s
            .timers
            .iter()
            .map(|(deadline, _, _)| *deadline)
            .min()
            .map(|earliest| std::time::Duration::from_nanos((earliest - now).max(0) as u64));
        s = match sleep {
            Some(d) => cv.wait_timeout(s, d).unwrap().0,
            None => cv.wait(s).unwrap(),
        };
    }
}

/// A waiter: the `waitfor` bridge. Answers the token to hand out and the
/// waiter's id to block on.
pub fn salvo_waiter() -> (SalvoReply, usize) {
    let (lock, _cv) = state();
    let pool = salvo_current_pool();
    let mut s = lock.lock().unwrap();
    s.waiters.push(WaiterState {
        value: None,
        pool,
        parked: None,
    });
    let wid = s.waiters.len() - 1;
    s.next_slot += 1;
    let slot = s.next_slot;
    s.pools[pool].owed += 1;
    (
        SalvoReply {
            target: Target::Waiter(wid),
            slot,
            tracked: true,
        },
        wid,
    )
}

/// [waitfor-pump] Blocks the calling thread until the waiter's token is
/// sent, and answers the value — *serving this thread's pool while it waits*
/// (everything on it except the waiting actor's own activations, which stay
/// stalled). For `main`, whose pool has no other worker, that is what runs
/// main-pool work at all; where the queue is empty the wait is a plain
/// block. If nothing can run while this frame waits, reports the deadlock
/// instead of hanging — including when the waiting frame is an **occupied
/// actor**, whose own mailbox its wait has stalled.
pub fn salvo_wait(wid: usize) -> SalvoMsg {
    let (lock, cv) = state();
    let here = HERE.with(|h| h.get());
    let (pool, own) = (here.pool, here.actor);
    let mut s = lock.lock().unwrap();
    // This frame is parked for the whole call, including across the jobs the
    // pump runs below: each of those books itself in `active` on its own, so
    // `active - parked` stays the count of frames that can still proceed.
    enter_wait(&mut s, &here, wid);
    loop {
        if let Some(v) = s.waiters[wid].value.take() {
            leave_wait(&mut s, &here, wid);
            return v;
        }
        // [waitfor-pump] Detached tasks are what the rule names first, and
        // they are served whoever is waiting; activations are served except
        // the waiter's own.
        if !s.pools[pool].tasks.is_empty() {
            s = run_task(lock, cv, s, pool);
            continue;
        }
        if let Some((addr, at)) = pick(&s, pool, own) {
            s = run_job(lock, cv, s, addr, at);
            continue;
        }
        // [actor-on-idle] Nothing to run is exactly the event the hooks are
        // registered for, and firing one *is* progress — so it comes before
        // the deadlock report, which is what firing nothing leaves.
        if fire_idle(&mut s, cv) {
            continue;
        }
        if stuck(&s) {
            report_deadlock(&s, own);
        }
        s = cv.wait(s).unwrap();
    }
}

/// [waitfor-pump] Books the calling frame as parked on `wid`: an activation or
/// a task counts out of the frames that can still proceed, and `main`'s own
/// thread — which the scheduler never counts as a frame — records that it is
/// inside a wait at all, since `main` running program code is progress nothing
/// else can see.
fn enter_wait(s: &mut Sched, here: &Here, wid: usize) {
    s.waiters[wid].parked = Some(here.actor);
    if here.frame {
        s.parked_frames += 1;
    } else if here.pool == SALVO_MAIN_POOL {
        s.main_waits += 1;
    }
}

/// The exact reverse, on every way out of a wait. Saturating, so an
/// unbalanced pair cannot wrap the count into a permanent "everything is
/// stuck".
fn leave_wait(s: &mut Sched, here: &Here, wid: usize) {
    s.waiters[wid].parked = None;
    if here.frame {
        s.parked_frames = s.parked_frames.saturating_sub(1);
    } else if here.pool == SALVO_MAIN_POOL {
        s.main_waits = s.main_waits.saturating_sub(1);
    }
}

/// Delivers a reply under the lock: to a waiter, or to an actor's queue
/// with reserved capacity (never blocks, never counts against the bound).
/// A reply to a dead actor is a silent no-op.
fn deliver_reply(s: &mut Sched, reply: SalvoReply, value: SalvoMsg) {
    // [actor-on-idle] The obligation is met here, whatever the target does
    // with the value — including a no-op delivery to the dead.
    if reply.tracked {
        release(s, &reply.target);
    }
    match reply.target {
        Target::Waiter(wid) => {
            s.waiters[wid].value = Some(value);
        }
        Target::Proc(addr) => {
            if s.actors[addr].dead {
                return;
            }
            s.actors[addr].queue.push_back(Entry::Reply(reply.slot, value));
        }
        // [task-mint] The answer schedules the task. Nothing to check: a task
        // has no mailbox to fill and no death to be a no-op for.
        Target::Task(pool, body) => {
            s.pools[pool].tasks.push_back((body, value));
        }
    }
}

impl SalvoReply {
    /// Sends the reply, consuming the token. Enqueue only — user code
    /// never runs inside a `send`.
    pub fn send(self, value: SalvoMsg) {
        let (lock, cv) = state();
        let mut s = lock.lock().unwrap();
        deliver_reply(&mut s, self, value);
        cv.notify_all();
    }
}

/// Runs one activation to completion: takes the entry out of the queue,
/// releases the lock for the body, catches a fault at this boundary and
/// turns it into the actor's death, then answers the reacquired guard. Both
/// callers — a pool worker and a `waitfor` pumping its own pool
/// [waitfor-pump] — go through here, so an activation means the same thing
/// whichever thread runs it.
fn run_job<'g>(
    lock: &'g Mutex<Sched>,
    cv: &Condvar,
    mut s: MutexGuard<'g, Sched>,
    addr: usize,
    at: usize,
) -> MutexGuard<'g, Sched> {
    let entry = s.actors[addr].queue.remove(at).unwrap();
    if matches!(entry, Entry::User(_)) {
        s.actors[addr].user_len -= 1;
    }
    if let Entry::Reply(slot, _) = entry {
        if s.actors[addr].gate == Some(slot) {
            s.actors[addr].gate = None;
        }
    }
    let mut body = s.actors[addr].body.take().unwrap();
    let pool = s.actors[addr].pool;
    s.actors[addr].running = true;
    s.active += 1;
    cv.notify_all(); // a user entry left the queue: unblock senders
    drop(s);

    // The activation runs *here*: an ambient mint inside it inherits this
    // pool, and a nested wait must not serve this actor [waitfor-pump].
    let saved = HERE.with(|h| {
        h.replace(Here {
            pool,
            actor: Some(addr),
            frame: true,
        })
    });
    let ctx = SalvoCtx { addr };
    let outcome = catch_unwind(AssertUnwindSafe(|| {
        match entry {
            Entry::User(msg) => body.handle(&ctx, msg),
            Entry::Reply(slot, value) => body.resume(&ctx, slot, value),
        }
        body
    }));
    HERE.with(|h| h.set(saved));

    s = lock.lock().unwrap();
    s.actors[addr].running = false;
    s.active -= 1;
    match outcome {
        Ok(body) => {
            s.actors[addr].body = Some(body);
        }
        Err(panic) => {
            let reason = panic
                .downcast_ref::<&str>()
                .map(|m| (*m).to_string())
                .or_else(|| panic.downcast_ref::<String>().cloned())
                .unwrap_or_else(|| "fault".to_string());
            s.actors[addr].dead = true;
            s.actors[addr].exit_reason = Some(reason.clone());
            s.actors[addr].queue.clear();
            s.actors[addr].user_len = 0;
            s.actors[addr].gate = None;
            let watchers = std::mem::take(&mut s.actors[addr].watchers);
            let unwatched = watchers.is_empty();
            for (w, exit) in watchers {
                let value = exit(reason.clone());
                deliver_reply(&mut s, w, value);
            }
            // [pool-fault-sink] The net under supervision: a death nobody was
            // watching still reaches the pool's sink, or the named report.
            if unwatched {
                report_fault(&mut s, pool, reason);
            }
        }
    }
    cv.notify_all();
    s
}

/// One pool worker: pick a deliverable entry for an actor on this pool,
/// run the activation to completion, repeat.
fn worker(pool: usize) {
    HERE.with(|h| {
        h.set(Here {
            pool,
            actor: None,
            frame: false,
        })
    });
    let (lock, cv) = state();
    let mut s = lock.lock().unwrap();
    loop {
        // [task-mint] A queued task before an activation: one rule, the same
        // on both backends, so a program's interleaving does not depend on
        // its target. Each queue is still served in arrival order.
        if !s.pools[pool].tasks.is_empty() {
            s = run_task(lock, cv, s, pool);
            continue;
        }
        match pick(&s, pool, None) {
            Some((addr, at)) => s = run_job(lock, cv, s, addr, at),
            None => {
                // [actor-on-idle] A worker with nothing to do is the other
                // place quiescence is observed: a hook registered from an
                // actor is fired by whichever thread next runs dry, without
                // anybody having to wait for it.
                if !fire_idle(&mut s, cv) {
                    s = cv.wait(s).unwrap();
                }
            }
        }
    }
}

/// [task-mint] Runs one detached task to completion, with the same lock
/// discipline and fault boundary as an activation: the lock is released for
/// the body, and a fault is caught here. A task has no identity, so there is
/// nothing to mark dead and nobody to notify — the fault goes to the pool's
/// sink [pool-fault-sink], or to the named report when it has none.
fn run_task<'g>(
    lock: &'g Mutex<Sched>,
    cv: &Condvar,
    mut s: MutexGuard<'g, Sched>,
    pool: usize,
) -> MutexGuard<'g, Sched> {
    let Some((body, value)) = s.pools[pool].tasks.pop_front() else {
        return s;
    };
    s.active += 1;
    drop(s);

    // A task belongs to no actor, so a nested wait inside it may serve every
    // activation on the pool [waitfor-pump].
    let saved = HERE.with(|h| {
        h.replace(Here {
            pool,
            actor: None,
            frame: true,
        })
    });
    let outcome = catch_unwind(AssertUnwindSafe(move || body(value)));
    HERE.with(|h| h.set(saved));

    s = lock.lock().unwrap();
    s.active -= 1;
    if let Err(panic) = outcome {
        let reason = panic
            .downcast_ref::<&str>()
            .map(|m| (*m).to_string())
            .or_else(|| panic.downcast_ref::<String>().cloned())
            .unwrap_or_else(|| "fault".to_string());
        report_fault(&mut s, pool, reason);
    }
    cv.notify_all();
    s
}

/// [pool-fault-sink] Where an uncaught fault on a pool goes: a message to the
/// pool's sink actor if it has one, else a named report on stderr. A fault
/// that cannot be delivered (a dead sink) falls back to the report, since the
/// alternative is losing it silently.
fn report_fault(s: &mut Sched, pool: usize, reason: String) {
    if let Some((addr, build)) = s.pools[pool].sink {
        if !s.actors[addr].dead {
            let msg = build(reason);
            // Enqueued past the bound deliberately: a fault report must not
            // block the faulting thread, and dropping it would lose the one
            // thing the sink exists for.
            s.actors[addr].queue.push_back(Entry::User(msg));
            s.actors[addr].user_len += 1;
            return;
        }
    }
    eprintln!("salvo: an uncaught fault on pool {pool}: {reason}");
}
