// Generated by the Salvo compiler: enums for union types.

impl<T1: crate::wire::__Wire, T2: crate::wire::__Wire, T3: crate::wire::__Wire, T4: crate::wire::__Wire, T5: crate::wire::__Wire, T6: crate::wire::__Wire, T7: crate::wire::__Wire> crate::wire::__Wire for Union7<T1, T2, T3, T4, T5, T6, T7> {
    fn __enc(&self, out: &mut Vec<u8>) {
        match self {
            Union7::U1(v) => {
                out.push(0);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U2(v) => {
                out.push(1);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U3(v) => {
                out.push(2);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U4(v) => {
                out.push(3);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U5(v) => {
                out.push(4);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U6(v) => {
                out.push(5);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U7(v) => {
                out.push(6);
                crate::wire::__Wire::__enc(v, out);
            }
        }
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        match r.u8()? {
            0 => Some(Union7::U1(crate::wire::__Wire::__dec(r)?)),
            1 => Some(Union7::U2(crate::wire::__Wire::__dec(r)?)),
            2 => Some(Union7::U3(crate::wire::__Wire::__dec(r)?)),
            3 => Some(Union7::U4(crate::wire::__Wire::__dec(r)?)),
            4 => Some(Union7::U5(crate::wire::__Wire::__dec(r)?)),
            5 => Some(Union7::U6(crate::wire::__Wire::__dec(r)?)),
            6 => Some(Union7::U7(crate::wire::__Wire::__dec(r)?)),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Union7<T1, T2, T3, T4, T5, T6, T7> {
    U1(T1),
    U2(T2),
    U3(T3),
    U4(T4),
    U5(T5),
    U6(T6),
    U7(T7),
}

impl<T1, T2, T3, T4, T5, T6, T7> Union7<T1, T2, T3, T4, T5, T6, T7> {
    pub fn u1(&self) -> &T1 {
        match self {
            Union7::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u1_mut(&mut self) -> &mut T1 {
        match self {
            Union7::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2(&self) -> &T2 {
        match self {
            Union7::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2_mut(&mut self) -> &mut T2 {
        match self {
            Union7::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3(&self) -> &T3 {
        match self {
            Union7::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3_mut(&mut self) -> &mut T3 {
        match self {
            Union7::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4(&self) -> &T4 {
        match self {
            Union7::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4_mut(&mut self) -> &mut T4 {
        match self {
            Union7::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5(&self) -> &T5 {
        match self {
            Union7::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5_mut(&mut self) -> &mut T5 {
        match self {
            Union7::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6(&self) -> &T6 {
        match self {
            Union7::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6_mut(&mut self) -> &mut T6 {
        match self {
            Union7::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7(&self) -> &T7 {
        match self {
            Union7::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7_mut(&mut self) -> &mut T7 {
        match self {
            Union7::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn to_str(&self, f1: &mut dyn FnMut(&T1) -> String, f2: &mut dyn FnMut(&T2) -> String, f3: &mut dyn FnMut(&T3) -> String, f4: &mut dyn FnMut(&T4) -> String, f5: &mut dyn FnMut(&T5) -> String, f6: &mut dyn FnMut(&T6) -> String, f7: &mut dyn FnMut(&T7) -> String) -> String {
        match self {
            Union7::U1(v) => f1(v),
            Union7::U2(v) => f2(v),
            Union7::U3(v) => f3(v),
            Union7::U4(v) => f4(v),
            Union7::U5(v) => f5(v),
            Union7::U6(v) => f6(v),
            Union7::U7(v) => f7(v),
        }
    }
}

impl<T1, T2, T3, T4, T5, T6, T7> std::fmt::Display for Union7<T1, T2, T3, T4, T5, T6, T7>
where
    T1: std::fmt::Display,
    T2: std::fmt::Display,
    T3: std::fmt::Display,
    T4: std::fmt::Display,
    T5: std::fmt::Display,
    T6: std::fmt::Display,
    T7: std::fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Union7::U1(v) => write!(f, "{}", v),
            Union7::U2(v) => write!(f, "{}", v),
            Union7::U3(v) => write!(f, "{}", v),
            Union7::U4(v) => write!(f, "{}", v),
            Union7::U5(v) => write!(f, "{}", v),
            Union7::U6(v) => write!(f, "{}", v),
            Union7::U7(v) => write!(f, "{}", v),
        }
    }
}
