// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 2c8ead26067fa07e
package salvo.runtime.routing

import salvo.runtime.*

// [mod-use] The module's `use` #0, bound on first use.
private val __moduleUse0: RouteTable by lazy {
    val route_table: RouteTable = __Mon_RouteTable(Routes().also { it.init() })
    route_table
}

fun decodeMessagePlatform(addr: Int, proto: String, payload: salvo.SalvoBytes): salvo.platform.runtime.Dyn? {
    return salvo.platform.runtime.routing.decodeMessage(addr, proto, payload)
}

fun decodeWaiterAnswerPlatform(wid: Int, payload: salvo.SalvoBytes): salvo.platform.runtime.Dyn? {
    return salvo.platform.runtime.routing.decodeWaiterAnswer(wid, payload)
}

fun decodeTaskAnswerPlatform(key: Long, payload: salvo.SalvoBytes): salvo.platform.runtime.Dyn? {
    return salvo.platform.runtime.routing.decodeTaskAnswer(key, payload)
}

fun rawAnswerPlatform(payload: salvo.SalvoBytes): salvo.platform.runtime.Dyn {
    return salvo.platform.runtime.routing.rawAnswer(payload)
}

fun controlMessagePlatform(sink: Int, from: Long, payload: salvo.SalvoBytes): salvo.platform.runtime.Dyn? {
    return salvo.platform.runtime.routing.controlMessage(sink, from, payload)
}

fun wireOutPlatform(from: Long, to: salvo.SalvoBytes, frame: salvo.SalvoBytes) {
    return salvo.platform.runtime.routing.wireOut(from, to, frame)
}
