// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 5ecf120cea852ac5
package salvo.runtime.streams

import salvo.core.bytes.*
import salvo.core.deque.*
import salvo.core.list.*
import salvo.core.seq.*
import salvo.core.string.*
import salvo.runtime.*

// [mod-use] The module's `use` #0, bound on first use.
private val __moduleUse0: StreamTable by lazy {
    val stream_table: StreamTable = __Mon_StreamTable(Streams())
    stream_table
}

data class HostRead(
    val data: salvo.platform.core.bytes.Bytes,
    val error: String?,
)

object __Codec_HostRead : salvo.WireCodec<HostRead> {
    override fun enc(v: HostRead, out: salvo.WireOut) {
        salvo.BytesCodec.enc(v.data, out)
        salvo.OptCodec(salvo.StrCodec).enc(v.error, out)
    }
    override fun dec(inp: salvo.WireIn): HostRead = HostRead(salvo.BytesCodec.dec(inp), salvo.OptCodec(salvo.StrCodec).dec(inp))
}

fun hostReadPlatform(h: salvo.platform.runtime.streams.HostIn, max: Int): HostRead {
    return salvo.platform.runtime.streams.hostRead(h, max)
}

fun hostCloseInPlatform(h: salvo.platform.runtime.streams.HostIn) {
    return salvo.platform.runtime.streams.hostCloseIn(h)
}

fun hostWritePlatform(h: salvo.platform.runtime.streams.HostOut, data: salvo.platform.core.bytes.Bytes): String? {
    return salvo.platform.runtime.streams.hostWrite(h, data)
}

fun hostFlushPlatform(h: salvo.platform.runtime.streams.HostOut): String? {
    return salvo.platform.runtime.streams.hostFlush(h)
}

fun hostCloseOutPlatform(h: salvo.platform.runtime.streams.HostOut): String? {
    return salvo.platform.runtime.streams.hostCloseOut(h)
}

fun hostBytesInPlatform(data: salvo.platform.core.bytes.Bytes): salvo.platform.runtime.streams.HostIn {
    return salvo.platform.runtime.streams.hostBytesIn(data)
}

fun notOursPlatform(handle: Long): Nothing {
    return salvo.platform.runtime.streams.notOurs(handle)
}
