// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 5cd1832c3b5d03f1
// Generated by the Salvo compiler: sealed wrappers for union types.
package salvo

sealed interface Union7<out T1, out T2, out T3, out T4, out T5, out T6, out T7> {
    val value: Any?
    data class U1<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T1) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U2<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T2) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U3<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T3) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U4<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T4) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U5<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T5) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U6<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T6) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U7<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T7) : Union7<T1, T2, T3, T4, T5, T6, T7>
    fun toStr(f1: (T1) -> String, f2: (T2) -> String, f3: (T3) -> String, f4: (T4) -> String, f5: (T5) -> String, f6: (T6) -> String, f7: (T7) -> String): String = when (this) {
        is U1 -> f1(this.value)
        is U2 -> f2(this.value)
        is U3 -> f3(this.value)
        is U4 -> f4(this.value)
        is U5 -> f5(this.value)
        is U6 -> f6(this.value)
        is U7 -> f7(this.value)
    }
}
