// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 0ffbeeb8845040b9
// Generated by the Salvo compiler: the codec of `Union7` [kt-wire].
package salvo

class Union7Codec<T1, T2, T3, T4, T5, T6, T7>(private val c1: WireCodec<T1>, private val c2: WireCodec<T2>, private val c3: WireCodec<T3>, private val c4: WireCodec<T4>, private val c5: WireCodec<T5>, private val c6: WireCodec<T6>, private val c7: WireCodec<T7>) : WireCodec<Union7<T1, T2, T3, T4, T5, T6, T7>> {
    override fun enc(v: Union7<T1, T2, T3, T4, T5, T6, T7>, out: WireOut) {
        when (v) {
            is Union7.U1 -> { out.u8(0); c1.enc(v.value, out) }
            is Union7.U2 -> { out.u8(1); c2.enc(v.value, out) }
            is Union7.U3 -> { out.u8(2); c3.enc(v.value, out) }
            is Union7.U4 -> { out.u8(3); c4.enc(v.value, out) }
            is Union7.U5 -> { out.u8(4); c5.enc(v.value, out) }
            is Union7.U6 -> { out.u8(5); c6.enc(v.value, out) }
            is Union7.U7 -> { out.u8(6); c7.enc(v.value, out) }
        }
    }
    override fun dec(inp: WireIn): Union7<T1, T2, T3, T4, T5, T6, T7> = when (inp.u8()) {
            0 -> Union7.U1(c1.dec(inp))
            1 -> Union7.U2(c2.dec(inp))
            2 -> Union7.U3(c3.dec(inp))
            3 -> Union7.U4(c4.dec(inp))
            4 -> Union7.U5(c5.dec(inp))
            5 -> Union7.U6(c6.dec(inp))
            6 -> Union7.U7(c7.dec(inp))
            else -> throw WireError()
        }
}
