// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 6106fb760fae54e6
// Generated by the Salvo compiler: sealed wrappers for union types.
package salvo

sealed interface Union3<out T1, out T2, out T3> {
    val value: Any?
    data class U1<out T1, out T2, out T3>(override val value: T1) : Union3<T1, T2, T3>
    data class U2<out T1, out T2, out T3>(override val value: T2) : Union3<T1, T2, T3>
    data class U3<out T1, out T2, out T3>(override val value: T3) : Union3<T1, T2, T3>
}
