// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 023a4214a13ba612
use crate::aws::AwsConfig;


pub type __Platform_HostS3 = crate::aws_s3::__Platform_S3<crate::platform_aws_s3_host::HostS3>;

impl __Platform_HostS3 {
    pub fn new(config: crate::aws::AwsConfig) -> Self {
        crate::aws_s3::__Platform_S3(crate::platform_aws_s3_host::HostS3::new(config))
    }
}
