// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
package salvo.aws.s3.host

import salvo.aws.*
import salvo.aws.s3.*

class __Platform_HostS3(config: AwsConfig) : salvo.aws.s3.__Platform_S3(salvo.platform.aws.s3.host.HostS3(config))
