// Host implementation of `aws.s3.host`'s `HostS3`,
// over aws-sdk-kotlin (`aws.sdk.kotlin.services.s3`) [platform-reply].
//
// Generated by `salvo-client-codegen` from `models/s3-2006-03-01.json`; do not
// edit — regenerate with `./gradlew generate` in `modules/aws/codegen`.
@file:OptIn(aws.smithy.kotlin.runtime.InternalApi::class, aws.sdk.kotlin.runtime.InternalSdkApi::class)
@file:Suppress("DEPRECATION", "UNUSED_PARAMETER", "UNCHECKED_CAST", "USELESS_ELVIS", "UNNECESSARY_SAFE_CALL")

package salvo.platform.aws.s3.host

import salvo.*
import salvo.aws.*
import salvo.aws.s3.*
import salvo.aws.s3.host.*
import kotlinx.coroutines.launch
import aws.smithy.kotlin.runtime.content.asByteStream
import aws.smithy.kotlin.runtime.content.toInputStream

// `threadsafe platform handler HostS3`: the SDK client is safe to share, and
// each call is a coroutine on the handler's own scope, completing its reply there.
class HostS3(private val config: AwsConfig) : S3 {
    private val scope = kotlinx.coroutines.CoroutineScope(
        kotlinx.coroutines.SupervisorJob() + kotlinx.coroutines.Dispatchers.IO
    )
    private val client = aws.sdk.kotlin.services.s3.S3Client {
        region = this@HostS3.config.region.code
        credentialsProvider = salvoCredentials(this@HostS3.config.credentials)
        this@HostS3.config.endpoint?.let { endpointUrl = aws.smithy.kotlin.runtime.net.url.Url.parse(it) }
        forcePathStyle = this@HostS3.config.endpoint != null
    }

    init {
        salvoCloseWhenMainEnds(client)
    }

    override fun put_object(input: PutObjectInput, reply: salvo.SalvoReply) {
        val host = reply.hosted()
        val body = SalvoStreams.takeIn(input.body.handle)
        val length = input.content_length
        scope.launch {
            if (length == null || length < 0) {
                body.closeInput()
                val failed: Union2<PutObjectOutput, salvo.core.checked.Checked<Union7<EncryptionTypeMismatch, InvalidObjectState, InvalidRequest, InvalidWriteOffset, NoSuchKey, TooManyParts, AwsError>>> = U2_2(salvo.core.checked.Checked(U7_7(AwsError(code = "MissingContentLength", message = "S3 PutObject streams its body, so the input needs content_length: the body's length in bytes"))))
                host.send(failed)
                return@launch
            }
            val upload = SalvoUpload(body, length)
            val answer: Union2<PutObjectOutput, salvo.core.checked.Checked<Union7<EncryptionTypeMismatch, InvalidObjectState, InvalidRequest, InvalidWriteOffset, NoSuchKey, TooManyParts, AwsError>>> = try {
                U2_1(fromSdkPutObjectOutput(client.putObject(toSdkPutObjectInput(input, upload.asByteStream(length)))))
            } catch (e: aws.sdk.kotlin.services.s3.model.EncryptionTypeMismatch) {
                U2_2(salvo.core.checked.Checked(U7_1(fromSdkEncryptionTypeMismatch(e))))
            } catch (e: aws.sdk.kotlin.services.s3.model.InvalidRequest) {
                U2_2(salvo.core.checked.Checked(U7_3(fromSdkInvalidRequest(e))))
            } catch (e: aws.sdk.kotlin.services.s3.model.InvalidWriteOffset) {
                U2_2(salvo.core.checked.Checked(U7_4(fromSdkInvalidWriteOffset(e))))
            } catch (e: aws.sdk.kotlin.services.s3.model.TooManyParts) {
                U2_2(salvo.core.checked.Checked(U7_6(fromSdkTooManyParts(e))))
            } catch (e: Exception) {
                U2_2(salvo.core.checked.Checked(U7_7(salvoAwsError(e))))
            }
            val problem = upload.finish()
            body.closeInput()
            val result: Union2<PutObjectOutput, salvo.core.checked.Checked<Union7<EncryptionTypeMismatch, InvalidObjectState, InvalidRequest, InvalidWriteOffset, NoSuchKey, TooManyParts, AwsError>>> = problem?.let {
                U2_2(salvo.core.checked.Checked(U7_7(AwsError(code = "StreamFailed", message = it))))
            } ?: answer
            host.send(result)
        }
    }

    override fun get_object(input: GetObjectInput, reply: salvo.SalvoReply) {
        val host = reply.hosted()
        scope.launch {
            var sent = false
            val answer: Union2<GetObjectOutput, salvo.core.checked.Checked<Union7<EncryptionTypeMismatch, InvalidObjectState, InvalidRequest, InvalidWriteOffset, NoSuchKey, TooManyParts, AwsError>>>? = try {
                client.getObject(toSdkGetObjectInput(input)) { response ->
                    val closed = kotlinx.coroutines.CompletableDeferred<Unit>()
                    val handle = salvoRegisterBody("S3 GetObject body", response.body, closed)
                    sent = true
                    val ok: Union2<GetObjectOutput, salvo.core.checked.Checked<Union7<EncryptionTypeMismatch, InvalidObjectState, InvalidRequest, InvalidWriteOffset, NoSuchKey, TooManyParts, AwsError>>> = U2_1(fromSdkGetObjectOutput(response, handle))
                    host.send(ok)
                    closed.await()
                }
                null
            } catch (e: aws.sdk.kotlin.services.s3.model.InvalidObjectState) {
                U2_2(salvo.core.checked.Checked(U7_2(fromSdkInvalidObjectState(e))))
            } catch (e: aws.sdk.kotlin.services.s3.model.NoSuchKey) {
                U2_2(salvo.core.checked.Checked(U7_5(fromSdkNoSuchKey(e))))
            } catch (e: Exception) {
                U2_2(salvo.core.checked.Checked(U7_7(salvoAwsError(e))))
            }
            if (!sent && answer != null) host.send(answer)
        }
    }
}

/** The SDK credentials provider an `AwsConfig`'s credentials name. */
private fun salvoCredentials(
    c: Union3<ProfileCredentials, EnvironmentCredentials, DefaultChain>,
): aws.smithy.kotlin.runtime.auth.awscredentials.CredentialsProvider = when (c) {
    is U3_1<*, *, *> -> {
        val p = c.value as ProfileCredentials
        aws.sdk.kotlin.runtime.auth.credentials.ProfileCredentialsProvider(
            profileName = p.profile,
            configurationSource = aws.sdk.kotlin.runtime.config.profile.AwsConfigurationSource(
                p.profile,
                salvoExpandHome("~/.aws/config"),
                salvoExpandHome(p.path),
            ),
        )
    }
    is U3_2<*, *, *> -> aws.sdk.kotlin.runtime.auth.credentials.EnvironmentCredentialsProvider()
    is U3_3<*, *, *> -> aws.sdk.kotlin.runtime.auth.credentials.DefaultChainCredentialsProvider()
}

/**
 * Closes [client] once the program's `main` thread has ended. The SDK's
 * HTTP engine (OkHttp) keeps a non-daemon dispatcher thread alive for 60s
 * after its last call, which would hold the JVM open that long after the
 * program is done; a Rust program exits when `main` returns, and this
 * makes the JVM do the same. Closing the client shuts the engine's
 * executor down. A stopgap inside the glue: the runtime ending the
 * process when `main` returns is on the roadmap, to be designed.
 */
private fun salvoCloseWhenMainEnds(client: AutoCloseable) {
    val main = Thread.getAllStackTraces().keys.firstOrNull { it.name == "main" && it.threadGroup?.name == "main" }
        ?: return
    val closer = Thread {
        main.join()
        runCatching { client.close() }
    }
    closer.isDaemon = true
    closer.name = "salvo-aws-close"
    closer.start()
}

/** `~/` at the front of a path is the home directory, as a shell would read it. */
private fun salvoExpandHome(path: String): String =
    if (path.startsWith("~/")) (System.getenv("HOME") ?: System.getProperty("user.home")) + path.substring(1) else path

private fun toSdkObjectCannedACL(v: Union8<ObjectCannedACL.Private, ObjectCannedACL.PublicRead, ObjectCannedACL.PublicReadWrite, ObjectCannedACL.AuthenticatedRead, ObjectCannedACL.AwsExecRead, ObjectCannedACL.BucketOwnerRead, ObjectCannedACL.BucketOwnerFullControl, ObjectCannedACL.Unknown>): aws.sdk.kotlin.services.s3.model.ObjectCannedAcl = when (v) {
    is U8_1<*, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectCannedAcl.fromValue("private")
    is U8_2<*, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectCannedAcl.fromValue("public-read")
    is U8_3<*, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectCannedAcl.fromValue("public-read-write")
    is U8_4<*, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectCannedAcl.fromValue("authenticated-read")
    is U8_5<*, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectCannedAcl.fromValue("aws-exec-read")
    is U8_6<*, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectCannedAcl.fromValue("bucket-owner-read")
    is U8_7<*, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectCannedAcl.fromValue("bucket-owner-full-control")
    is U8_8<*, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectCannedAcl.fromValue((v.value as ObjectCannedACL.Unknown).value)
}

private fun fromSdkObjectCannedACL(v: aws.sdk.kotlin.services.s3.model.ObjectCannedAcl): Union8<ObjectCannedACL.Private, ObjectCannedACL.PublicRead, ObjectCannedACL.PublicReadWrite, ObjectCannedACL.AuthenticatedRead, ObjectCannedACL.AwsExecRead, ObjectCannedACL.BucketOwnerRead, ObjectCannedACL.BucketOwnerFullControl, ObjectCannedACL.Unknown> = when (v.value) {
    "private" -> U8_1(ObjectCannedACL.Private())
    "public-read" -> U8_2(ObjectCannedACL.PublicRead())
    "public-read-write" -> U8_3(ObjectCannedACL.PublicReadWrite())
    "authenticated-read" -> U8_4(ObjectCannedACL.AuthenticatedRead())
    "aws-exec-read" -> U8_5(ObjectCannedACL.AwsExecRead())
    "bucket-owner-read" -> U8_6(ObjectCannedACL.BucketOwnerRead())
    "bucket-owner-full-control" -> U8_7(ObjectCannedACL.BucketOwnerFullControl())
    else -> U8_8(ObjectCannedACL.Unknown(v.value))
}

private fun toSdkChecksumAlgorithm(v: Union11<ChecksumAlgorithm.Crc32, ChecksumAlgorithm.Crc32C, ChecksumAlgorithm.Sha1, ChecksumAlgorithm.Sha256, ChecksumAlgorithm.Crc64Nvme, ChecksumAlgorithm.Sha512, ChecksumAlgorithm.Md5, ChecksumAlgorithm.Xxhash64, ChecksumAlgorithm.Xxhash3, ChecksumAlgorithm.Xxhash128, ChecksumAlgorithm.Unknown>): aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm = when (v) {
    is U11_1<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm.fromValue("CRC32")
    is U11_2<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm.fromValue("CRC32C")
    is U11_3<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm.fromValue("SHA1")
    is U11_4<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm.fromValue("SHA256")
    is U11_5<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm.fromValue("CRC64NVME")
    is U11_6<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm.fromValue("SHA512")
    is U11_7<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm.fromValue("MD5")
    is U11_8<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm.fromValue("XXHASH64")
    is U11_9<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm.fromValue("XXHASH3")
    is U11_10<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm.fromValue("XXHASH128")
    is U11_11<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm.fromValue((v.value as ChecksumAlgorithm.Unknown).value)
}

private fun fromSdkChecksumAlgorithm(v: aws.sdk.kotlin.services.s3.model.ChecksumAlgorithm): Union11<ChecksumAlgorithm.Crc32, ChecksumAlgorithm.Crc32C, ChecksumAlgorithm.Sha1, ChecksumAlgorithm.Sha256, ChecksumAlgorithm.Crc64Nvme, ChecksumAlgorithm.Sha512, ChecksumAlgorithm.Md5, ChecksumAlgorithm.Xxhash64, ChecksumAlgorithm.Xxhash3, ChecksumAlgorithm.Xxhash128, ChecksumAlgorithm.Unknown> = when (v.value) {
    "CRC32" -> U11_1(ChecksumAlgorithm.Crc32())
    "CRC32C" -> U11_2(ChecksumAlgorithm.Crc32C())
    "SHA1" -> U11_3(ChecksumAlgorithm.Sha1())
    "SHA256" -> U11_4(ChecksumAlgorithm.Sha256())
    "CRC64NVME" -> U11_5(ChecksumAlgorithm.Crc64Nvme())
    "SHA512" -> U11_6(ChecksumAlgorithm.Sha512())
    "MD5" -> U11_7(ChecksumAlgorithm.Md5())
    "XXHASH64" -> U11_8(ChecksumAlgorithm.Xxhash64())
    "XXHASH3" -> U11_9(ChecksumAlgorithm.Xxhash3())
    "XXHASH128" -> U11_10(ChecksumAlgorithm.Xxhash128())
    else -> U11_11(ChecksumAlgorithm.Unknown(v.value))
}

private fun toSdkServerSideEncryption(v: Union6<ServerSideEncryption.Aes256, ServerSideEncryption.AwsFsx, ServerSideEncryption.AwsBackup, ServerSideEncryption.AwsKms, ServerSideEncryption.AwsKmsDsse, ServerSideEncryption.Unknown>): aws.sdk.kotlin.services.s3.model.ServerSideEncryption = when (v) {
    is U6_1<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ServerSideEncryption.fromValue("AES256")
    is U6_2<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ServerSideEncryption.fromValue("aws:fsx")
    is U6_3<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ServerSideEncryption.fromValue("aws:backup")
    is U6_4<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ServerSideEncryption.fromValue("aws:kms")
    is U6_5<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ServerSideEncryption.fromValue("aws:kms:dsse")
    is U6_6<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ServerSideEncryption.fromValue((v.value as ServerSideEncryption.Unknown).value)
}

private fun fromSdkServerSideEncryption(v: aws.sdk.kotlin.services.s3.model.ServerSideEncryption): Union6<ServerSideEncryption.Aes256, ServerSideEncryption.AwsFsx, ServerSideEncryption.AwsBackup, ServerSideEncryption.AwsKms, ServerSideEncryption.AwsKmsDsse, ServerSideEncryption.Unknown> = when (v.value) {
    "AES256" -> U6_1(ServerSideEncryption.Aes256())
    "aws:fsx" -> U6_2(ServerSideEncryption.AwsFsx())
    "aws:backup" -> U6_3(ServerSideEncryption.AwsBackup())
    "aws:kms" -> U6_4(ServerSideEncryption.AwsKms())
    "aws:kms:dsse" -> U6_5(ServerSideEncryption.AwsKmsDsse())
    else -> U6_6(ServerSideEncryption.Unknown(v.value))
}

private fun toSdkStorageClass(v: Union16<StorageClass.Standard, StorageClass.ReducedRedundancy, StorageClass.StandardIa, StorageClass.OnezoneIa, StorageClass.IntelligentTiering, StorageClass.Glacier, StorageClass.DeepArchive, StorageClass.Outposts, StorageClass.GlacierIr, StorageClass.Snow, StorageClass.ExpressOnezone, StorageClass.FsxOpenzfs, StorageClass.FsxOntap, StorageClass.AwsBackupWarm, StorageClass.AwsBackupLowCostWarm, StorageClass.Unknown>): aws.sdk.kotlin.services.s3.model.StorageClass = when (v) {
    is U16_1<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("STANDARD")
    is U16_2<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("REDUCED_REDUNDANCY")
    is U16_3<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("STANDARD_IA")
    is U16_4<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("ONEZONE_IA")
    is U16_5<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("INTELLIGENT_TIERING")
    is U16_6<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("GLACIER")
    is U16_7<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("DEEP_ARCHIVE")
    is U16_8<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("OUTPOSTS")
    is U16_9<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("GLACIER_IR")
    is U16_10<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("SNOW")
    is U16_11<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("EXPRESS_ONEZONE")
    is U16_12<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("FSX_OPENZFS")
    is U16_13<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("FSX_ONTAP")
    is U16_14<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("AWS_BACKUP_WARM")
    is U16_15<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue("AWS_BACKUP_LOW_COST_WARM")
    is U16_16<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.StorageClass.fromValue((v.value as StorageClass.Unknown).value)
}

private fun fromSdkStorageClass(v: aws.sdk.kotlin.services.s3.model.StorageClass): Union16<StorageClass.Standard, StorageClass.ReducedRedundancy, StorageClass.StandardIa, StorageClass.OnezoneIa, StorageClass.IntelligentTiering, StorageClass.Glacier, StorageClass.DeepArchive, StorageClass.Outposts, StorageClass.GlacierIr, StorageClass.Snow, StorageClass.ExpressOnezone, StorageClass.FsxOpenzfs, StorageClass.FsxOntap, StorageClass.AwsBackupWarm, StorageClass.AwsBackupLowCostWarm, StorageClass.Unknown> = when (v.value) {
    "STANDARD" -> U16_1(StorageClass.Standard())
    "REDUCED_REDUNDANCY" -> U16_2(StorageClass.ReducedRedundancy())
    "STANDARD_IA" -> U16_3(StorageClass.StandardIa())
    "ONEZONE_IA" -> U16_4(StorageClass.OnezoneIa())
    "INTELLIGENT_TIERING" -> U16_5(StorageClass.IntelligentTiering())
    "GLACIER" -> U16_6(StorageClass.Glacier())
    "DEEP_ARCHIVE" -> U16_7(StorageClass.DeepArchive())
    "OUTPOSTS" -> U16_8(StorageClass.Outposts())
    "GLACIER_IR" -> U16_9(StorageClass.GlacierIr())
    "SNOW" -> U16_10(StorageClass.Snow())
    "EXPRESS_ONEZONE" -> U16_11(StorageClass.ExpressOnezone())
    "FSX_OPENZFS" -> U16_12(StorageClass.FsxOpenzfs())
    "FSX_ONTAP" -> U16_13(StorageClass.FsxOntap())
    "AWS_BACKUP_WARM" -> U16_14(StorageClass.AwsBackupWarm())
    "AWS_BACKUP_LOW_COST_WARM" -> U16_15(StorageClass.AwsBackupLowCostWarm())
    else -> U16_16(StorageClass.Unknown(v.value))
}

private fun toSdkRequestPayer(v: Union2<RequestPayer.Requester, RequestPayer.Unknown>): aws.sdk.kotlin.services.s3.model.RequestPayer = when (v) {
    is U2_1<*, *> -> aws.sdk.kotlin.services.s3.model.RequestPayer.fromValue("requester")
    is U2_2<*, *> -> aws.sdk.kotlin.services.s3.model.RequestPayer.fromValue((v.value as RequestPayer.Unknown).value)
}

private fun fromSdkRequestPayer(v: aws.sdk.kotlin.services.s3.model.RequestPayer): Union2<RequestPayer.Requester, RequestPayer.Unknown> = when (v.value) {
    "requester" -> U2_1(RequestPayer.Requester())
    else -> U2_2(RequestPayer.Unknown(v.value))
}

private fun toSdkObjectLockMode(v: Union3<ObjectLockMode.Governance, ObjectLockMode.Compliance, ObjectLockMode.Unknown>): aws.sdk.kotlin.services.s3.model.ObjectLockMode = when (v) {
    is U3_1<*, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectLockMode.fromValue("GOVERNANCE")
    is U3_2<*, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectLockMode.fromValue("COMPLIANCE")
    is U3_3<*, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectLockMode.fromValue((v.value as ObjectLockMode.Unknown).value)
}

private fun fromSdkObjectLockMode(v: aws.sdk.kotlin.services.s3.model.ObjectLockMode): Union3<ObjectLockMode.Governance, ObjectLockMode.Compliance, ObjectLockMode.Unknown> = when (v.value) {
    "GOVERNANCE" -> U3_1(ObjectLockMode.Governance())
    "COMPLIANCE" -> U3_2(ObjectLockMode.Compliance())
    else -> U3_3(ObjectLockMode.Unknown(v.value))
}

private fun toSdkObjectLockLegalHoldStatus(v: Union3<ObjectLockLegalHoldStatus.On, ObjectLockLegalHoldStatus.Off, ObjectLockLegalHoldStatus.Unknown>): aws.sdk.kotlin.services.s3.model.ObjectLockLegalHoldStatus = when (v) {
    is U3_1<*, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectLockLegalHoldStatus.fromValue("ON")
    is U3_2<*, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectLockLegalHoldStatus.fromValue("OFF")
    is U3_3<*, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectLockLegalHoldStatus.fromValue((v.value as ObjectLockLegalHoldStatus.Unknown).value)
}

private fun fromSdkObjectLockLegalHoldStatus(v: aws.sdk.kotlin.services.s3.model.ObjectLockLegalHoldStatus): Union3<ObjectLockLegalHoldStatus.On, ObjectLockLegalHoldStatus.Off, ObjectLockLegalHoldStatus.Unknown> = when (v.value) {
    "ON" -> U3_1(ObjectLockLegalHoldStatus.On())
    "OFF" -> U3_2(ObjectLockLegalHoldStatus.Off())
    else -> U3_3(ObjectLockLegalHoldStatus.Unknown(v.value))
}

private fun toSdkObjectLockEventHold(v: Union3<ObjectLockEventHold.On, ObjectLockEventHold.Off, ObjectLockEventHold.Unknown>): aws.sdk.kotlin.services.s3.model.ObjectLockEventHold = when (v) {
    is U3_1<*, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectLockEventHold.fromValue("ON")
    is U3_2<*, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectLockEventHold.fromValue("OFF")
    is U3_3<*, *, *> -> aws.sdk.kotlin.services.s3.model.ObjectLockEventHold.fromValue((v.value as ObjectLockEventHold.Unknown).value)
}

private fun fromSdkObjectLockEventHold(v: aws.sdk.kotlin.services.s3.model.ObjectLockEventHold): Union3<ObjectLockEventHold.On, ObjectLockEventHold.Off, ObjectLockEventHold.Unknown> = when (v.value) {
    "ON" -> U3_1(ObjectLockEventHold.On())
    "OFF" -> U3_2(ObjectLockEventHold.Off())
    else -> U3_3(ObjectLockEventHold.Unknown(v.value))
}

private fun toSdkChecksumType(v: Union3<ChecksumType.Composite, ChecksumType.FullObject, ChecksumType.Unknown>): aws.sdk.kotlin.services.s3.model.ChecksumType = when (v) {
    is U3_1<*, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumType.fromValue("COMPOSITE")
    is U3_2<*, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumType.fromValue("FULL_OBJECT")
    is U3_3<*, *, *> -> aws.sdk.kotlin.services.s3.model.ChecksumType.fromValue((v.value as ChecksumType.Unknown).value)
}

private fun fromSdkChecksumType(v: aws.sdk.kotlin.services.s3.model.ChecksumType): Union3<ChecksumType.Composite, ChecksumType.FullObject, ChecksumType.Unknown> = when (v.value) {
    "COMPOSITE" -> U3_1(ChecksumType.Composite())
    "FULL_OBJECT" -> U3_2(ChecksumType.FullObject())
    else -> U3_3(ChecksumType.Unknown(v.value))
}

private fun toSdkRequestCharged(v: Union2<RequestCharged.Requester, RequestCharged.Unknown>): aws.sdk.kotlin.services.s3.model.RequestCharged = when (v) {
    is U2_1<*, *> -> aws.sdk.kotlin.services.s3.model.RequestCharged.fromValue("requester")
    is U2_2<*, *> -> aws.sdk.kotlin.services.s3.model.RequestCharged.fromValue((v.value as RequestCharged.Unknown).value)
}

private fun fromSdkRequestCharged(v: aws.sdk.kotlin.services.s3.model.RequestCharged): Union2<RequestCharged.Requester, RequestCharged.Unknown> = when (v.value) {
    "requester" -> U2_1(RequestCharged.Requester())
    else -> U2_2(RequestCharged.Unknown(v.value))
}

private fun toSdkChecksumMode(v: Union2<ChecksumMode.Enabled, ChecksumMode.Unknown>): aws.sdk.kotlin.services.s3.model.ChecksumMode = when (v) {
    is U2_1<*, *> -> aws.sdk.kotlin.services.s3.model.ChecksumMode.fromValue("ENABLED")
    is U2_2<*, *> -> aws.sdk.kotlin.services.s3.model.ChecksumMode.fromValue((v.value as ChecksumMode.Unknown).value)
}

private fun fromSdkChecksumMode(v: aws.sdk.kotlin.services.s3.model.ChecksumMode): Union2<ChecksumMode.Enabled, ChecksumMode.Unknown> = when (v.value) {
    "ENABLED" -> U2_1(ChecksumMode.Enabled())
    else -> U2_2(ChecksumMode.Unknown(v.value))
}

private fun toSdkReplicationStatus(v: Union6<ReplicationStatus.Complete, ReplicationStatus.Pending, ReplicationStatus.Failed, ReplicationStatus.Replica, ReplicationStatus.Completed, ReplicationStatus.Unknown>): aws.sdk.kotlin.services.s3.model.ReplicationStatus = when (v) {
    is U6_1<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ReplicationStatus.fromValue("COMPLETE")
    is U6_2<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ReplicationStatus.fromValue("PENDING")
    is U6_3<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ReplicationStatus.fromValue("FAILED")
    is U6_4<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ReplicationStatus.fromValue("REPLICA")
    is U6_5<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ReplicationStatus.fromValue("COMPLETED")
    is U6_6<*, *, *, *, *, *> -> aws.sdk.kotlin.services.s3.model.ReplicationStatus.fromValue((v.value as ReplicationStatus.Unknown).value)
}

private fun fromSdkReplicationStatus(v: aws.sdk.kotlin.services.s3.model.ReplicationStatus): Union6<ReplicationStatus.Complete, ReplicationStatus.Pending, ReplicationStatus.Failed, ReplicationStatus.Replica, ReplicationStatus.Completed, ReplicationStatus.Unknown> = when (v.value) {
    "COMPLETE" -> U6_1(ReplicationStatus.Complete())
    "PENDING" -> U6_2(ReplicationStatus.Pending())
    "FAILED" -> U6_3(ReplicationStatus.Failed())
    "REPLICA" -> U6_4(ReplicationStatus.Replica())
    "COMPLETED" -> U6_5(ReplicationStatus.Completed())
    else -> U6_6(ReplicationStatus.Unknown(v.value))
}

private fun toSdkIntelligentTieringAccessTier(v: Union3<IntelligentTieringAccessTier.ArchiveAccess, IntelligentTieringAccessTier.DeepArchiveAccess, IntelligentTieringAccessTier.Unknown>): aws.sdk.kotlin.services.s3.model.IntelligentTieringAccessTier = when (v) {
    is U3_1<*, *, *> -> aws.sdk.kotlin.services.s3.model.IntelligentTieringAccessTier.fromValue("ARCHIVE_ACCESS")
    is U3_2<*, *, *> -> aws.sdk.kotlin.services.s3.model.IntelligentTieringAccessTier.fromValue("DEEP_ARCHIVE_ACCESS")
    is U3_3<*, *, *> -> aws.sdk.kotlin.services.s3.model.IntelligentTieringAccessTier.fromValue((v.value as IntelligentTieringAccessTier.Unknown).value)
}

private fun fromSdkIntelligentTieringAccessTier(v: aws.sdk.kotlin.services.s3.model.IntelligentTieringAccessTier): Union3<IntelligentTieringAccessTier.ArchiveAccess, IntelligentTieringAccessTier.DeepArchiveAccess, IntelligentTieringAccessTier.Unknown> = when (v.value) {
    "ARCHIVE_ACCESS" -> U3_1(IntelligentTieringAccessTier.ArchiveAccess())
    "DEEP_ARCHIVE_ACCESS" -> U3_2(IntelligentTieringAccessTier.DeepArchiveAccess())
    else -> U3_3(IntelligentTieringAccessTier.Unknown(v.value))
}

private fun toSdkPutObjectInput(v: PutObjectInput, bodyStream: aws.smithy.kotlin.runtime.content.ByteStream): aws.sdk.kotlin.services.s3.model.PutObjectRequest = aws.sdk.kotlin.services.s3.model.PutObjectRequest {
    acl = v.acl?.let { toSdkObjectCannedACL(it) }
    body = bodyStream
    bucket = v.bucket
    cacheControl = v.cache_control
    contentDisposition = v.content_disposition
    contentEncoding = v.content_encoding
    contentLanguage = v.content_language
    contentLength = v.content_length
    contentMd5 = v.content_md5
    contentType = v.content_type
    checksumAlgorithm = v.checksum_algorithm?.let { toSdkChecksumAlgorithm(it) }
    checksumCrc32 = v.checksum_crc32
    checksumCrc32C = v.checksum_crc32_c
    checksumCrc64Nvme = v.checksum_crc64_nvme
    checksumSha1 = v.checksum_sha1
    checksumSha256 = v.checksum_sha256
    checksumSha512 = v.checksum_sha512
    checksumMd5 = v.checksum_md5
    checksumXxhash64 = v.checksum_xxhash64
    checksumXxhash3 = v.checksum_xxhash3
    checksumXxhash128 = v.checksum_xxhash128
    ifMatch = v.if_match
    ifNoneMatch = v.if_none_match
    grantFullControl = v.grant_full_control
    grantRead = v.grant_read
    grantReadAcp = v.grant_read_acp
    grantWriteAcp = v.grant_write_acp
    key = v.key
    writeOffsetBytes = v.write_offset_bytes
    metadata = v.metadata?.let { it.entries.associate { (k1, v1) -> k1 to v1 } }
    serverSideEncryption = v.server_side_encryption?.let { toSdkServerSideEncryption(it) }
    storageClass = v.storage_class?.let { toSdkStorageClass(it) }
    websiteRedirectLocation = v.website_redirect_location
    sseCustomerAlgorithm = v.sse_customer_algorithm
    sseCustomerKey = v.sse_customer_key
    sseCustomerKeyMd5 = v.sse_customer_key_md5
    ssekmsKeyId = v.ssekms_key_id
    ssekmsEncryptionContext = v.ssekms_encryption_context
    bucketKeyEnabled = v.bucket_key_enabled
    requestPayer = v.request_payer?.let { toSdkRequestPayer(it) }
    tagging = v.tagging
    objectLockMode = v.object_lock_mode?.let { toSdkObjectLockMode(it) }
    objectLockRetainUntilDate = v.object_lock_retain_until_date?.let { salvoDateTime(it) }
    objectLockLegalHoldStatus = v.object_lock_legal_hold_status?.let { toSdkObjectLockLegalHoldStatus(it) }
    objectLockEventHold = v.object_lock_event_hold?.let { toSdkObjectLockEventHold(it) }
    objectLockEventHoldDurationDays = v.object_lock_event_hold_duration_days
    objectLockEventHoldDurationYears = v.object_lock_event_hold_duration_years
    expectedBucketOwner = v.expected_bucket_owner
}

private fun fromSdkPutObjectOutput(v: aws.sdk.kotlin.services.s3.model.PutObjectResponse): PutObjectOutput = PutObjectOutput(
    expiration = v.expiration,
    e_tag = v.eTag,
    checksum_crc32 = v.checksumCrc32,
    checksum_crc32_c = v.checksumCrc32C,
    checksum_crc64_nvme = v.checksumCrc64Nvme,
    checksum_sha1 = v.checksumSha1,
    checksum_sha256 = v.checksumSha256,
    checksum_sha512 = v.checksumSha512,
    checksum_md5 = v.checksumMd5,
    checksum_xxhash64 = v.checksumXxhash64,
    checksum_xxhash3 = v.checksumXxhash3,
    checksum_xxhash128 = v.checksumXxhash128,
    checksum_type = v.checksumType?.let { fromSdkChecksumType(it) },
    server_side_encryption = v.serverSideEncryption?.let { fromSdkServerSideEncryption(it) },
    version_id = v.versionId,
    sse_customer_algorithm = v.sseCustomerAlgorithm,
    sse_customer_key_md5 = v.sseCustomerKeyMd5,
    ssekms_key_id = v.ssekmsKeyId,
    ssekms_encryption_context = v.ssekmsEncryptionContext,
    bucket_key_enabled = v.bucketKeyEnabled,
    size = v.size,
    request_charged = v.requestCharged?.let { fromSdkRequestCharged(it) },
)

private fun toSdkGetObjectInput(v: GetObjectInput): aws.sdk.kotlin.services.s3.model.GetObjectRequest = aws.sdk.kotlin.services.s3.model.GetObjectRequest {
    bucket = v.bucket
    ifMatch = v.if_match
    ifModifiedSince = v.if_modified_since?.let { salvoDateTime(it) }
    ifNoneMatch = v.if_none_match
    ifUnmodifiedSince = v.if_unmodified_since?.let { salvoDateTime(it) }
    key = v.key
    range = v.range
    responseCacheControl = v.response_cache_control
    responseContentDisposition = v.response_content_disposition
    responseContentEncoding = v.response_content_encoding
    responseContentLanguage = v.response_content_language
    responseContentType = v.response_content_type
    responseExpires = v.response_expires?.let { salvoDateTime(it) }
    versionId = v.version_id
    sseCustomerAlgorithm = v.sse_customer_algorithm
    sseCustomerKey = v.sse_customer_key
    sseCustomerKeyMd5 = v.sse_customer_key_md5
    requestPayer = v.request_payer?.let { toSdkRequestPayer(it) }
    partNumber = v.part_number
    expectedBucketOwner = v.expected_bucket_owner
    checksumMode = v.checksum_mode?.let { toSdkChecksumMode(it) }
}

private fun fromSdkGetObjectOutput(v: aws.sdk.kotlin.services.s3.model.GetObjectResponse, bodyHandle: Long): GetObjectOutput = GetObjectOutput(
    body = salvo.stream.InStream(bodyHandle),
    delete_marker = v.deleteMarker,
    accept_ranges = v.acceptRanges,
    expiration = v.expiration,
    restore = v.restore,
    last_modified = v.lastModified?.let { salvoInstant(it) },
    content_length = v.contentLength,
    e_tag = v.eTag,
    checksum_crc32 = v.checksumCrc32,
    checksum_crc32_c = v.checksumCrc32C,
    checksum_crc64_nvme = v.checksumCrc64Nvme,
    checksum_sha1 = v.checksumSha1,
    checksum_sha256 = v.checksumSha256,
    checksum_sha512 = v.checksumSha512,
    checksum_md5 = v.checksumMd5,
    checksum_xxhash64 = v.checksumXxhash64,
    checksum_xxhash3 = v.checksumXxhash3,
    checksum_xxhash128 = v.checksumXxhash128,
    checksum_type = v.checksumType?.let { fromSdkChecksumType(it) },
    missing_meta = v.missingMeta,
    version_id = v.versionId,
    cache_control = v.cacheControl,
    content_disposition = v.contentDisposition,
    content_encoding = v.contentEncoding,
    content_language = v.contentLanguage,
    content_range = v.contentRange,
    content_type = v.contentType,
    website_redirect_location = v.websiteRedirectLocation,
    server_side_encryption = v.serverSideEncryption?.let { fromSdkServerSideEncryption(it) },
    metadata = v.metadata?.let { it.entries.sortedBy { it.key }.associate { (k1, v1) -> k1 to v1 } },
    sse_customer_algorithm = v.sseCustomerAlgorithm,
    sse_customer_key_md5 = v.sseCustomerKeyMd5,
    ssekms_key_id = v.ssekmsKeyId,
    bucket_key_enabled = v.bucketKeyEnabled,
    storage_class = v.storageClass?.let { fromSdkStorageClass(it) },
    request_charged = v.requestCharged?.let { fromSdkRequestCharged(it) },
    replication_status = v.replicationStatus?.let { fromSdkReplicationStatus(it) },
    parts_count = v.partsCount,
    tag_count = v.tagCount,
    object_lock_mode = v.objectLockMode?.let { fromSdkObjectLockMode(it) },
    object_lock_retain_until_date = v.objectLockRetainUntilDate?.let { salvoInstant(it) },
    object_lock_legal_hold_status = v.objectLockLegalHoldStatus?.let { fromSdkObjectLockLegalHoldStatus(it) },
    object_lock_event_hold = v.objectLockEventHold?.let { fromSdkObjectLockEventHold(it) },
    object_lock_event_hold_duration_days = v.objectLockEventHoldDurationDays,
    object_lock_event_hold_duration_years = v.objectLockEventHoldDurationYears,
)

private fun fromSdkEncryptionTypeMismatch(v: aws.sdk.kotlin.services.s3.model.EncryptionTypeMismatch): EncryptionTypeMismatch = EncryptionTypeMismatch()

private fun fromSdkInvalidObjectState(v: aws.sdk.kotlin.services.s3.model.InvalidObjectState): InvalidObjectState = InvalidObjectState(
    storage_class = v.storageClass?.let { fromSdkStorageClass(it) },
    access_tier = v.accessTier?.let { fromSdkIntelligentTieringAccessTier(it) },
)

private fun fromSdkInvalidRequest(v: aws.sdk.kotlin.services.s3.model.InvalidRequest): InvalidRequest = InvalidRequest()

private fun fromSdkInvalidWriteOffset(v: aws.sdk.kotlin.services.s3.model.InvalidWriteOffset): InvalidWriteOffset = InvalidWriteOffset()

private fun fromSdkNoSuchKey(v: aws.sdk.kotlin.services.s3.model.NoSuchKey): NoSuchKey = NoSuchKey()

private fun fromSdkTooManyParts(v: aws.sdk.kotlin.services.s3.model.TooManyParts): TooManyParts = TooManyParts()

/** A Smithy timestamp as a `time.Instant`: nanoseconds since the epoch. */
private fun salvoInstant(t: aws.smithy.kotlin.runtime.time.Instant): salvo.time.Instant =
    salvo.time.Instant(nanos = t.epochSeconds * 1_000_000_000L + t.nanosecondsOfSecond)

/** A `time.Instant` as a Smithy timestamp. */
private fun salvoDateTime(at: salvo.time.Instant): aws.smithy.kotlin.runtime.time.Instant =
    aws.smithy.kotlin.runtime.time.Instant.fromEpochSeconds(
        Math.floorDiv(at.nanos, 1_000_000_000L),
        Math.floorMod(at.nanos, 1_000_000_000L).toInt(),
    )

/**
 * [stream-table] Registers a response body in the host's stream table,
 * answering its handle. [closed] completes when the program closes the
 * stream — or reads it to its end — which is what lets the SDK's response
 * block return and release the connection.
 */
private fun salvoRegisterBody(
    source: String,
    body: aws.smithy.kotlin.runtime.content.ByteStream?,
    closed: kotlinx.coroutines.CompletableDeferred<Unit>,
): Long {
    val input = body?.toInputStream()
        ?: java.io.ByteArrayInputStream(ByteArray(0))
    return SalvoStreams.registerIn(source, SalvoBody(input, closed), 0)
}

private class SalvoBody(
    input: java.io.InputStream,
    private val closed: kotlinx.coroutines.CompletableDeferred<Unit>,
) : java.io.FilterInputStream(input) {
    override fun close() {
        try {
            super.close()
        } finally {
            closed.complete(Unit)
        }
    }
}

/**
 * [stream-table] A request body streamed out of the host's table as the SDK
 * reads it: exactly [length] bytes, since the SDKs sign and checksum a body
 * of known length. A stream that ends early, or runs on past [length], fails
 * the read that finds it, which fails the request; the first failure is
 * kept in [problem]. Not retryable: a stream is read once.
 */
private class SalvoUpload(private val stream: SalvoIn, private val length: Long) : java.io.InputStream() {
    @Volatile var problem: String? = null
    private var left = length

    override fun read(): Int {
        val one = ByteArray(1)
        return if (read(one, 0, 1) <= 0) -1 else one[0].toInt() and 0xff
    }

    override fun read(b: ByteArray, off: Int, len: Int): Int {
        if (len == 0) return 0
        if (left == 0L) return -1
        val got = next(minOf(len.toLong(), left).toInt())
        if (got.isEmpty()) {
            fail("${stream.source}: ended after ${length - left} of the content_length of $length bytes")
        }
        // One byte past the end tells a stream longer than its length —
        // checked *before* the last chunk is handed over, since the SDK
        // stops reading at the length and would store a truncated object.
        if (left - got.size == 0L && next(1).isNotEmpty()) {
            fail("${stream.source}: longer than the content_length of $length bytes")
        }
        System.arraycopy(got, 0, b, off, got.size)
        left -= got.size
        return got.size
    }

    /** The upload's first failure, if any. */
    fun finish(): String? = problem

    private fun next(max: Int): ByteArray =
        try {
            synchronized(stream) { stream.readUpTo(max) }
        } catch (e: SalvoFaultException) {
            val f = e.fault
            fail("${stream.source}: " + if (f is SalvoFault.Failed) f.message else "not valid UTF-8")
        }

    private fun fail(message: String): Nothing {
        if (problem == null) problem = message
        throw java.io.IOException(message)
    }
}

private fun salvoAwsError(e: Throwable): AwsError {
    val code = (e as? aws.smithy.kotlin.runtime.ServiceException)?.sdkErrorMetadata?.errorCode
        ?: e::class.simpleName ?: "Exception"
    return AwsError(code = code, message = e.message ?: e.toString())
}
