// The host's Amazon Simple Queue Service: [HostSqs] implements `aws.sqs`'s
// [Sqs] over aws-sdk-kotlin and aws-sdk-rust. Its code is the platform
// templates beside this module, `platform/aws/sqs/host.sv.kt` and `.sv.rs`
// [host-splice].
//
// Its own module, as `fs.host` is: a program that fakes the service never
// reaches the host code, so it builds without the SDK.
//
// Generated by `salvo-client-codegen` from `models/sqs-2012-11-05.json`; do not
// edit — regenerate with `./gradlew generate` in `modules/aws/codegen`.

import aws
import aws.sqs

// [Sqs] through the platform's AWS SDK, configured by [config]: each call runs
// on the SDK's own asynchronous machinery (coroutines on the JVM, tokio on
// Rust) and completes its reply from there, so no Salvo worker waits.
// `threadsafe`: the SDK client is safe to share, so the instance is used from
// every pool with no lock.
export threadsafe platform handler HostSqs(config: AwsConfig) of Sqs
