// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 f43e3ad671dd7a33
// Generated by the Salvo compiler: the two clock readings std's `time`
// module is built on [time-types] [rs-time].
//
// Both answer nanoseconds in an `i64`, which is what `Instant`, `Tick` and
// `Duration` carry — one field each, so the seam between the language and the
// host is a number and nothing else.

use std::sync::OnceLock;
use std::time::Instant;

/// [time-ticker] The monotonic clock, in nanoseconds from an arbitrary
/// origin — this process's first reading, established here.
///
/// The origin has to live somewhere: Rust's `Instant` is opaque and cannot be
/// turned into a number, so a *process-wide* base is what makes two readings
/// comparable. One `OnceLock` for the whole program is the point — a base per
/// call site would put two origins in one program and make `between` answer
/// nonsense.
///
/// Never negative, and monotonically non-decreasing: `Instant` guarantees it,
/// and `duration_since` on the process base cannot underflow.
pub fn salvo_mono_nanos() -> i64 {
    static ORIGIN: OnceLock<Instant> = OnceLock::new();
    let origin = ORIGIN.get_or_init(Instant::now);
    Instant::now().duration_since(*origin).as_nanos() as i64
}
