// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 ffeecfddf36b70b1
// Host implementation of the platform declarations of Salvo module `runtime`:
// the primitives only the host can provide (the runtime record). Written by
// hand, against the generated `runtime.sv.kt`.
package salvo.platform.runtime

import java.util.concurrent.locks.LockSupport

// `threadsafe platform type Parker` [runtime-parker]: a thread's handle and
// its one token. The token is the parker's own flag, not `LockSupport`'s
// permit: every JDK lock parks through that permit too, so a `ReentrantLock`
// the thread waits on in between would consume an unpark meant for this
// parker, and the next park would never return. One parker per thread, so
// whoever holds a copy unparks the one the thread parks on.
class Parker(val thread: Thread) {
    val token = java.util.concurrent.atomic.AtomicBoolean(false)
}

private val parkers = ThreadLocal.withInitial { Parker(Thread.currentThread()) }

fun thisParker(): Parker = parkers.get()

private fun own(p: Parker) {
    check(p.thread === Thread.currentThread()) {
        "salvo: a thread parked on another thread's parker [runtime-parker]"
    }
}

fun park(p: Parker) {
    own(p)
    while (!p.token.compareAndSet(true, false)) {
        LockSupport.park(p)
    }
}

fun parkNanos(p: Parker, nanos: Long) {
    own(p)
    val deadline = System.nanoTime() + (if (nanos < 0) 0 else nanos)
    while (!p.token.compareAndSet(true, false)) {
        val left = deadline - System.nanoTime()
        if (left <= 0) return
        LockSupport.parkNanos(p, left)
    }
}

fun unpark(p: Parker) {
    p.token.set(true)
    LockSupport.unpark(p.thread)
}

// [runtime-kept-fn] A daemon thread, so it does not hold the JVM open after
// `main` returns.
fun startThread(body: () -> Unit) {
    val t = Thread { body() }
    t.isDaemon = true
    t.start()
}

// [runtime-kept-fn] The fault boundary: a throw is answered as its message.
fun guarded(body: () -> Unit): String? =
    try {
        body()
        null
    } catch (t: Throwable) {
        t.message ?: t.javaClass.simpleName
    }

// [runtime-sched] `linear platform type Dyn`: an erased value.
class Dyn(val v: Any?)

fun <T> erase(v: T): Dyn = Dyn(v)

@Suppress("UNCHECKED_CAST")
fun <T> unerase(d: Dyn): T = d.v as T

fun dropDyn(d: Dyn) {}

// [runtime-sched] `linear platform type Body`: what an activation runs.
class Body(val f: (Int, Long, Dyn) -> Unit)

fun bodyOf(f: (Int, Long, Dyn) -> Unit): Body = Body(f)

fun activate(b: Body, kind: Int, slot: Long, msg: Dyn): salvo.runtime.Ran =
    try {
        b.f(kind, slot, msg)
        salvo.runtime.Ran(b, null)
    } catch (t: Throwable) {
        salvo.runtime.Ran(b, t.message ?: t.javaClass.simpleName)
    }

fun dropBody(b: Body) {}

// [remote-backpressure] The routing layer's: a GRANT staged for the next
// flush, and the flush.
fun granted(addr: Int, pool: Int, from: Long) = salvo.runtime.routing.creditBack(addr, pool, from)

fun flushFrames() = salvo.runtime.routing.flush()

fun exitProcess(code: Int): Nothing = kotlin.system.exitProcess(code)

// [runtime-sched] `linear platform type Slot<T>`: a cell of at most one value.
class Slot<T>(var v: T?)

fun <T> slotOf(v: T): Slot<T> = Slot(v)

fun <T> slotEmpty(): Slot<T> = Slot(null)

fun <T> slotTake(s: Slot<T>): T? {
    val out = s.v
    s.v = null
    return out
}

fun <T> slotPut(s: Slot<T>, v: T) {
    s.v = v
}

fun <T> dropSlot(s: Slot<T>) {}

// [runtime-sched] Where this thread is: its pool and the actor whose
// activation it is inside (-1 for none). Main's thread starts on pool 0.
private val here = ThreadLocal.withInitial { intArrayOf(0, -1) }

fun herePool(): Int = here.get()[0]

fun hereActor(): Int = here.get()[1]

fun setHere(pool: Int, actor: Int) {
    here.set(intArrayOf(pool, actor))
}

// `threadsafe platform handler HostRuntime` [runtime-host]: stateless but for
// the `SecureRandom`, which is itself thread-safe.
class HostRuntime : salvo.runtime.RuntimeHostPlatform {
    private val random = java.security.SecureRandom()

    // [addr-capability] OS entropy, through the platform's secure source.
    override fun secureBits(): Long = random.nextLong()

    override fun report(line: String) {
        System.err.println(line)
    }

    // [time-timer] The clock `time.tick()` reads.
    override fun monoNanos(): Long = salvo.SalvoTime.monoNanos()
}

// [test-recover] The boundary for a lent body that answers: its answer, or
// the throw's message.
fun trapBoundary(body: () -> String?): String? =
    try {
        body()
    } catch (t: Throwable) {
        t.message ?: "a trap with no message"
    }
