// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 00a4643b6b12f596
// Generated by the Salvo compiler: the actor scheduler's host layer
// [rs-runtime-host]. The scheduler itself is Salvo — `std/runtime.sv`'s core and the routing service
// `std/runtime/routing.sv` (the runtime record), written once for both backends — and
// this file is what generated code and host code call: the entry points they
// always called, each a thin shim onto those, plus a registry of what only
// generated code knows (decoders, control builders, outbound hooks).
//
// The registry is a plain map; it is never held across a call into the core
// or the routing service.

use std::any::Any;
use std::collections::HashMap;
use std::sync::{Arc, Mutex, OnceLock};

use crate::platform_runtime::{Body, Dyn};

/// A message payload: any sendable value. The checker owns sendability
/// statically; the runtime is untyped.
pub type SalvoMsg = Box<dyn Any + Send>;

/// An actor body: state plus one entry point per kind of delivery.
/// Generated code implements `handle` as the member dispatch and `resume`
/// as the parked-continuation dispatch (by slot).
pub trait SalvoActor: Send {
    /// A user message (a `send fn` invocation).
    fn handle(&mut self, ctx: &SalvoCtx, msg: SalvoMsg);
    /// A reply delivery: the slot names the parked continuation.
    fn resume(&mut self, ctx: &SalvoCtx, slot: u64, value: SalvoMsg);
    /// [addr-routable] [wire-format] Decodes a reply that arrived over the
    /// wire for the continuation parked at `slot`: only the actor knows the
    /// answer's type. `None` when nothing is parked there or the bytes are
    /// malformed.
    fn decode_reply(&self, _slot: u64, _payload: &[u8]) -> Option<SalvoMsg> {
        None
    }
}

/// Passed to every activation: the actor's own identity.
pub struct SalvoCtx {
    pub addr: usize,
}

/// [platform-check] A check on the value sent on a reply.
pub type SalvoReplyCheck = Arc<dyn Fn(&dyn Any) + Send + Sync>;

/// [task-mint] A task body: a one-shot closure taking the answer.
pub type TaskBody = Box<dyn FnOnce(SalvoMsg) + Send>;

/// [addr-routable] The routable identity of an actor: the node hosting it,
/// its index there, and the unguessable capability bits minted at its spawn
/// [addr-capability].
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct RemoteRef {
    pub node: u64,
    pub actor: u64,
    pub bits: u64,
}

/// [wire-format] Decodes one message of one protocol, given the protocol's
/// hash and the payload.
pub type MsgDecoder = fn(&str, &[u8]) -> Option<SalvoMsg>;
/// [node-group] [actor-group] Builds the message a control frame's payload
/// arrives as: the sink's own private `control(from, data)` member.
pub type ControlOf = fn(u64, Vec<u8>) -> SalvoMsg;
/// [wire-format] Decodes one reply payload of a known type.
pub type ReplyDecoder = fn(&[u8]) -> Option<SalvoMsg>;
/// [actor-watch] [pool-fault-sink] Builds a message from a reason. The core
/// answers watches with `Exit` itself; for a pool's sink this builds the
/// `Faults` message its body receives.
pub type ExitOf = fn(String) -> SalvoMsg;
/// [actor-on-idle] Kept for the generated call sites; the core builds `Idle`.
pub type IdleOf = fn(i32, i32) -> SalvoMsg;

/// [addr-routable] A reply that arrived over the wire for an actor, still as
/// bytes: decoded by the actor's `decode_reply` when its activation runs.
struct RawReply(Vec<u8>);

/// [main-pool] The pool `main` is the single worker of.
pub const SALVO_MAIN_POOL: usize = 0;

// ---- the local surface: shims onto the core

/// [main-pool] The pool the calling thread works for.
pub fn salvo_current_pool() -> usize {
    crate::platform_runtime::here_pool() as usize
}


/// A pool of `n` workers whose faults go to the named report, for host code
/// (generated code calls `core.actor`'s Salvo `pool`).
pub fn salvo_pool(n: usize) -> usize {
    salvo_pool_with_sink(n, None)
}

/// [pool-fault-sink] The same, with an actor its uncaught faults go to and
/// the builder of the message it receives.
pub fn salvo_pool_with_sink(n: usize, sink: Option<(usize, ExitOf)>) -> usize {
    let sink_addr = match sink {
        Some((addr, build)) => {
            registry().sinks.insert(addr, build);
            addr as i32
        }
        None => -1,
    };
    let pool = crate::runtime::new_pool_of(n as i32, sink_addr);
    crate::runtime_routing::adopt(pool);
    pool as usize
}

/// [waitfor-dedicated] A pool of exactly one thread.
pub fn salvo_thread() -> usize {
    // [pool-retire] Its thread returns once its actor is dead.
    let pool = crate::runtime::new_dedicated_pool();
    crate::runtime_routing::adopt(pool);
    pool as usize
}

/// Spawns an actor on a pool; the queue bound is explicit.
pub fn salvo_spawn(pool: usize, bound: usize, actor: Box<dyn SalvoActor>, decode: Option<MsgDecoder>) -> usize {
    let addr = crate::runtime::spawn_body(pool as i32, bound as i32, body_of_actor(actor)) as usize;
    if let Some(d) = decode {
        registry().decode.insert(addr, d);
    }
    addr
}

/// The core's body for a generated actor: kind 0 a message, 1 an answer
/// (raw bytes decoded by the actor first), 2 a fault report for a pool's
/// sink, built into its message by the sink's builder.
fn body_of_actor(mut actor: Box<dyn SalvoActor>) -> Body {
    Body {
        f: Box::new(move |kind: i32, slot: i64, value: Dyn| {
            let ctx = SalvoCtx { addr: crate::platform_runtime::here_actor() as usize };
            match kind {
                0 => actor.handle(&ctx, value.v),
                1 => match value.v.downcast::<RawReply>() {
                    Ok(raw) => {
                        if let Some(v) = actor.decode_reply(slot as u64, &raw.0) {
                            actor.resume(&ctx, slot as u64, v);
                        }
                    }
                    Err(v) => actor.resume(&ctx, slot as u64, v),
                },
                _ => {
                    let reason = value.v.downcast::<String>().map(|b| *b).unwrap_or_default();
                    let build = registry().sinks.get(&ctx.addr).copied();
                    if let Some(build) = build {
                        actor.handle(&ctx, build(reason));
                    }
                }
            }
        }),
    }
}

/// Sends a user message: waits while the target's mailbox is full; a send
/// to the dead is the silent no-op.
pub fn salvo_send(addr: usize, msg: SalvoMsg) {
    crate::runtime::send_dyn(addr as i32, Dyn { v: msg });
}

/// A reply token targeting an actor's parked continuation, and its slot.
pub fn salvo_mint(addr: usize) -> (SalvoReply, u64) {
    let t = crate::runtime::mint(addr as i32, false);
    let slot = t.slot as u64;
    (SalvoReply::local(t, None), slot)
}

/// A gated reply token: until it is answered, the actor serves nothing else.
pub fn salvo_mint_gated(addr: usize) -> (SalvoReply, u64) {
    let t = crate::runtime::mint(addr as i32, true);
    let slot = t.slot as u64;
    (SalvoReply::local(t, None), slot)
}

/// [task-mint] A token whose answer schedules `body` on `pool`.
pub fn salvo_mint_task(pool: usize, body: TaskBody, decode: ReplyDecoder) -> SalvoReply {
    let mut once = Some(body);
    let b = Body {
        f: Box::new(move |_kind: i32, _slot: i64, value: Dyn| {
            if let Some(f) = once.take() {
                f(value.v);
            }
        }),
    };
    SalvoReply::local(crate::runtime::mint_task_on(pool as i32, b), Some(decode))
}

/// [actor-watch] A death watch: the core answers it with an `Exit`.
pub fn salvo_watch(addr: usize, on_exit: SalvoReply, _exit: ExitOf) {
    if let Some(t) = on_exit.take_local() {
        crate::runtime::watch(addr as i32, t);
    }
}

/// [actor-on-idle] A quiescence hook: the core answers it with an `Idle`.
pub fn salvo_on_idle(pool: usize, notify: SalvoReply, _idle: IdleOf) {
    if let Some(t) = notify.take_local() {
        crate::runtime::on_idle(pool as i32, t);
    }
}

/// [threadsafe-platform] A host thread that may inject work is open…
pub fn salvo_external_begin() {
    crate::runtime::external_begin();
}

/// …and is gone.
pub fn salvo_external_end() {
    crate::runtime::external_end();
}

/// A waiter: the `waitfor` bridge. Answers the token and the waiter's id.
pub fn salvo_waiter() -> (SalvoReply, usize) {
    let m = crate::runtime::waiter();
    let wid = m.wid as usize;
    (SalvoReply::local(m.token, None), wid)
}

/// [waitfor-pump] Waits for the waiter's answer, serving this thread's pool
/// meanwhile, and reports the deadlock when nothing can ever answer it.
pub fn salvo_wait(wid: usize) -> SalvoMsg {
    crate::runtime::await_answer(wid as i32).v
}

/// A one-shot reply capability: a token of the core's, or one minted on
/// another node and decoded here.
pub struct SalvoReply {
    inner: Mutex<ReplyInner>,
    check: Option<SalvoReplyCheck>,
    /// [wire-format] How a task's answer is decoded should it come back
    /// over the wire.
    decode: Option<ReplyDecoder>,
}

enum ReplyInner {
    Local(Option<crate::runtime::Token>),
    Remote(crate::runtime_routing::ReplyParts),
}

impl SalvoReply {
    fn local(t: crate::runtime::Token, decode: Option<ReplyDecoder>) -> Self {
        SalvoReply { inner: Mutex::new(ReplyInner::Local(Some(t))), check: None, decode }
    }

    fn take_local(&self) -> Option<crate::runtime::Token> {
        match &mut *self.inner.lock().unwrap() {
            ReplyInner::Local(t) => t.take(),
            ReplyInner::Remote(_) => None,
        }
    }

    /// Sends the reply, consuming the token. Enqueue only — user code never
    /// runs inside a `send`.
    pub fn send(self, value: SalvoMsg) {
        if let Some(check) = &self.check {
            check(&*value);
        }
        match self.take_local() {
            Some(t) => crate::runtime::answer(t, Dyn { v: value }),
            None => panic!("internal: an untyped reply to a remote token"),
        }
    }

    /// [platform-check] This token, checking what is sent on it.
    pub fn checked(mut self, check: SalvoReplyCheck) -> Self {
        self.check = Some(check);
        self
    }

    /// [platform-reply] Hands the token to host code that completes it later,
    /// from any thread; until then the program has an outside source of work.
    pub fn hosted(self) -> SalvoHostReply {
        crate::runtime::external_begin();
        SalvoHostReply { reply: Some(self) }
    }
}

/// [platform-reply] A reply the host has taken on.
pub struct SalvoHostReply {
    reply: Option<SalvoReply>,
}

impl SalvoHostReply {
    /// Completes the reply with `value`, from any thread.
    pub fn send<T: Any + Send>(mut self, value: T) {
        // Checked while the token is still held: a refused value unwinds
        // through `Drop`, which closes the outside source.
        if let Some(check) = self.reply.as_ref().and_then(|r| r.check.clone()) {
            check(&value);
        }
        let mut reply = self.reply.take().expect("a host reply holds its token until sent");
        reply.check = None;
        if matches!(&*reply.inner.lock().unwrap(), ReplyInner::Remote(_)) {
            panic!(
                "salvo: a host-completed reply to a token minted on another node is not \
                 supported yet [platform-reply]"
            );
        }
        reply.send(Box::new(value));
        crate::runtime::external_end();
    }
}

impl Drop for SalvoHostReply {
    /// [platform-reply] The host dropped a reply unsent: reported, and the
    /// outside source closed, so a frame waiting on it reports the deadlock
    /// it is in instead of waiting forever in silence.
    fn drop(&mut self) {
        if self.reply.take().is_none() {
            return;
        }
        crate::runtime::external_end();
        eprintln!("salvo: a host reply was dropped without being sent [platform-reply]");
    }
}

// ======================================================================
// [addr-routable] [addr-capability] [remote-backpressure] Across machines.
//
// The routing itself — identities, proxies, credits, routes and the frames,
// in the canonical encoding — is the Salvo service `runtime.routing`
// (`std/runtime/routing.sv`). What stays here is what only generated code
// knows: each actor's message decoder, each waiting frame's and exported
// task's answer decoder, each control sink's message builder and each node's
// outbound hook. The routing service reaches them through its platform fns
// (`std/platform/runtime/routing.rs`).
// ======================================================================

/// What generated code registered, by index.
pub struct Registry {
    pub sinks: HashMap<usize, ExitOf>,
    pub decode: HashMap<usize, MsgDecoder>,
    pub waiter_decode: HashMap<usize, ReplyDecoder>,
    pub task_decode: HashMap<i64, ReplyDecoder>,
    pub controls: HashMap<usize, ControlOf>,
    pub wires: HashMap<i64, Arc<dyn Fn(&[u8], Vec<u8>) + Send + Sync>>,
}

/// The registry, locked. Never held across a call into the core or the
/// routing service.
pub fn registry() -> std::sync::MutexGuard<'static, Registry> {
    static REG: OnceLock<Mutex<Registry>> = OnceLock::new();
    REG.get_or_init(|| {
        Mutex::new(Registry {
            sinks: HashMap::new(),
            decode: HashMap::new(),
            waiter_decode: HashMap::new(),
            task_decode: HashMap::new(),
            controls: HashMap::new(),
            wires: HashMap::new(),
        })
    })
    .lock()
    .unwrap()
}

/// [addr-routable] A reply that arrived over the wire for an actor, still as
/// bytes: decoded by the actor when its activation runs.
pub fn salvo_raw_answer(payload: Vec<u8>) -> Dyn {
    Dyn { v: Box::new(RawReply(payload)) }
}




/// [addr-routable] The routable identity of a local index.
pub fn salvo_addr_identity(addr: usize) -> RemoteRef {
    let r = crate::runtime_routing::identity(addr as i32);
    RemoteRef { node: r.node as u64, actor: r.actor as u64, bits: r.bits as u64 }
}


/// [addr-routable] [addr-capability] A decoded identity as a local index.
pub fn salvo_import_addr(r: RemoteRef) -> usize {
    crate::runtime_routing::import_addr(r.node as i64, r.actor as i64, r.bits as i64) as usize
}



/// [addr-routable] Binds the outbound hook of the current node.
pub fn salvo_set_wire(hook: Arc<dyn Fn(&[u8], Vec<u8>) + Send + Sync>) {
    let node = crate::runtime_routing::here_node();
    registry().wires.insert(node, hook);
    crate::runtime_routing::outbound_bound();
}

/// [addr-routable] [wire-format] The typed send: a local mailbox as any
/// send; for a proxy, encoded here and handed to the routing service, which
/// waits for a credit [remote-backpressure].
pub fn salvo_send_wire<M: crate::wire::__Wire + Any + Send>(addr: usize, msg: M, proto: &str) {
    // The core hands the message back when the addr is a proxy.
    let Some(back) = crate::runtime::send_or_back(addr as i32, Dyn { v: Box::new(msg) }) else { return };
    let Ok(msg) = back.v.downcast::<M>() else { return };
    let payload = crate::wire::salvo_encode(&*msg);
    crate::runtime_routing::send_remote(addr as i32, proto.to_string(), payload);
}





/// [route-stub] FNV-1a over the key's canonical bytes.
pub fn salvo_key_hash(bytes: &[u8]) -> i64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for b in bytes {
        h ^= *b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h as i64
}

/// [addr-routable] [wire-format] The typed reply: a token that came over the
/// wire is answered with a REPLY frame; a local one delivers as any reply.
pub fn salvo_reply_wire<T: crate::wire::__Wire + Any + Send>(reply: SalvoReply, value: T) {
    let remote = match &*reply.inner.lock().unwrap() {
        ReplyInner::Remote(parts) => Some(parts.clone()),
        ReplyInner::Local(_) => None,
    };
    match remote {
        Some(parts) => crate::runtime_routing::answer_remote(parts, crate::wire::salvo_encode(&value)),
        None => reply.send(Box::new(value)),
    }
}

/// [addr-routable] The wire form of a reply token. Exporting a task moves
/// its body into the routing service until its answer returns.
fn salvo_reply_export(reply: &SalvoReply) -> crate::runtime_routing::ReplyParts {
    let mut inner = reply.inner.lock().unwrap();
    match &mut *inner {
        ReplyInner::Remote(parts) => parts.clone(),
        ReplyInner::Local(t) => {
            let Some(t) = t.take() else {
                return crate::runtime_routing::ReplyParts { node: 0, kind: 0, id: 0, slot: 0, bits: 0 };
            };
            let parts = crate::runtime_routing::export_reply(crate::runtime::export_token(t));
            if parts.kind == 2 {
                if let Some(d) = reply.decode {
                    registry().task_decode.insert(parts.id, d);
                }
            }
            parts
        }
    }
}

/// [addr-routable] A reply token decoded from the wire: the original when it
/// names a target on this node, a remote token otherwise.
fn salvo_reply_import(parts: crate::runtime_routing::ReplyParts) -> SalvoReply {
    let here = crate::runtime_routing::here_node();
    let inner = if parts.node == here && parts.kind == 0 {
        ReplyInner::Local(Some(crate::runtime::token_to_actor(parts.id as i32, parts.slot)))
    } else if parts.node == here && parts.kind == 1 {
        ReplyInner::Local(Some(crate::runtime::token_to_waiter(parts.id as i32, parts.slot)))
    } else {
        ReplyInner::Remote(parts)
    };
    SalvoReply { inner: Mutex::new(inner), check: None, decode: None }
}

/// [addr-routable] Registers how a waiter's reply is decoded off the wire.
pub fn salvo_waiter_decoder(wid: usize, decode: ReplyDecoder) {
    registry().waiter_decode.insert(wid, decode);
}

/// [protocol-hash] Registers this program's protocol table.
pub fn salvo_set_protocols(table: Vec<(String, String)>) {
    crate::runtime_routing::register_protocols(table);
}




/// [node-group] [actor-group] Where the current node's control frames on
/// `channel` go, and the message they arrive as.
pub fn salvo_watch_control(channel: String, sink: usize, build: ControlOf) {
    registry().controls.insert(sink, build);
    crate::runtime_routing::watch_control(channel, sink as i32);
}





// [addr-routable] The codecs of the two scheduler handles live here, beside
// what they ask, so the wire stands alone in a program with no actors.

/// [addr-routable] An `Addr<E>` is a scheduler index in generated code; on
/// the wire it is its routable identity `(node, actor, bits)`, 24 bytes.
impl crate::wire::__Wire for usize {
    fn __enc(&self, out: &mut Vec<u8>) {
        let r = salvo_addr_identity(*self);
        out.extend_from_slice(&r.node.to_be_bytes());
        out.extend_from_slice(&r.actor.to_be_bytes());
        out.extend_from_slice(&r.bits.to_be_bytes());
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        let node = r.u64()?;
        let actor = r.u64()?;
        let bits = r.u64()?;
        Some(salvo_import_addr(RemoteRef { node, actor, bits }))
    }
}

/// [addr-routable] A `Reply<T>` on the wire: `(node, kind, id, slot, bits)`,
/// 33 bytes.
impl crate::wire::__Wire for SalvoReply {
    fn __enc(&self, out: &mut Vec<u8>) {
        let p = salvo_reply_export(self);
        out.extend_from_slice(&(p.node as u64).to_be_bytes());
        out.push(p.kind as u8);
        out.extend_from_slice(&(p.id as u64).to_be_bytes());
        out.extend_from_slice(&(p.slot as u64).to_be_bytes());
        out.extend_from_slice(&(p.bits as u64).to_be_bytes());
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        let node = r.u64()? as i64;
        let kind = r.u8()? as i32;
        let id = r.u64()? as i64;
        let slot = r.u64()? as i64;
        let bits = r.u64()? as i64;
        Some(salvo_reply_import(crate::runtime_routing::ReplyParts { node, kind, id, slot, bits }))
    }
}
