// Kotlin for `aws.sqs.host`'s `HostSqs` [host-splice]: host code, with Salvo
// between backticks, over the platform's AWS SDK.
//
// Generated by `salvo-client-codegen` from `models/sqs-2012-11-05.json`; do not
// edit — regenerate with `./gradlew generate` in `modules/aws/codegen`.

import aws.sdk.kotlin.services.sqs.model.CreateQueueRequest as SdkCreateQueueRequest
import aws.sdk.kotlin.services.sqs.model.CreateQueueResponse as SdkCreateQueueResponse
import aws.sdk.kotlin.services.sqs.model.DeleteMessageRequest as SdkDeleteMessageRequest
import aws.sdk.kotlin.services.sqs.model.DeleteQueueRequest as SdkDeleteQueueRequest
import aws.sdk.kotlin.services.sqs.model.GetQueueUrlRequest as SdkGetQueueUrlRequest
import aws.sdk.kotlin.services.sqs.model.GetQueueUrlResponse as SdkGetQueueUrlResponse
import aws.sdk.kotlin.services.sqs.model.Message as SdkMessage
import aws.sdk.kotlin.services.sqs.model.MessageAttributeValue as SdkMessageAttributeValue
import aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName as SdkMessageSystemAttributeName
import aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeNameForSends as SdkMessageSystemAttributeNameForSends
import aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeValue as SdkMessageSystemAttributeValue
import aws.sdk.kotlin.services.sqs.model.QueueAttributeName as SdkQueueAttributeName
import aws.sdk.kotlin.services.sqs.model.ReceiveMessageRequest as SdkReceiveMessageRequest
import aws.sdk.kotlin.services.sqs.model.ReceiveMessageResponse as SdkReceiveMessageResponse
import aws.sdk.kotlin.services.sqs.model.SendMessageRequest as SdkSendMessageRequest
import aws.sdk.kotlin.services.sqs.model.SendMessageResponse as SdkSendMessageResponse
import kotlinx.coroutines.launch

`threadsafe platform handler HostSqs(config: AwsConfig) of Sqs` {

    // The handler's host state: the SDK client, safe to share, and the scope
    // each call is a coroutine on.
    private val scope = kotlinx.coroutines.CoroutineScope(
        kotlinx.coroutines.SupervisorJob() + kotlinx.coroutines.Dispatchers.IO
    )
    private val `salvoConfig : AwsConfig` = `config`
    private val client = aws.sdk.kotlin.services.sqs.SqsClient {
        region = `salvoConfig.region.code`
        credentialsProvider = salvoCredentials(salvoConfig)
        `salvoConfig.endpoint`?.let { endpointUrl = aws.smithy.kotlin.runtime.net.url.Url.parse(it) }
    }

    init {
        salvoCloseWhenMainEnds(client)
    }

    private fun toSdkCreateQueueInput(`v : CreateQueueInput`): SdkCreateQueueRequest = SdkCreateQueueRequest {
        queueName = `v.queue_name`
        attributes = `v.attributes`?.let { it.entries.associate { (k1, v1) -> SdkQueueAttributeName.fromValue(k1) to v1 } }
        tags = `v.tags`?.let { it.entries.associate { (k1, v1) -> k1 to v1 } }
    }

    private fun fromSdkCreateQueueOutput(v: SdkCreateQueueResponse): `CreateQueueOutput` = `CreateQueueOutput { queue_url: @{v.queueUrl} }`

    private fun toSdkGetQueueUrlInput(`v : GetQueueUrlInput`): SdkGetQueueUrlRequest = SdkGetQueueUrlRequest {
        queueName = `v.queue_name`
        queueOwnerAwsAccountId = `v.queue_owner_aws_account_id`
    }

    private fun fromSdkGetQueueUrlOutput(v: SdkGetQueueUrlResponse): `GetQueueUrlOutput` = `GetQueueUrlOutput { queue_url: @{v.queueUrl} }`

    private fun toSdkSendMessageInput(`v : SendMessageInput`): SdkSendMessageRequest = SdkSendMessageRequest {
        queueUrl = `v.queue_url`
        messageBody = `v.message_body`
        delaySeconds = `v.delay_seconds`
        messageAttributes = `v.message_attributes`?.let { it.entries.associate { (k1, v1) -> k1 to toSdkMessageAttributeValue(v1) } }
        messageSystemAttributes = `v.message_system_attributes`?.let { it.entries.associate { (k1, v1) -> SdkMessageSystemAttributeNameForSends.fromValue(k1) to toSdkMessageSystemAttributeValue(v1) } }
        messageDeduplicationId = `v.message_deduplication_id`
        messageGroupId = `v.message_group_id`
    }

    private fun fromSdkMessageAttributeValue(v: SdkMessageAttributeValue): `MessageAttributeValue` = `MessageAttributeValue { string_value: @{v.stringValue}, binary_value: @{v.binaryValue?.let { salvo.SalvoBytes(it) }}, string_list_values: @{v.stringListValues?.let { it.map { e1 -> e1 } }}, binary_list_values: @{v.binaryListValues?.let { it.map { e1 -> salvo.SalvoBytes(e1) } }}, data_type: @{(v.dataType ?: error("missing required member DataType"))} }`

    private fun toSdkMessageAttributeValue(`v : MessageAttributeValue`): SdkMessageAttributeValue = SdkMessageAttributeValue {
        stringValue = `v.string_value`
        binaryValue = `v.binary_value`?.let { it.toByteArray() }
        stringListValues = `v.string_list_values`?.let { it.map { e1 -> e1 } }
        binaryListValues = `v.binary_list_values`?.let { it.map { e1 -> e1.toByteArray() } }
        dataType = `v.data_type`
    }

    private fun fromSdkMessageSystemAttributeValue(v: SdkMessageSystemAttributeValue): `MessageSystemAttributeValue` = `MessageSystemAttributeValue { string_value: @{v.stringValue}, binary_value: @{v.binaryValue?.let { salvo.SalvoBytes(it) }}, string_list_values: @{v.stringListValues?.let { it.map { e1 -> e1 } }}, binary_list_values: @{v.binaryListValues?.let { it.map { e1 -> salvo.SalvoBytes(e1) } }}, data_type: @{(v.dataType ?: error("missing required member DataType"))} }`

    private fun toSdkMessageSystemAttributeValue(`v : MessageSystemAttributeValue`): SdkMessageSystemAttributeValue = SdkMessageSystemAttributeValue {
        stringValue = `v.string_value`
        binaryValue = `v.binary_value`?.let { it.toByteArray() }
        stringListValues = `v.string_list_values`?.let { it.map { e1 -> e1 } }
        binaryListValues = `v.binary_list_values`?.let { it.map { e1 -> e1.toByteArray() } }
        dataType = `v.data_type`
    }

    private fun fromSdkSendMessageOutput(v: SdkSendMessageResponse): `SendMessageOutput` = `SendMessageOutput { md5_of_message_body: @{v.md5OfMessageBody}, md5_of_message_attributes: @{v.md5OfMessageAttributes}, md5_of_message_system_attributes: @{v.md5OfMessageSystemAttributes}, message_id: @{v.messageId}, sequence_number: @{v.sequenceNumber} }`

    private fun toSdkReceiveMessageInput(`v : ReceiveMessageInput`): SdkReceiveMessageRequest = SdkReceiveMessageRequest {
        queueUrl = `v.queue_url`
        attributeNames = `v.attribute_names`?.let { it.map { e1 -> SdkQueueAttributeName.fromValue(e1) } }
        messageSystemAttributeNames = `v.message_system_attribute_names`?.let { it.map { e1 -> SdkMessageSystemAttributeName.fromValue(e1) } }
        messageAttributeNames = `v.message_attribute_names`?.let { it.map { e1 -> e1 } }
        maxNumberOfMessages = `v.max_number_of_messages`
        visibilityTimeout = `v.visibility_timeout`
        waitTimeSeconds = `v.wait_time_seconds`
        receiveRequestAttemptId = `v.receive_request_attempt_id`
    }

    private fun fromSdkReceiveMessageOutput(v: SdkReceiveMessageResponse): `ReceiveMessageOutput` = `ReceiveMessageOutput { messages: @{v.messages?.let { it.map { e1 -> fromSdkMessage(e1) } }} }`

    private fun fromSdkMessage(v: SdkMessage): `Message` = `Message { message_id: @{v.messageId}, receipt_handle: @{v.receiptHandle}, md5_of_body: @{v.md5OfBody}, body: @{v.body}, attributes: @{v.attributes?.let { it.entries.sortedBy { it.key.value }.associate { (k1, v1) -> k1.value to v1 } }}, md5_of_message_attributes: @{v.md5OfMessageAttributes}, message_attributes: @{v.messageAttributes?.let { it.entries.sortedBy { it.key }.associate { (k1, v1) -> k1 to fromSdkMessageAttributeValue(v1) } }} }`

    private fun toSdkMessage(`v : Message`): SdkMessage = SdkMessage {
        messageId = `v.message_id`
        receiptHandle = `v.receipt_handle`
        md5OfBody = `v.md5_of_body`
        body = `v.body`
        attributes = `v.attributes`?.let { it.entries.associate { (k1, v1) -> SdkMessageSystemAttributeName.fromValue(k1) to v1 } }
        md5OfMessageAttributes = `v.md5_of_message_attributes`
        messageAttributes = `v.message_attributes`?.let { it.entries.associate { (k1, v1) -> k1 to toSdkMessageAttributeValue(v1) } }
    }

    private fun toSdkDeleteMessageInput(`v : DeleteMessageInput`): SdkDeleteMessageRequest = SdkDeleteMessageRequest {
        queueUrl = `v.queue_url`
        receiptHandle = `v.receipt_handle`
    }

    private fun toSdkDeleteQueueInput(`v : DeleteQueueInput`): SdkDeleteQueueRequest = SdkDeleteQueueRequest {
        queueUrl = `v.queue_url`
    }

    /** A code as the model names it (see the Rust block's `salvo_code`). */
    private fun salvoCode(code: String): String = when (val c = code.substringAfterLast('#')) {
        "AWS.SimpleQueueService.NonExistentQueue" -> "QueueDoesNotExist"
        "AWS.SimpleQueueService.QueueDeletedRecently" -> "QueueDeletedRecently"
        "AWS.SimpleQueueService.UnsupportedOperation" -> "UnsupportedOperation"
        "KMS.AccessDeniedException" -> "KmsAccessDenied"
        "KMS.DisabledException" -> "KmsDisabled"
        "KMS.InvalidKeyUsageException" -> "KmsInvalidKeyUsage"
        "KMS.InvalidStateException" -> "KmsInvalidState"
        "KMS.NotFoundException" -> "KmsNotFound"
        "KMS.OptInRequired" -> "KmsOptInRequired"
        "KMS.ThrottlingException" -> "KmsThrottled"
        "QueueAlreadyExists" -> "QueueNameExists"
        else -> c
    }

    private fun salvoFailure(e: aws.smithy.kotlin.runtime.ServiceException): `SqsError` {
        val meta = e.sdkErrorMetadata
        val response = meta.protocolResponse as? aws.smithy.kotlin.runtime.http.response.HttpResponse
        val code = salvoCode(meta.errorCode ?: "Unknown")
        val message = meta.errorMessage ?: ""
        val status = response?.status?.value ?: 0
        val requestId = meta.requestId
        return `SqsError { code: @{code}, message: @{message}, status: @{status}, request_id: @{requestId} }`
    }

    private fun salvoAwsError(e: Throwable): `AwsError` {
        val code = (e as? aws.smithy.kotlin.runtime.ServiceException)?.sdkErrorMetadata?.errorCode
            ?: e::class.simpleName ?: "Exception"
        val message = e.message ?: e.toString()
        return `AwsError { code: @{code}, message: @{message} }`
    }

    /** The SDK credentials provider an `AwsConfig`'s credentials name. */
    @OptIn(aws.sdk.kotlin.runtime.InternalSdkApi::class)
    private fun salvoCredentials(`cfg : AwsConfig`): aws.smithy.kotlin.runtime.auth.awscredentials.CredentialsProvider {
        val profile = `profile_of(cfg.credentials)`
        if (profile != null) {
            return aws.sdk.kotlin.runtime.auth.credentials.ProfileCredentialsProvider(
                profileName = `(@{profile} : ProfileCredentials).profile`,
                configurationSource = aws.sdk.kotlin.runtime.config.profile.AwsConfigurationSource(
                    `(@{profile} : ProfileCredentials).profile`,
                    salvoExpandHome("~/.aws/config"),
                    salvoExpandHome(`(@{profile} : ProfileCredentials).path`),
                ),
            )
        }
        if (`uses_environment(cfg.credentials)`) {
            return aws.sdk.kotlin.runtime.auth.credentials.EnvironmentCredentialsProvider()
        }
        return aws.sdk.kotlin.runtime.auth.credentials.DefaultChainCredentialsProvider()
    }

    /** `~/` at the front of a path is the home directory, as a shell would read it. */
    private fun salvoExpandHome(path: String): String =
        if (path.startsWith("~/")) (System.getenv("HOME") ?: System.getProperty("user.home")) + path.substring(1) else path

    /**
     * Closes [client] once the program's `main` thread has ended. The SDK's
     * HTTP engine (OkHttp) keeps a non-daemon dispatcher thread alive for 60s
     * after its last call, which would hold the JVM open that long after the
     * program is done; a Rust program exits when `main` returns, and this
     * makes the JVM do the same. A stopgap: the runtime ending the process
     * when `main` returns is on the roadmap, to be designed.
     */
    private fun salvoCloseWhenMainEnds(client: AutoCloseable) {
        val main = Thread.getAllStackTraces().keys.firstOrNull { it.name == "main" && it.threadGroup?.name == "main" }
            ?: return
        val closer = Thread {
            main.join()
            runCatching { client.close() }
        }
        closer.isDaemon = true
        closer.name = "salvo-aws-close"
        closer.start()
    }

    `fn create_queue(input: CreateQueueInput, reply: Reply<Ok CreateQueueOutput | Err Checked<SqsFailure>>) -> None` {
        val host = `reply`.hosted()
        val request = `input`
        scope.launch {
            val `answer : Ok CreateQueueOutput | Err Checked<SqsFailure>` = try {
                val `value : CreateQueueOutput` = fromSdkCreateQueueOutput(client.createQueue(toSdkCreateQueueInput(request)))
                `ok(value) : answer`
            } catch (e: aws.smithy.kotlin.runtime.ServiceException) {
                val `failure : SqsError` = salvoFailure(e)
                `err(checked<SqsFailure>(failure)) : answer`
            } catch (e: Exception) {
                val `failure : AwsError` = salvoAwsError(e)
                `err(checked<SqsFailure>(failure)) : answer`
            }
            host.send(answer)
        }
    }

    `fn get_queue_url(input: GetQueueUrlInput, reply: Reply<Ok GetQueueUrlOutput | Err Checked<SqsFailure>>) -> None` {
        val host = `reply`.hosted()
        val request = `input`
        scope.launch {
            val `answer : Ok GetQueueUrlOutput | Err Checked<SqsFailure>` = try {
                val `value : GetQueueUrlOutput` = fromSdkGetQueueUrlOutput(client.getQueueUrl(toSdkGetQueueUrlInput(request)))
                `ok(value) : answer`
            } catch (e: aws.smithy.kotlin.runtime.ServiceException) {
                val `failure : SqsError` = salvoFailure(e)
                `err(checked<SqsFailure>(failure)) : answer`
            } catch (e: Exception) {
                val `failure : AwsError` = salvoAwsError(e)
                `err(checked<SqsFailure>(failure)) : answer`
            }
            host.send(answer)
        }
    }

    `fn send_message(input: SendMessageInput, reply: Reply<Ok SendMessageOutput | Err Checked<SqsFailure>>) -> None` {
        val host = `reply`.hosted()
        val request = `input`
        scope.launch {
            val `answer : Ok SendMessageOutput | Err Checked<SqsFailure>` = try {
                val `value : SendMessageOutput` = fromSdkSendMessageOutput(client.sendMessage(toSdkSendMessageInput(request)))
                `ok(value) : answer`
            } catch (e: aws.smithy.kotlin.runtime.ServiceException) {
                val `failure : SqsError` = salvoFailure(e)
                `err(checked<SqsFailure>(failure)) : answer`
            } catch (e: Exception) {
                val `failure : AwsError` = salvoAwsError(e)
                `err(checked<SqsFailure>(failure)) : answer`
            }
            host.send(answer)
        }
    }

    `fn receive_message(input: ReceiveMessageInput, reply: Reply<Ok ReceiveMessageOutput | Err Checked<SqsFailure>>) -> None` {
        val host = `reply`.hosted()
        val request = `input`
        scope.launch {
            val `answer : Ok ReceiveMessageOutput | Err Checked<SqsFailure>` = try {
                val `value : ReceiveMessageOutput` = fromSdkReceiveMessageOutput(client.receiveMessage(toSdkReceiveMessageInput(request)))
                `ok(value) : answer`
            } catch (e: aws.smithy.kotlin.runtime.ServiceException) {
                val `failure : SqsError` = salvoFailure(e)
                `err(checked<SqsFailure>(failure)) : answer`
            } catch (e: Exception) {
                val `failure : AwsError` = salvoAwsError(e)
                `err(checked<SqsFailure>(failure)) : answer`
            }
            host.send(answer)
        }
    }

    `fn delete_message(input: DeleteMessageInput, reply: Reply<Ok None | Err Checked<SqsFailure>>) -> None` {
        val host = `reply`.hosted()
        val request = `input`
        scope.launch {
            val `answer : Ok None | Err Checked<SqsFailure>` = try {
                client.deleteMessage(toSdkDeleteMessageInput(request))
                `ok(None) : answer`
            } catch (e: aws.smithy.kotlin.runtime.ServiceException) {
                val `failure : SqsError` = salvoFailure(e)
                `err(checked<SqsFailure>(failure)) : answer`
            } catch (e: Exception) {
                val `failure : AwsError` = salvoAwsError(e)
                `err(checked<SqsFailure>(failure)) : answer`
            }
            host.send(answer)
        }
    }

    `fn delete_queue(input: DeleteQueueInput, reply: Reply<Ok None | Err Checked<SqsFailure>>) -> None` {
        val host = `reply`.hosted()
        val request = `input`
        scope.launch {
            val `answer : Ok None | Err Checked<SqsFailure>` = try {
                client.deleteQueue(toSdkDeleteQueueInput(request))
                `ok(None) : answer`
            } catch (e: aws.smithy.kotlin.runtime.ServiceException) {
                val `failure : SqsError` = salvoFailure(e)
                `err(checked<SqsFailure>(failure)) : answer`
            } catch (e: Exception) {
                val `failure : AwsError` = salvoAwsError(e)
                `err(checked<SqsFailure>(failure)) : answer`
            }
            host.send(answer)
        }
    }
}
