// Host implementation of `aws.sqs.host`'s `HostSqs`,
// over aws-sdk-kotlin (`aws.sdk.kotlin.services.sqs`) [platform-reply].
//
// Generated by `salvo-client-codegen` from `models/sqs-2012-11-05.json`; do not
// edit — regenerate with `./gradlew generate` in `modules/aws/codegen`.
@file:OptIn(aws.smithy.kotlin.runtime.InternalApi::class, aws.sdk.kotlin.runtime.InternalSdkApi::class)
@file:Suppress("DEPRECATION", "UNUSED_PARAMETER", "UNCHECKED_CAST", "USELESS_ELVIS", "UNNECESSARY_SAFE_CALL")

package salvo.platform.aws.sqs.host

import salvo.*
import salvo.aws.*
import salvo.aws.sqs.*
import salvo.aws.sqs.host.*
import kotlinx.coroutines.launch

// `threadsafe platform handler HostSqs`: the SDK client is safe to share, and
// each call is a coroutine on the handler's own scope, completing its reply there.
class HostSqs(private val config: AwsConfig) : Sqs {
    private val scope = kotlinx.coroutines.CoroutineScope(
        kotlinx.coroutines.SupervisorJob() + kotlinx.coroutines.Dispatchers.IO
    )
    private val client = aws.sdk.kotlin.services.sqs.SqsClient {
        region = this@HostSqs.config.region.code
        credentialsProvider = salvoCredentials(this@HostSqs.config.credentials)
        this@HostSqs.config.endpoint?.let { endpointUrl = aws.smithy.kotlin.runtime.net.url.Url.parse(it) }
    }

    override fun create_queue(input: CreateQueueInput, reply: salvo.SalvoReply) {
        val host = reply.hosted()
        scope.launch {
            val answer: Union2<CreateQueueOutput, salvo.core.checked.Checked<Union21<InvalidAddress, InvalidAttributeName, InvalidAttributeValue, InvalidIdFormat, InvalidMessageContents, InvalidSecurity, KmsAccessDenied, KmsDisabled, KmsInvalidKeyUsage, KmsInvalidState, KmsNotFound, KmsOptInRequired, KmsThrottled, OverLimit, QueueDeletedRecently, QueueDoesNotExist, QueueNameExists, ReceiptHandleIsInvalid, RequestThrottled, UnsupportedOperation, AwsError>>> = try {
                U2_1(fromSdkCreateQueueOutput(client.createQueue(toSdkCreateQueueInput(input))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidAddress) {
                U2_2(salvo.core.checked.Checked(U21_1(fromSdkInvalidAddress(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidAttributeName) {
                U2_2(salvo.core.checked.Checked(U21_2(fromSdkInvalidAttributeName(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidAttributeValue) {
                U2_2(salvo.core.checked.Checked(U21_3(fromSdkInvalidAttributeValue(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidSecurity) {
                U2_2(salvo.core.checked.Checked(U21_6(fromSdkInvalidSecurity(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.QueueDeletedRecently) {
                U2_2(salvo.core.checked.Checked(U21_15(fromSdkQueueDeletedRecently(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.QueueNameExists) {
                U2_2(salvo.core.checked.Checked(U21_17(fromSdkQueueNameExists(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.RequestThrottled) {
                U2_2(salvo.core.checked.Checked(U21_19(fromSdkRequestThrottled(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.UnsupportedOperation) {
                U2_2(salvo.core.checked.Checked(U21_20(fromSdkUnsupportedOperation(e))))
            } catch (e: Exception) {
                U2_2(salvo.core.checked.Checked(U21_21(salvoAwsError(e))))
            }
            host.send(answer)
        }
    }

    override fun get_queue_url(input: GetQueueUrlInput, reply: salvo.SalvoReply) {
        val host = reply.hosted()
        scope.launch {
            val answer: Union2<GetQueueUrlOutput, salvo.core.checked.Checked<Union21<InvalidAddress, InvalidAttributeName, InvalidAttributeValue, InvalidIdFormat, InvalidMessageContents, InvalidSecurity, KmsAccessDenied, KmsDisabled, KmsInvalidKeyUsage, KmsInvalidState, KmsNotFound, KmsOptInRequired, KmsThrottled, OverLimit, QueueDeletedRecently, QueueDoesNotExist, QueueNameExists, ReceiptHandleIsInvalid, RequestThrottled, UnsupportedOperation, AwsError>>> = try {
                U2_1(fromSdkGetQueueUrlOutput(client.getQueueUrl(toSdkGetQueueUrlInput(input))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidAddress) {
                U2_2(salvo.core.checked.Checked(U21_1(fromSdkInvalidAddress(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidSecurity) {
                U2_2(salvo.core.checked.Checked(U21_6(fromSdkInvalidSecurity(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.QueueDoesNotExist) {
                U2_2(salvo.core.checked.Checked(U21_16(fromSdkQueueDoesNotExist(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.RequestThrottled) {
                U2_2(salvo.core.checked.Checked(U21_19(fromSdkRequestThrottled(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.UnsupportedOperation) {
                U2_2(salvo.core.checked.Checked(U21_20(fromSdkUnsupportedOperation(e))))
            } catch (e: Exception) {
                U2_2(salvo.core.checked.Checked(U21_21(salvoAwsError(e))))
            }
            host.send(answer)
        }
    }

    override fun send_message(input: SendMessageInput, reply: salvo.SalvoReply) {
        val host = reply.hosted()
        scope.launch {
            val answer: Union2<SendMessageOutput, salvo.core.checked.Checked<Union21<InvalidAddress, InvalidAttributeName, InvalidAttributeValue, InvalidIdFormat, InvalidMessageContents, InvalidSecurity, KmsAccessDenied, KmsDisabled, KmsInvalidKeyUsage, KmsInvalidState, KmsNotFound, KmsOptInRequired, KmsThrottled, OverLimit, QueueDeletedRecently, QueueDoesNotExist, QueueNameExists, ReceiptHandleIsInvalid, RequestThrottled, UnsupportedOperation, AwsError>>> = try {
                U2_1(fromSdkSendMessageOutput(client.sendMessage(toSdkSendMessageInput(input))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidAddress) {
                U2_2(salvo.core.checked.Checked(U21_1(fromSdkInvalidAddress(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidMessageContents) {
                U2_2(salvo.core.checked.Checked(U21_5(fromSdkInvalidMessageContents(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidSecurity) {
                U2_2(salvo.core.checked.Checked(U21_6(fromSdkInvalidSecurity(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsAccessDenied) {
                U2_2(salvo.core.checked.Checked(U21_7(fromSdkKmsAccessDenied(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsDisabled) {
                U2_2(salvo.core.checked.Checked(U21_8(fromSdkKmsDisabled(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsInvalidKeyUsage) {
                U2_2(salvo.core.checked.Checked(U21_9(fromSdkKmsInvalidKeyUsage(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsInvalidState) {
                U2_2(salvo.core.checked.Checked(U21_10(fromSdkKmsInvalidState(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsNotFound) {
                U2_2(salvo.core.checked.Checked(U21_11(fromSdkKmsNotFound(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsOptInRequired) {
                U2_2(salvo.core.checked.Checked(U21_12(fromSdkKmsOptInRequired(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsThrottled) {
                U2_2(salvo.core.checked.Checked(U21_13(fromSdkKmsThrottled(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.QueueDoesNotExist) {
                U2_2(salvo.core.checked.Checked(U21_16(fromSdkQueueDoesNotExist(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.RequestThrottled) {
                U2_2(salvo.core.checked.Checked(U21_19(fromSdkRequestThrottled(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.UnsupportedOperation) {
                U2_2(salvo.core.checked.Checked(U21_20(fromSdkUnsupportedOperation(e))))
            } catch (e: Exception) {
                U2_2(salvo.core.checked.Checked(U21_21(salvoAwsError(e))))
            }
            host.send(answer)
        }
    }

    override fun receive_message(input: ReceiveMessageInput, reply: salvo.SalvoReply) {
        val host = reply.hosted()
        scope.launch {
            val answer: Union2<ReceiveMessageOutput, salvo.core.checked.Checked<Union21<InvalidAddress, InvalidAttributeName, InvalidAttributeValue, InvalidIdFormat, InvalidMessageContents, InvalidSecurity, KmsAccessDenied, KmsDisabled, KmsInvalidKeyUsage, KmsInvalidState, KmsNotFound, KmsOptInRequired, KmsThrottled, OverLimit, QueueDeletedRecently, QueueDoesNotExist, QueueNameExists, ReceiptHandleIsInvalid, RequestThrottled, UnsupportedOperation, AwsError>>> = try {
                U2_1(fromSdkReceiveMessageOutput(client.receiveMessage(toSdkReceiveMessageInput(input))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidAddress) {
                U2_2(salvo.core.checked.Checked(U21_1(fromSdkInvalidAddress(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidSecurity) {
                U2_2(salvo.core.checked.Checked(U21_6(fromSdkInvalidSecurity(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsAccessDenied) {
                U2_2(salvo.core.checked.Checked(U21_7(fromSdkKmsAccessDenied(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsDisabled) {
                U2_2(salvo.core.checked.Checked(U21_8(fromSdkKmsDisabled(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsInvalidKeyUsage) {
                U2_2(salvo.core.checked.Checked(U21_9(fromSdkKmsInvalidKeyUsage(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsInvalidState) {
                U2_2(salvo.core.checked.Checked(U21_10(fromSdkKmsInvalidState(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsNotFound) {
                U2_2(salvo.core.checked.Checked(U21_11(fromSdkKmsNotFound(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsOptInRequired) {
                U2_2(salvo.core.checked.Checked(U21_12(fromSdkKmsOptInRequired(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.KmsThrottled) {
                U2_2(salvo.core.checked.Checked(U21_13(fromSdkKmsThrottled(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.OverLimit) {
                U2_2(salvo.core.checked.Checked(U21_14(fromSdkOverLimit(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.QueueDoesNotExist) {
                U2_2(salvo.core.checked.Checked(U21_16(fromSdkQueueDoesNotExist(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.RequestThrottled) {
                U2_2(salvo.core.checked.Checked(U21_19(fromSdkRequestThrottled(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.UnsupportedOperation) {
                U2_2(salvo.core.checked.Checked(U21_20(fromSdkUnsupportedOperation(e))))
            } catch (e: Exception) {
                U2_2(salvo.core.checked.Checked(U21_21(salvoAwsError(e))))
            }
            host.send(answer)
        }
    }

    override fun delete_message(input: DeleteMessageInput, reply: salvo.SalvoReply) {
        val host = reply.hosted()
        scope.launch {
            val answer: Union2<Unit, salvo.core.checked.Checked<Union21<InvalidAddress, InvalidAttributeName, InvalidAttributeValue, InvalidIdFormat, InvalidMessageContents, InvalidSecurity, KmsAccessDenied, KmsDisabled, KmsInvalidKeyUsage, KmsInvalidState, KmsNotFound, KmsOptInRequired, KmsThrottled, OverLimit, QueueDeletedRecently, QueueDoesNotExist, QueueNameExists, ReceiptHandleIsInvalid, RequestThrottled, UnsupportedOperation, AwsError>>> = try {
                client.deleteMessage(toSdkDeleteMessageInput(input))
                U2_1(Unit)
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidAddress) {
                U2_2(salvo.core.checked.Checked(U21_1(fromSdkInvalidAddress(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidIdFormat) {
                U2_2(salvo.core.checked.Checked(U21_4(fromSdkInvalidIdFormat(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidSecurity) {
                U2_2(salvo.core.checked.Checked(U21_6(fromSdkInvalidSecurity(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.QueueDoesNotExist) {
                U2_2(salvo.core.checked.Checked(U21_16(fromSdkQueueDoesNotExist(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.ReceiptHandleIsInvalid) {
                U2_2(salvo.core.checked.Checked(U21_18(fromSdkReceiptHandleIsInvalid(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.RequestThrottled) {
                U2_2(salvo.core.checked.Checked(U21_19(fromSdkRequestThrottled(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.UnsupportedOperation) {
                U2_2(salvo.core.checked.Checked(U21_20(fromSdkUnsupportedOperation(e))))
            } catch (e: Exception) {
                U2_2(salvo.core.checked.Checked(U21_21(salvoAwsError(e))))
            }
            host.send(answer)
        }
    }

    override fun delete_queue(input: DeleteQueueInput, reply: salvo.SalvoReply) {
        val host = reply.hosted()
        scope.launch {
            val answer: Union2<Unit, salvo.core.checked.Checked<Union21<InvalidAddress, InvalidAttributeName, InvalidAttributeValue, InvalidIdFormat, InvalidMessageContents, InvalidSecurity, KmsAccessDenied, KmsDisabled, KmsInvalidKeyUsage, KmsInvalidState, KmsNotFound, KmsOptInRequired, KmsThrottled, OverLimit, QueueDeletedRecently, QueueDoesNotExist, QueueNameExists, ReceiptHandleIsInvalid, RequestThrottled, UnsupportedOperation, AwsError>>> = try {
                client.deleteQueue(toSdkDeleteQueueInput(input))
                U2_1(Unit)
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidAddress) {
                U2_2(salvo.core.checked.Checked(U21_1(fromSdkInvalidAddress(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.InvalidSecurity) {
                U2_2(salvo.core.checked.Checked(U21_6(fromSdkInvalidSecurity(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.QueueDoesNotExist) {
                U2_2(salvo.core.checked.Checked(U21_16(fromSdkQueueDoesNotExist(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.RequestThrottled) {
                U2_2(salvo.core.checked.Checked(U21_19(fromSdkRequestThrottled(e))))
            } catch (e: aws.sdk.kotlin.services.sqs.model.UnsupportedOperation) {
                U2_2(salvo.core.checked.Checked(U21_20(fromSdkUnsupportedOperation(e))))
            } catch (e: Exception) {
                U2_2(salvo.core.checked.Checked(U21_21(salvoAwsError(e))))
            }
            host.send(answer)
        }
    }
}

/** The SDK credentials provider an `AwsConfig`'s credentials name. */
private fun salvoCredentials(
    c: Union3<ProfileCredentials, EnvironmentCredentials, DefaultChain>,
): aws.smithy.kotlin.runtime.auth.awscredentials.CredentialsProvider = when (c) {
    is U3_1<*, *, *> -> {
        val p = c.value as ProfileCredentials
        aws.sdk.kotlin.runtime.auth.credentials.ProfileCredentialsProvider(
            profileName = p.profile,
            configurationSource = aws.sdk.kotlin.runtime.config.profile.AwsConfigurationSource(
                p.profile,
                salvoExpandHome("~/.aws/config"),
                salvoExpandHome(p.path),
            ),
        )
    }
    is U3_2<*, *, *> -> aws.sdk.kotlin.runtime.auth.credentials.EnvironmentCredentialsProvider()
    is U3_3<*, *, *> -> aws.sdk.kotlin.runtime.auth.credentials.DefaultChainCredentialsProvider()
}

/** `~/` at the front of a path is the home directory, as a shell would read it. */
private fun salvoExpandHome(path: String): String =
    if (path.startsWith("~/")) (System.getenv("HOME") ?: System.getProperty("user.home")) + path.substring(1) else path

private fun toSdkQueueAttributeName(v: Union23<QueueAttributeName.All, QueueAttributeName.Policy, QueueAttributeName.VisibilityTimeout, QueueAttributeName.MaximumMessageSize, QueueAttributeName.MessageRetentionPeriod, QueueAttributeName.ApproximateNumberOfMessages, QueueAttributeName.ApproximateNumberOfMessagesNotVisible, QueueAttributeName.CreatedTimestamp, QueueAttributeName.LastModifiedTimestamp, QueueAttributeName.QueueArn, QueueAttributeName.ApproximateNumberOfMessagesDelayed, QueueAttributeName.DelaySeconds, QueueAttributeName.ReceiveMessageWaitTimeSeconds, QueueAttributeName.RedrivePolicy, QueueAttributeName.FifoQueue, QueueAttributeName.ContentBasedDeduplication, QueueAttributeName.KmsMasterKeyId, QueueAttributeName.KmsDataKeyReusePeriodSeconds, QueueAttributeName.DeduplicationScope, QueueAttributeName.FifoThroughputLimit, QueueAttributeName.RedriveAllowPolicy, QueueAttributeName.SqsManagedSseEnabled, QueueAttributeName.Unknown>): aws.sdk.kotlin.services.sqs.model.QueueAttributeName = when (v) {
    is U23_1<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("All")
    is U23_2<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("Policy")
    is U23_3<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("VisibilityTimeout")
    is U23_4<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("MaximumMessageSize")
    is U23_5<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("MessageRetentionPeriod")
    is U23_6<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("ApproximateNumberOfMessages")
    is U23_7<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("ApproximateNumberOfMessagesNotVisible")
    is U23_8<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("CreatedTimestamp")
    is U23_9<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("LastModifiedTimestamp")
    is U23_10<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("QueueArn")
    is U23_11<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("ApproximateNumberOfMessagesDelayed")
    is U23_12<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("DelaySeconds")
    is U23_13<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("ReceiveMessageWaitTimeSeconds")
    is U23_14<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("RedrivePolicy")
    is U23_15<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("FifoQueue")
    is U23_16<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("ContentBasedDeduplication")
    is U23_17<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("KmsMasterKeyId")
    is U23_18<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("KmsDataKeyReusePeriodSeconds")
    is U23_19<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("DeduplicationScope")
    is U23_20<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("FifoThroughputLimit")
    is U23_21<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("RedriveAllowPolicy")
    is U23_22<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue("SqsManagedSseEnabled")
    is U23_23<*, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue((v.value as QueueAttributeName.Unknown).value)
}

private fun fromSdkQueueAttributeName(v: aws.sdk.kotlin.services.sqs.model.QueueAttributeName): Union23<QueueAttributeName.All, QueueAttributeName.Policy, QueueAttributeName.VisibilityTimeout, QueueAttributeName.MaximumMessageSize, QueueAttributeName.MessageRetentionPeriod, QueueAttributeName.ApproximateNumberOfMessages, QueueAttributeName.ApproximateNumberOfMessagesNotVisible, QueueAttributeName.CreatedTimestamp, QueueAttributeName.LastModifiedTimestamp, QueueAttributeName.QueueArn, QueueAttributeName.ApproximateNumberOfMessagesDelayed, QueueAttributeName.DelaySeconds, QueueAttributeName.ReceiveMessageWaitTimeSeconds, QueueAttributeName.RedrivePolicy, QueueAttributeName.FifoQueue, QueueAttributeName.ContentBasedDeduplication, QueueAttributeName.KmsMasterKeyId, QueueAttributeName.KmsDataKeyReusePeriodSeconds, QueueAttributeName.DeduplicationScope, QueueAttributeName.FifoThroughputLimit, QueueAttributeName.RedriveAllowPolicy, QueueAttributeName.SqsManagedSseEnabled, QueueAttributeName.Unknown> = when (v.value) {
    "All" -> U23_1(QueueAttributeName.All())
    "Policy" -> U23_2(QueueAttributeName.Policy())
    "VisibilityTimeout" -> U23_3(QueueAttributeName.VisibilityTimeout())
    "MaximumMessageSize" -> U23_4(QueueAttributeName.MaximumMessageSize())
    "MessageRetentionPeriod" -> U23_5(QueueAttributeName.MessageRetentionPeriod())
    "ApproximateNumberOfMessages" -> U23_6(QueueAttributeName.ApproximateNumberOfMessages())
    "ApproximateNumberOfMessagesNotVisible" -> U23_7(QueueAttributeName.ApproximateNumberOfMessagesNotVisible())
    "CreatedTimestamp" -> U23_8(QueueAttributeName.CreatedTimestamp())
    "LastModifiedTimestamp" -> U23_9(QueueAttributeName.LastModifiedTimestamp())
    "QueueArn" -> U23_10(QueueAttributeName.QueueArn())
    "ApproximateNumberOfMessagesDelayed" -> U23_11(QueueAttributeName.ApproximateNumberOfMessagesDelayed())
    "DelaySeconds" -> U23_12(QueueAttributeName.DelaySeconds())
    "ReceiveMessageWaitTimeSeconds" -> U23_13(QueueAttributeName.ReceiveMessageWaitTimeSeconds())
    "RedrivePolicy" -> U23_14(QueueAttributeName.RedrivePolicy())
    "FifoQueue" -> U23_15(QueueAttributeName.FifoQueue())
    "ContentBasedDeduplication" -> U23_16(QueueAttributeName.ContentBasedDeduplication())
    "KmsMasterKeyId" -> U23_17(QueueAttributeName.KmsMasterKeyId())
    "KmsDataKeyReusePeriodSeconds" -> U23_18(QueueAttributeName.KmsDataKeyReusePeriodSeconds())
    "DeduplicationScope" -> U23_19(QueueAttributeName.DeduplicationScope())
    "FifoThroughputLimit" -> U23_20(QueueAttributeName.FifoThroughputLimit())
    "RedriveAllowPolicy" -> U23_21(QueueAttributeName.RedriveAllowPolicy())
    "SqsManagedSseEnabled" -> U23_22(QueueAttributeName.SqsManagedSseEnabled())
    else -> U23_23(QueueAttributeName.Unknown(v.value))
}

private fun toSdkMessageSystemAttributeName(v: Union11<MessageSystemAttributeName.All, MessageSystemAttributeName.SenderId, MessageSystemAttributeName.SentTimestamp, MessageSystemAttributeName.ApproximateReceiveCount, MessageSystemAttributeName.ApproximateFirstReceiveTimestamp, MessageSystemAttributeName.SequenceNumber, MessageSystemAttributeName.MessageDeduplicationId, MessageSystemAttributeName.MessageGroupId, MessageSystemAttributeName.AwsTraceHeader, MessageSystemAttributeName.DeadLetterQueueSourceArn, MessageSystemAttributeName.Unknown>): aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName = when (v) {
    is U11_1<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue("All")
    is U11_2<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue("SenderId")
    is U11_3<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue("SentTimestamp")
    is U11_4<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue("ApproximateReceiveCount")
    is U11_5<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue("ApproximateFirstReceiveTimestamp")
    is U11_6<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue("SequenceNumber")
    is U11_7<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue("MessageDeduplicationId")
    is U11_8<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue("MessageGroupId")
    is U11_9<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue("AWSTraceHeader")
    is U11_10<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue("DeadLetterQueueSourceArn")
    is U11_11<*, *, *, *, *, *, *, *, *, *, *> -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue((v.value as MessageSystemAttributeName.Unknown).value)
}

private fun fromSdkMessageSystemAttributeName(v: aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName): Union11<MessageSystemAttributeName.All, MessageSystemAttributeName.SenderId, MessageSystemAttributeName.SentTimestamp, MessageSystemAttributeName.ApproximateReceiveCount, MessageSystemAttributeName.ApproximateFirstReceiveTimestamp, MessageSystemAttributeName.SequenceNumber, MessageSystemAttributeName.MessageDeduplicationId, MessageSystemAttributeName.MessageGroupId, MessageSystemAttributeName.AwsTraceHeader, MessageSystemAttributeName.DeadLetterQueueSourceArn, MessageSystemAttributeName.Unknown> = when (v.value) {
    "All" -> U11_1(MessageSystemAttributeName.All())
    "SenderId" -> U11_2(MessageSystemAttributeName.SenderId())
    "SentTimestamp" -> U11_3(MessageSystemAttributeName.SentTimestamp())
    "ApproximateReceiveCount" -> U11_4(MessageSystemAttributeName.ApproximateReceiveCount())
    "ApproximateFirstReceiveTimestamp" -> U11_5(MessageSystemAttributeName.ApproximateFirstReceiveTimestamp())
    "SequenceNumber" -> U11_6(MessageSystemAttributeName.SequenceNumber())
    "MessageDeduplicationId" -> U11_7(MessageSystemAttributeName.MessageDeduplicationId())
    "MessageGroupId" -> U11_8(MessageSystemAttributeName.MessageGroupId())
    "AWSTraceHeader" -> U11_9(MessageSystemAttributeName.AwsTraceHeader())
    "DeadLetterQueueSourceArn" -> U11_10(MessageSystemAttributeName.DeadLetterQueueSourceArn())
    else -> U11_11(MessageSystemAttributeName.Unknown(v.value))
}

private fun toSdkCreateQueueInput(v: CreateQueueInput): aws.sdk.kotlin.services.sqs.model.CreateQueueRequest = aws.sdk.kotlin.services.sqs.model.CreateQueueRequest {
    queueName = v.queue_name
    attributes = v.attributes?.let { it.entries.associate { (k1, v1) -> aws.sdk.kotlin.services.sqs.model.QueueAttributeName.fromValue(k1) to v1 } }
    tags = v.tags?.let { it.entries.associate { (k1, v1) -> k1 to v1 } }
}

private fun fromSdkCreateQueueOutput(v: aws.sdk.kotlin.services.sqs.model.CreateQueueResponse): CreateQueueOutput = CreateQueueOutput(
    queue_url = v.queueUrl,
)

private fun toSdkGetQueueUrlInput(v: GetQueueUrlInput): aws.sdk.kotlin.services.sqs.model.GetQueueUrlRequest = aws.sdk.kotlin.services.sqs.model.GetQueueUrlRequest {
    queueName = v.queue_name
    queueOwnerAwsAccountId = v.queue_owner_aws_account_id
}

private fun fromSdkGetQueueUrlOutput(v: aws.sdk.kotlin.services.sqs.model.GetQueueUrlResponse): GetQueueUrlOutput = GetQueueUrlOutput(
    queue_url = v.queueUrl,
)

private fun toSdkSendMessageInput(v: SendMessageInput): aws.sdk.kotlin.services.sqs.model.SendMessageRequest = aws.sdk.kotlin.services.sqs.model.SendMessageRequest {
    queueUrl = v.queue_url
    messageBody = v.message_body
    delaySeconds = v.delay_seconds
    messageAttributes = v.message_attributes?.let { it.entries.associate { (k1, v1) -> k1 to toSdkMessageAttributeValue(v1) } }
    messageSystemAttributes = v.message_system_attributes?.let { it.entries.associate { (k1, v1) -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeNameForSends.fromValue(k1) to toSdkMessageSystemAttributeValue(v1) } }
    messageDeduplicationId = v.message_deduplication_id
    messageGroupId = v.message_group_id
}

private fun fromSdkMessageAttributeValue(v: aws.sdk.kotlin.services.sqs.model.MessageAttributeValue): MessageAttributeValue = MessageAttributeValue(
    string_value = v.stringValue,
    binary_value = v.binaryValue?.let { salvo.SalvoBytes(it) },
    string_list_values = v.stringListValues?.let { it.map { e1 -> e1 } },
    binary_list_values = v.binaryListValues?.let { it.map { e1 -> salvo.SalvoBytes(e1) } },
    data_type = (v.dataType ?: error("missing required member DataType")),
)

private fun toSdkMessageAttributeValue(v: MessageAttributeValue): aws.sdk.kotlin.services.sqs.model.MessageAttributeValue = aws.sdk.kotlin.services.sqs.model.MessageAttributeValue {
    stringValue = v.string_value
    binaryValue = v.binary_value?.let { it.toByteArray() }
    stringListValues = v.string_list_values?.let { it.map { e1 -> e1 } }
    binaryListValues = v.binary_list_values?.let { it.map { e1 -> e1.toByteArray() } }
    dataType = v.data_type
}

private fun fromSdkMessageSystemAttributeValue(v: aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeValue): MessageSystemAttributeValue = MessageSystemAttributeValue(
    string_value = v.stringValue,
    binary_value = v.binaryValue?.let { salvo.SalvoBytes(it) },
    string_list_values = v.stringListValues?.let { it.map { e1 -> e1 } },
    binary_list_values = v.binaryListValues?.let { it.map { e1 -> salvo.SalvoBytes(e1) } },
    data_type = (v.dataType ?: error("missing required member DataType")),
)

private fun toSdkMessageSystemAttributeValue(v: MessageSystemAttributeValue): aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeValue = aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeValue {
    stringValue = v.string_value
    binaryValue = v.binary_value?.let { it.toByteArray() }
    stringListValues = v.string_list_values?.let { it.map { e1 -> e1 } }
    binaryListValues = v.binary_list_values?.let { it.map { e1 -> e1.toByteArray() } }
    dataType = v.data_type
}

private fun fromSdkSendMessageOutput(v: aws.sdk.kotlin.services.sqs.model.SendMessageResponse): SendMessageOutput = SendMessageOutput(
    md5_of_message_body = v.md5OfMessageBody,
    md5_of_message_attributes = v.md5OfMessageAttributes,
    md5_of_message_system_attributes = v.md5OfMessageSystemAttributes,
    message_id = v.messageId,
    sequence_number = v.sequenceNumber,
)

private fun toSdkReceiveMessageInput(v: ReceiveMessageInput): aws.sdk.kotlin.services.sqs.model.ReceiveMessageRequest = aws.sdk.kotlin.services.sqs.model.ReceiveMessageRequest {
    queueUrl = v.queue_url
    attributeNames = v.attribute_names?.let { it.map { e1 -> toSdkQueueAttributeName(e1) } }
    messageSystemAttributeNames = v.message_system_attribute_names?.let { it.map { e1 -> toSdkMessageSystemAttributeName(e1) } }
    messageAttributeNames = v.message_attribute_names?.let { it.map { e1 -> e1 } }
    maxNumberOfMessages = v.max_number_of_messages
    visibilityTimeout = v.visibility_timeout
    waitTimeSeconds = v.wait_time_seconds
    receiveRequestAttemptId = v.receive_request_attempt_id
}

private fun fromSdkReceiveMessageOutput(v: aws.sdk.kotlin.services.sqs.model.ReceiveMessageResponse): ReceiveMessageOutput = ReceiveMessageOutput(
    messages = v.messages?.let { it.map { e1 -> fromSdkMessage(e1) } },
)

private fun fromSdkMessage(v: aws.sdk.kotlin.services.sqs.model.Message): Message = Message(
    message_id = v.messageId,
    receipt_handle = v.receiptHandle,
    md5_of_body = v.md5OfBody,
    body = v.body,
    attributes = v.attributes?.let { it.entries.sortedBy { it.key.value }.associate { (k1, v1) -> k1.value to v1 } },
    md5_of_message_attributes = v.md5OfMessageAttributes,
    message_attributes = v.messageAttributes?.let { it.entries.sortedBy { it.key }.associate { (k1, v1) -> k1 to fromSdkMessageAttributeValue(v1) } },
)

private fun toSdkMessage(v: Message): aws.sdk.kotlin.services.sqs.model.Message = aws.sdk.kotlin.services.sqs.model.Message {
    messageId = v.message_id
    receiptHandle = v.receipt_handle
    md5OfBody = v.md5_of_body
    body = v.body
    attributes = v.attributes?.let { it.entries.associate { (k1, v1) -> aws.sdk.kotlin.services.sqs.model.MessageSystemAttributeName.fromValue(k1) to v1 } }
    md5OfMessageAttributes = v.md5_of_message_attributes
    messageAttributes = v.message_attributes?.let { it.entries.associate { (k1, v1) -> k1 to toSdkMessageAttributeValue(v1) } }
}

private fun toSdkDeleteMessageInput(v: DeleteMessageInput): aws.sdk.kotlin.services.sqs.model.DeleteMessageRequest = aws.sdk.kotlin.services.sqs.model.DeleteMessageRequest {
    queueUrl = v.queue_url
    receiptHandle = v.receipt_handle
}

private fun toSdkDeleteQueueInput(v: DeleteQueueInput): aws.sdk.kotlin.services.sqs.model.DeleteQueueRequest = aws.sdk.kotlin.services.sqs.model.DeleteQueueRequest {
    queueUrl = v.queue_url
}

private fun fromSdkInvalidAddress(v: aws.sdk.kotlin.services.sqs.model.InvalidAddress): InvalidAddress = InvalidAddress(
    message = v.message,
)

private fun fromSdkInvalidAttributeName(v: aws.sdk.kotlin.services.sqs.model.InvalidAttributeName): InvalidAttributeName = InvalidAttributeName(
    message = v.message,
)

private fun fromSdkInvalidAttributeValue(v: aws.sdk.kotlin.services.sqs.model.InvalidAttributeValue): InvalidAttributeValue = InvalidAttributeValue(
    message = v.message,
)

private fun fromSdkInvalidIdFormat(v: aws.sdk.kotlin.services.sqs.model.InvalidIdFormat): InvalidIdFormat = InvalidIdFormat()

private fun fromSdkInvalidMessageContents(v: aws.sdk.kotlin.services.sqs.model.InvalidMessageContents): InvalidMessageContents = InvalidMessageContents(
    message = v.message,
)

private fun fromSdkInvalidSecurity(v: aws.sdk.kotlin.services.sqs.model.InvalidSecurity): InvalidSecurity = InvalidSecurity(
    message = v.message,
)

private fun fromSdkKmsAccessDenied(v: aws.sdk.kotlin.services.sqs.model.KmsAccessDenied): KmsAccessDenied = KmsAccessDenied(
    message = v.message,
)

private fun fromSdkKmsDisabled(v: aws.sdk.kotlin.services.sqs.model.KmsDisabled): KmsDisabled = KmsDisabled(
    message = v.message,
)

private fun fromSdkKmsInvalidKeyUsage(v: aws.sdk.kotlin.services.sqs.model.KmsInvalidKeyUsage): KmsInvalidKeyUsage = KmsInvalidKeyUsage(
    message = v.message,
)

private fun fromSdkKmsInvalidState(v: aws.sdk.kotlin.services.sqs.model.KmsInvalidState): KmsInvalidState = KmsInvalidState(
    message = v.message,
)

private fun fromSdkKmsNotFound(v: aws.sdk.kotlin.services.sqs.model.KmsNotFound): KmsNotFound = KmsNotFound(
    message = v.message,
)

private fun fromSdkKmsOptInRequired(v: aws.sdk.kotlin.services.sqs.model.KmsOptInRequired): KmsOptInRequired = KmsOptInRequired(
    message = v.message,
)

private fun fromSdkKmsThrottled(v: aws.sdk.kotlin.services.sqs.model.KmsThrottled): KmsThrottled = KmsThrottled(
    message = v.message,
)

private fun fromSdkOverLimit(v: aws.sdk.kotlin.services.sqs.model.OverLimit): OverLimit = OverLimit(
    message = v.message,
)

private fun fromSdkQueueDeletedRecently(v: aws.sdk.kotlin.services.sqs.model.QueueDeletedRecently): QueueDeletedRecently = QueueDeletedRecently(
    message = v.message,
)

private fun fromSdkQueueDoesNotExist(v: aws.sdk.kotlin.services.sqs.model.QueueDoesNotExist): QueueDoesNotExist = QueueDoesNotExist(
    message = v.message,
)

private fun fromSdkQueueNameExists(v: aws.sdk.kotlin.services.sqs.model.QueueNameExists): QueueNameExists = QueueNameExists(
    message = v.message,
)

private fun fromSdkReceiptHandleIsInvalid(v: aws.sdk.kotlin.services.sqs.model.ReceiptHandleIsInvalid): ReceiptHandleIsInvalid = ReceiptHandleIsInvalid(
    message = v.message,
)

private fun fromSdkRequestThrottled(v: aws.sdk.kotlin.services.sqs.model.RequestThrottled): RequestThrottled = RequestThrottled(
    message = v.message,
)

private fun fromSdkUnsupportedOperation(v: aws.sdk.kotlin.services.sqs.model.UnsupportedOperation): UnsupportedOperation = UnsupportedOperation(
    message = v.message,
)

private fun salvoAwsError(e: Throwable): AwsError {
    val code = (e as? aws.smithy.kotlin.runtime.ServiceException)?.sdkErrorMetadata?.errorCode
        ?: e::class.simpleName ?: "Exception"
    return AwsError(code = code, message = e.message ?: e.toString())
}
