// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 023a4214a13ba612
use crate::core_bytes::*;
use crate::core_iterator::*;
use crate::core_list::*;
use crate::core_map::*;
use crate::core_set::*;
use crate::core_sorted::*;
use crate::core_string::*;
use crate::unions::*;

pub fn iter__3<T: Clone>(d: &std::collections::VecDeque<T>) -> DequeYield<'_, T> {
    return DequeYield { items: d, at: 0 };
}

#[derive(Clone, Debug, PartialEq)]
pub struct DequeYield<'s, T: Clone> {
    pub items: &'s std::collections::VecDeque<T>,
    pub at: i32,
}

pub fn next__3<'s, T: Clone>(p: &mut DequeYield<'s, T>) -> Union2<&'s T, Finished> {
    let mut elem = p.items.get((p.at) as i64 as usize);
    if elem.is_none() {
        return Union2::U2(finished());
    }
    p.at = p.at + 1;
    return Union2::U1(emitted(elem.unwrap()));
}

#[derive(Clone, Debug, PartialEq)]
pub struct __Iter_reversed_Deque<'s, T: Clone> {
    pub d: &'s std::collections::VecDeque<T>,
    pub at: i32,
}

pub fn reversed<T: Clone>(d: &std::collections::VecDeque<T>) -> __Iter_reversed_Deque<'_, T> {
    return __Iter_reversed_Deque { d: d, at: (d.len() as i32) - 1 };
}

pub fn next__4<'s, T: Clone>(__p: &mut __Iter_reversed_Deque<'s, T>) -> Union2<&'s T, Finished> {
    let mut elem = __p.d.get((__p.at) as i64 as usize);
    if elem.is_none() {
        return Union2::U2(finished());
    }
    __p.at = __p.at - 1;
    return Union2::U1(emitted(elem.unwrap()));
}
