// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 023a4214a13ba612
use crate::core_map::MapKeyYield;
use crate::core_set::SetYield;
use crate::core_string::append_platform;
use crate::core_string::mut_str;


/// [platform-type] The host's `SortedSet`.
pub use crate::platform_core_sorted::SortedSet;
const _: fn() = || { fn __contract<T: Send + 'static + Clone + std::fmt::Debug + PartialEq + Eq>() {} __contract::<SortedSet<i32>>(); };
const _: fn() = || { fn __each(x: &SortedSet<i32>) -> impl Iterator<Item = i32> + '_ { crate::platform_core_sorted::each_sorted_set(x).map(|e| e.clone()) } let _ = __each; };
const _: fn() = || { fn __each_ref(x: &SortedSet<i32>) -> impl Iterator<Item = &i32> + '_ { crate::platform_core_sorted::each_sorted_set(x) } fn __each_mut(x: &mut SortedSet<i32>) -> impl Iterator<Item = &mut i32> + '_ { crate::platform_core_sorted::each_sorted_set_mut(x) } fn __into_each(x: SortedSet<i32>) -> impl Iterator<Item = i32> { crate::platform_core_sorted::into_each_sorted_set(x) } let _ = (__each_ref, __each_mut, __into_each); };

pub fn sorted_set_of_platform<T: Clone>(mut elems: Vec<T>, cmp: &mut dyn FnMut(&T, &T) -> i32) -> crate::core_sorted::SortedSet<T> {
    let mut cmp = cmp;
    crate::platform_core_sorted::sorted_set_of(elems, &mut cmp)
}

pub fn mut_sorted_set_of_platform<T: Clone>(mut elems: Vec<T>, cmp: &mut dyn FnMut(&T, &T) -> i32) -> crate::core_sorted::SortedSet<T> {
    let mut cmp = cmp;
    crate::platform_core_sorted::mut_sorted_set_of(elems, &mut cmp)
}

pub fn add_platform<T: Clone>(set: &mut crate::core_sorted::SortedSet<T>, mut elem: T, cmp: &mut dyn FnMut(&T, &T) -> i32) -> bool {
    let mut cmp = cmp;
    crate::platform_core_sorted::add(set, elem, &mut cmp)
}

pub fn remove__SortedSet_T<T: Clone>(set: &mut crate::core_sorted::SortedSet<T>, elem: &T, cmp: &mut dyn FnMut(&T, &T) -> i32) -> bool {
    return crate::core_sorted::remove_elem_platform::<T>(&mut *set, elem, &mut *cmp);
}

pub fn remove_elem_platform<T: Clone>(set: &mut crate::core_sorted::SortedSet<T>, elem: &T, cmp: &mut dyn FnMut(&T, &T) -> i32) -> bool {
    let mut cmp = cmp;
    crate::platform_core_sorted::remove_elem(set, elem, &mut cmp)
}

pub fn set_size_platform<T: Clone>(set: &crate::core_sorted::SortedSet<T>) -> i32 {
    crate::platform_core_sorted::set_size(set)
}

pub fn remove_key_platform<K: Clone, V: Clone>(map: &mut crate::core_sorted::SortedMap<K, V>, key: &K, cmp: &mut dyn FnMut(&K, &K) -> i32) -> Option<V> {
    let mut cmp = cmp;
    crate::platform_core_sorted::remove_key(map, key, &mut cmp)
}

pub fn map_size_platform<K: Clone, V: Clone>(map: &crate::core_sorted::SortedMap<K, V>) -> i32 {
    crate::platform_core_sorted::map_size(map)
}

pub fn contains_platform<T: Clone>(set: &crate::core_sorted::SortedSet<T>, elem: &T, cmp: &mut dyn FnMut(&T, &T) -> i32) -> bool {
    let mut cmp = cmp;
    crate::platform_core_sorted::contains(set, elem, &mut cmp)
}

pub fn size__SortedSet<T: Clone>(set: &crate::core_sorted::SortedSet<T>) -> i32 {
    return crate::core_sorted::set_size_platform::<T>(set);
}

pub fn min_platform<T: Clone>(set: &crate::core_sorted::SortedSet<T>) -> Option<T> {
    crate::platform_core_sorted::min(set)
}

pub fn max_platform<T: Clone>(set: &crate::core_sorted::SortedSet<T>) -> Option<T> {
    crate::platform_core_sorted::max(set)
}

pub fn to_list_platform<T: Clone>(set: &crate::core_sorted::SortedSet<T>) -> Vec<T> {
    crate::platform_core_sorted::to_list(set)
}

pub fn to_str__SortedSet<T: Clone>(set: &crate::core_sorted::SortedSet<T>, to_str: &mut dyn FnMut(&T) -> String) -> String {
    let mut out: String = crate::core_string::mut_str(vec![String::from("{")]);
    let mut i: i32 = 0i32;
    for mut x in crate::platform_core_sorted::each_sorted_set(set).map(|__x| __x.clone()) {
        if (i > 0i32) {
            crate::core_string::append_platform(&mut out, &String::from(", "));
        };
        crate::core_string::append_platform(&mut out, &to_str(&x));
        i = i32::wrapping_add(i, 1i32);
    }
    crate::core_string::append_platform(&mut out, &String::from("}"));
    return out;
}

pub fn iter__SortedSet<T: Clone>(set: &crate::core_sorted::SortedSet<T>) -> crate::core_set::SetYield<T> {
    return crate::core_set::SetYield { items: crate::core_sorted::to_list_platform::<T>(set), at: 0i32 };
}

/// [platform-type] The host's `SortedMap`.
pub use crate::platform_core_sorted::SortedMap;
const _: fn() = || { fn __contract<T: Send + 'static + Clone + std::fmt::Debug + PartialEq + Eq>() {} __contract::<SortedMap<i32, i32>>(); };
const _: fn() = || { fn __each(x: &SortedMap<i32, i32>) -> impl Iterator<Item = i32> + '_ { crate::platform_core_sorted::each_sorted_map(x).map(|e| e.clone()) } let _ = __each; };
const _: fn() = || { fn __each_ref(x: &SortedMap<i32, i32>) -> impl Iterator<Item = &i32> + '_ { crate::platform_core_sorted::each_sorted_map(x) } fn __each_mut(x: &mut SortedMap<i32, i32>) -> impl Iterator<Item = &mut i32> + '_ { crate::platform_core_sorted::each_sorted_map_mut(x) } fn __into_each(x: SortedMap<i32, i32>) -> impl Iterator<Item = i32> { crate::platform_core_sorted::into_each_sorted_map(x) } let _ = (__each_ref, __each_mut, __into_each); };

pub fn sorted_map_of_platform<K: Clone, V: Clone>(mut entries: Vec<(K, V)>, cmp: &mut dyn FnMut(&K, &K) -> i32) -> crate::core_sorted::SortedMap<K, V> {
    let mut cmp = cmp;
    crate::platform_core_sorted::sorted_map_of(entries, &mut cmp)
}

pub fn mut_sorted_map_of_platform<K: Clone, V: Clone>(mut entries: Vec<(K, V)>, cmp: &mut dyn FnMut(&K, &K) -> i32) -> crate::core_sorted::SortedMap<K, V> {
    let mut cmp = cmp;
    crate::platform_core_sorted::mut_sorted_map_of(entries, &mut cmp)
}

pub fn get_platform<'a, K: Clone, V: Clone>(map: &'a crate::core_sorted::SortedMap<K, V>, key: &K, cmp: &mut dyn FnMut(&K, &K) -> i32) -> Option<&'a V> {
    let mut cmp = cmp;
    crate::platform_core_sorted::get(map, key, &mut cmp)
}

pub fn put_platform<K: Clone, V: Clone>(map: &mut crate::core_sorted::SortedMap<K, V>, mut key: K, mut value: V, cmp: &mut dyn FnMut(&K, &K) -> i32) {
    let mut cmp = cmp;
    crate::platform_core_sorted::put(map, key, value, &mut cmp)
}

pub fn remove__SortedMap_K<K: Clone, V: Clone>(map: &mut crate::core_sorted::SortedMap<K, V>, key: &K, cmp: &mut dyn FnMut(&K, &K) -> i32) -> Option<V> {
    return crate::core_sorted::remove_key_platform::<K, V>(&mut *map, key, &mut *cmp);
}

pub fn contains_key_platform<K: Clone, V: Clone>(map: &crate::core_sorted::SortedMap<K, V>, key: &K, cmp: &mut dyn FnMut(&K, &K) -> i32) -> bool {
    let mut cmp = cmp;
    crate::platform_core_sorted::contains_key(map, key, &mut cmp)
}

pub fn size__SortedMap<K: Clone, V: Clone>(map: &crate::core_sorted::SortedMap<K, V>) -> i32 {
    return crate::core_sorted::map_size_platform::<K, V>(map);
}

pub fn first_key_platform<K: Clone, V: Clone>(map: &crate::core_sorted::SortedMap<K, V>) -> Option<K> {
    crate::platform_core_sorted::first_key(map)
}

pub fn last_key_platform<K: Clone, V: Clone>(map: &crate::core_sorted::SortedMap<K, V>) -> Option<K> {
    crate::platform_core_sorted::last_key(map)
}

pub fn keys_platform<K: Clone, V: Clone>(map: &crate::core_sorted::SortedMap<K, V>) -> Vec<K> {
    crate::platform_core_sorted::keys(map)
}

pub fn to_str__SortedMap<K: Clone, V: Clone>(map: &crate::core_sorted::SortedMap<K, V>, to_str: &mut dyn FnMut(&K) -> String, to_str__1: &mut dyn FnMut(&V) -> String, cmp: &mut dyn FnMut(&K, &K) -> i32) -> String {
    let mut out: String = crate::core_string::mut_str(vec![String::from("{")]);
    let mut i: i32 = 0i32;
    for mut k in crate::platform_core_sorted::each_sorted_map(map).map(|__x| __x.clone()) {
        if (i > 0i32) {
            crate::core_string::append_platform(&mut out, &String::from(", "));
        };
        crate::core_string::append_platform(&mut out, &to_str(&k));
        crate::core_string::append_platform(&mut out, &String::from(": "));
        crate::core_string::append_platform(&mut out, &to_str__1({
            let mut __nn_1: Option<&V> = crate::core_sorted::get_platform::<K, V>(map, &k, &mut *cmp);
            if __nn_1.is_none() {
                panic!("salvo: value is absent at core.sorted:148:28");
            } else {
                let mut __some_2 = __nn_1.unwrap();
                __some_2
            }
        }));
        i = i32::wrapping_add(i, 1i32);
    }
    crate::core_string::append_platform(&mut out, &String::from("}"));
    return out;
}

pub fn eq__SortedSet_SortedSet<T: Clone>(a: &crate::core_sorted::SortedSet<T>, b: &crate::core_sorted::SortedSet<T>, cmp: &mut dyn FnMut(&T, &T) -> i32) -> bool {
    if !(((crate::core_sorted::size__SortedSet::<T>(a)) == (crate::core_sorted::size__SortedSet::<T>(b)))) {
        return false;
    };
    for mut x in crate::platform_core_sorted::each_sorted_set(a).map(|__x| __x.clone()) {
        if !(crate::core_sorted::contains_platform::<T>(b, &x, &mut *cmp)) {
            return false;
        };
    }
    return true;
}

pub fn eq__SortedMap_SortedMap<K: Clone, V: Clone>(a: &crate::core_sorted::SortedMap<K, V>, b: &crate::core_sorted::SortedMap<K, V>, eq: &mut dyn FnMut(&V, &V) -> bool, cmp: &mut dyn FnMut(&K, &K) -> i32) -> bool {
    if !(((crate::core_sorted::size__SortedMap::<K, V>(a)) == (crate::core_sorted::size__SortedMap::<K, V>(b)))) {
        return false;
    };
    for mut k in crate::platform_core_sorted::each_sorted_map(a).map(|__x| __x.clone()) {
        let mut theirs: Option<&V> = crate::core_sorted::get_platform::<K, V>(b, &k, &mut *cmp);
        if theirs.is_none() {
            return false;
        };
        let mut theirs_3 = theirs.unwrap();
        if !(eq({
            let mut __nn_1: Option<&V> = crate::core_sorted::get_platform::<K, V>(a, &k, &mut *cmp);
            if __nn_1.is_none() {
                panic!("salvo: value is absent at core.sorted:181:16");
            } else {
                let mut __some_2 = __nn_1.unwrap();
                __some_2
            }
        }, theirs_3)) {
            return false;
        };
    }
    return true;
}

pub fn iter__SortedMap<K: Clone, V: Clone>(map: &crate::core_sorted::SortedMap<K, V>) -> crate::core_map::MapKeyYield<K> {
    return crate::core_map::MapKeyYield { items: crate::core_sorted::keys_platform::<K, V>(map), at: 0i32 };
}

pub fn NonEmpty__SortedSet_qualifies<T: Clone>(set: &crate::core_sorted::SortedSet<T>) -> bool {
    return (crate::core_sorted::size__SortedSet::<T>(set) > 0i32);
}

pub fn NonEmpty__SortedMap_qualifies<K: Clone, V: Clone>(map: &crate::core_sorted::SortedMap<K, V>) -> bool {
    return (crate::core_sorted::size__SortedMap::<K, V>(map) > 0i32);
}

pub fn min<T: Clone>(set: &crate::core_sorted::SortedSet<T>) -> T {
    return {
        let mut __nn_1: Option<T> = crate::core_sorted::min_platform::<T>(set);
        if __nn_1.is_none() {
            panic!("salvo: value is absent at core.sorted:236:12");
        } else {
            let mut __some_2 = __nn_1.unwrap();
            __some_2
        }
    };
}

pub fn max<T: Clone>(set: &crate::core_sorted::SortedSet<T>) -> T {
    return {
        let mut __nn_1: Option<T> = crate::core_sorted::max_platform::<T>(set);
        if __nn_1.is_none() {
            panic!("salvo: value is absent at core.sorted:240:12");
        } else {
            let mut __some_2 = __nn_1.unwrap();
            __some_2
        }
    };
}

pub fn first_key<K: Clone, V: Clone>(map: &crate::core_sorted::SortedMap<K, V>) -> K {
    return {
        let mut __nn_1: Option<K> = crate::core_sorted::first_key_platform::<K, V>(map);
        if __nn_1.is_none() {
            panic!("salvo: value is absent at core.sorted:244:12");
        } else {
            let mut __some_2 = __nn_1.unwrap();
            __some_2
        }
    };
}

pub fn last_key<K: Clone, V: Clone>(map: &crate::core_sorted::SortedMap<K, V>) -> K {
    return {
        let mut __nn_1: Option<K> = crate::core_sorted::last_key_platform::<K, V>(map);
        if __nn_1.is_none() {
            panic!("salvo: value is absent at core.sorted:248:12");
        } else {
            let mut __some_2 = __nn_1.unwrap();
            __some_2
        }
    };
}
