//! Emission helpers both backends share (ROADMAP §0j step 3): syntax
//! walkers, type-name helpers and generated-name policies that were
//! duplicated byte for byte in the two emitters. Backend-neutral by rule:
//! nothing here may cite a backend-prefixed label (AGENTS.md).


use salvo_syntax::ast::*;

/// One generated file: a path relative to the target directory and its
/// content.
#[derive(Debug, Clone)]
pub struct EmittedFile {
    pub rel_path: std::path::PathBuf,
    pub content: String,
}

/// [backend-companion] Two emitted files with one path is a **clobber**: the
/// second write wins and the first module's code silently vanishes. It has
/// happened twice — a runtime file and a std module of the same name — so the
/// assembly refuses rather than overwriting [backend-never-wrong]. Renaming the
/// runtime file is the fix each time (`hosttime`, `throwsignal`); the durable
/// one is a namespace for the runtime, recorded in ROADMAP.
pub fn no_duplicate_paths(files: &[EmittedFile]) -> Result<(), Vec<String>> {
    let mut seen: std::collections::HashMap<&std::path::Path, usize> =
        std::collections::HashMap::new();
    for f in files {
        *seen.entry(f.rel_path.as_path()).or_default() += 1;
    }
    let mut clashes: Vec<String> = seen
        .into_iter()
        .filter(|(_, n)| *n > 1)
        .map(|(path, n)| {
            format!(
                "two emitted files claim `{}` ({n} of them): a module's path and a \
                 runtime file collide, so one would silently overwrite the other — \
                 rename the runtime file [backend-companion]",
                path.display()
            )
        })
        .collect();
    if clashes.is_empty() {
        Ok(())
    } else {
        clashes.sort();
        Err(clashes)
    }
}


/// [platform-abi] The name an item is kept by in ABI mode.
pub fn abi_item_name(item: &Item) -> Option<&str> {
    match item {
        Item::Struct(s) => Some(&s.name.name),
        Item::Type(t) if t.alias.is_some() => Some(&t.name.name),
        Item::Effect(e) => Some(&e.name.name),
        _ => None,
    }
}


pub use salvo_core::naming::msg_variant_name;


/// Does this module contain anything that turns into Rust code?
pub fn module_produces_code(module: &Module) -> bool {
    module.items.iter().any(|item| match item {
        Item::Struct(s) => !s.comptime,
        Item::Effect(_) => true,
        Item::Handler(_) => true,
        Item::Fn(f) => f.body.is_some() || f.platform,
        Item::Qualifier(q) => q.fns.iter().any(|f| f.body.is_some()),
        _ => false,
    })
}


pub fn type_base_name(ty: &Type) -> Option<&str> {
    match ty {
        Type::Named { base, .. } => Some(base.name.name.as_str()),
        Type::Nullable { inner, .. } => type_base_name(inner),
        Type::QualifiedGroup { base, .. } => type_base_name(base),
        Type::Array { .. } => Some("[]"),
        // [col-hashed-ordered] A tuple receiver, for the interim structural
        // `cmp`/`eq`/`hash` intrinsics over tuples.
        Type::Tuple { .. } => Some("()"),
        _ => None,
    }
}



pub fn is_none_type(ty: &Type) -> bool {
    matches!(ty, Type::Named { qualifiers, base } if qualifiers.is_empty() && base.name.name == "None")
}












/// Writes emitted files under `target_dir`, creating directories, and
/// answers their relative paths: the body of every backend's
/// `Backend::emit` (ROADMAP §0j step 3).
pub fn write_emitted(
    target_dir: &std::path::Path,
    files: Vec<EmittedFile>,
) -> std::io::Result<Vec<std::path::PathBuf>> {
    let mut written = Vec::with_capacity(files.len());
    for file in files {
        let path = target_dir.join(&file.rel_path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, &file.content)?;
        written.push(file.rel_path);
    }
    Ok(written)
}

/// [platform-abi] The first lines of every generated file of a platform
/// root, in a backend whose line comment is `//`: never edited, never read
/// by the build.
pub const ABI_HEADER: &str = "// GENERATED by salvo for the host project of this platform root [platform-abi]:\n\
    // the declarations the platform code uses, as the build emits them. Rewritten\n\
    // by every build — do not edit; the build never reads this file.";

/// [platform-abi] [platform-stamp] The program's ABI stamp, and `files`
/// with [`ABI_HEADER`] and the stamp prefixed to each — what a consumer
/// compares before building the root.
pub fn stamp_abi_files(
    program: &salvo_core::Program,
    files: Vec<EmittedFile>,
) -> (String, Vec<(std::path::PathBuf, String)>) {
    let symbols = salvo_core::Symbols::collect(program);
    let stamp = salvo_core::abi::abi_stamp(program, &symbols, None).unwrap_or_default();
    let out = files
        .into_iter()
        .map(|f| (f.rel_path, format!("{ABI_HEADER}\n// {stamp}\n{}", f.content)))
        .collect();
    (stamp, out)
}

/// Removes `path` if it is a file *we* wrote, recognised by its first
/// line(s) being `header`: how a manifest a previous build generated is
/// retired without touching a hand-written one.
pub fn remove_if_ours(path: &std::path::Path, header: &str) -> std::io::Result<()> {
    if std::fs::read_to_string(path).is_ok_and(|text| text.starts_with(header)) {
        std::fs::remove_file(path)?;
    }
    Ok(())
}

/// Skeleton files as `(path, content)` pairs, the shape
/// `Backend::platform_skeletons` answers.
pub fn as_pairs(files: Vec<EmittedFile>) -> Vec<(std::path::PathBuf, String)> {
    files.into_iter().map(|f| (f.rel_path, f.content)).collect()
}

/// [platform-abi] Whether `module` is the project's own (not std, not a
/// dependency): its implementation file is mounted in a host project, where
/// a std or dependency module's host file is carried as a copy.
pub fn is_project_module(program: &salvo_core::Program, module: &salvo_core::ModulePath) -> bool {
    program
        .units()
        .any(|u| u.file.module == *module && (!u.file.is_std || u.file.is_shadow) && u.file.dependency.is_none())
}



/// [platform-abi] Whether a module's item is emitted: everything outside an
/// ABI build, and in one only the platform declarations and the reached names.
pub fn abi_emits(item: &Item, keep: Option<&std::collections::BTreeSet<String>>) -> bool {
    let Some(keep) = keep else { return true };
    let platform = matches!(item, Item::Handler(h) if h.platform)
        || matches!(item, Item::Fn(f) if f.platform)
        || matches!(item, Item::Type(t) if t.platform);
    platform || abi_item_name(item).is_some_and(|n| keep.contains(n))
}
