// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 023a4214a13ba612
// Generated by the Salvo compiler: host code's entry points into the stream
// table [stream-table].
//
// The table itself is Salvo — the runtime service `runtime.streams`, which
// `stream.host`'s `HostRawStreams` reads — and this file is what host code
// calls: a file `HostRawFs` opened, a body a network client received, a
// request body an SDK uploads. Shipped wherever that service is. The mirror
// of the Rust backend's `hoststreams.rs`.
package salvo

/** [stream-table] A failure recorded against a stream, in host terms. */
sealed class SalvoFault {
    object Utf8 : SalvoFault()

    class Failed(val message: String) : SalvoFault()
}

class SalvoFaultException(val fault: SalvoFault) : Exception()

/** [stream-table] A readable stream host code took out of the table: what was read ahead, then the host stream. */
class SalvoIn(val source: String, val input: java.io.InputStream, var position: Long, var failed: SalvoFault?) {
    /** Up to [max] bytes; empty at the end. Throws [SalvoFaultException] on a failure. */
    fun readUpTo(max: Int): ByteArray {
        failed?.let { throw SalvoFaultException(it) }
        if (max <= 0) return ByteArray(0)
        val scratch = ByteArray(max)
        val n =
            try {
                input.read(scratch, 0, max)
            } catch (e: Exception) {
                val f = SalvoFault.Failed(e.message ?: e.toString())
                failed = f
                throw SalvoFaultException(f)
            }
        if (n <= 0) return ByteArray(0)
        position += n.toLong()
        return scratch.copyOf(n)
    }

    fun closeInput() {
        try {
            input.close()
        } catch (e: Exception) {
        }
    }
}

object SalvoStreams {
    /** [stream-handle] A handle for a new stream, unique in the process. */
    fun freshHandle(): Long = salvo.runtime.streams.freshHandle()

    /** [stream-table] Registers a readable stream, answering its handle. */
    fun registerIn(source: String, input: java.io.InputStream, position: Long): Long =
        salvo.runtime.streams.registerIn(source, salvo.platform.runtime.streams.HostIn(input), position)

    /** [stream-table] Registers a writable stream, answering its handle. */
    fun registerOut(source: String, output: java.io.OutputStream, position: Long): Long =
        salvo.runtime.streams.registerOut(source, salvo.platform.runtime.streams.HostOut(output), position)

    /** [stream-table] Takes the readable stream [handle] out of the table for host code to read. */
    fun takeIn(handle: Long): SalvoIn {
        val e = salvo.runtime.streams.takeForHost(handle)
        val f = e.failed
        val failed = if (f == null) null else if (f.utf8) SalvoFault.Utf8 else SalvoFault.Failed(f.message)
        val input = java.io.SequenceInputStream(java.io.ByteArrayInputStream(e.ahead.toByteArray()), e.host.input)
        return SalvoIn(e.source, input, e.position, failed)
    }
}
