//! [kt-runtime-source] The backend's *runtime modules* — `runtime/*.kt`,
//! included verbatim by the emitter and written into a program's output when
//! it touches the feature — compiled directly by `kotlinc`.
//!
//! Same reasoning as the Rust backend's `runtime_tests.rs`: these were Rust
//! string literals inside `emit.rs`, so they were only ever compiled as part
//! of a whole generated program and only ever reviewed as escaped text. As
//! real source files they are verified on their own here.
//!
//! Skipped when `kotlinc` is not on PATH.

use std::process::Command;

/// Every static runtime module. A new one belongs here as soon as it exists.
const RUNTIME_MODULES: &[&str] = &["throw.kt"];

/// The bytes the emitter will splice, read from the same path `include_str!`
/// reads at compile time.
fn runtime_source(file: &str) -> String {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("runtime")
        .join(file);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read the runtime module {}: {e}", path.display()))
}

/// Compiles one runtime module on its own and asserts that `kotlinc`
/// accepted it. Warnings are asserted away for the same reason as on Rust:
/// this code lands in user output, where the user cannot fix it.
fn compile_runtime_module(file: &str) {
    let kotlinc = salvo_testkit::kotlinc(env!("CARGO_TARGET_TMPDIR"));
    if !kotlinc.available {
        return;
    }
    let source = runtime_source(file);
    let parts: Vec<&[u8]> = vec![
        b"kotlin-runtime-module",
        kotlinc.version.as_bytes(),
        file.as_bytes(),
        source.as_bytes(),
    ];
    let Some(stamp) = salvo_testkit::cached(
        env!("CARGO_TARGET_TMPDIR"),
        &format!("kotlin-runtime {file}"),
        &parts,
    ) else {
        return;
    };
    let dir = salvo_testkit::scratch(env!("CARGO_TARGET_TMPDIR"), &format!("rt-{file}"));
    let src = dir.join(file);
    std::fs::write(&src, &source).expect("failed to write the runtime module");
    let out = Command::new("kotlinc")
        .arg(&src)
        .arg("-d")
        .arg(dir.join("classes"))
        .output()
        .expect("failed to run kotlinc");
    let noise = String::from_utf8_lossy(&out.stderr);
    assert!(
        out.status.success(),
        "kotlinc rejected runtime/{file}:\n{noise}"
    );
    assert!(
        !noise.contains("warning:"),
        "runtime/{file} compiles with warnings, which would land in user output:\n{noise}"
    );
    stamp.verified();
}

#[test]
fn every_runtime_module_compiles_warning_free() {
    for file in RUNTIME_MODULES {
        compile_runtime_module(file);
    }
}

/// A runtime module is spliced into user output, so it carries the
/// generated-by header and a trailing newline like everything else the
/// emitter writes.
#[test]
fn runtime_modules_carry_the_generated_header() {
    for file in RUNTIME_MODULES {
        let source = runtime_source(file);
        assert!(
            source.starts_with("// Generated by the Salvo compiler:"),
            "runtime/{file} must open with the generated-by header"
        );
        assert!(
            source.ends_with('\n'),
            "runtime/{file} must end with a newline"
        );
    }
}
