// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 023a4214a13ba612

#[derive(Clone, Debug, PartialEq)]
pub struct Instant {
    pub nanos: i64,
}

impl crate::wire::__Wire for Instant {
    fn __enc(&self, out: &mut Vec<u8>) {
        crate::wire::__Wire::__enc(&self.nanos, out);
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        Some(Self {
            nanos: crate::wire::__Wire::__dec(r)?,
        })
    }
}
