// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 023a4214a13ba612
package salvo.time

import salvo.core.actor.*
import salvo.core.bytes.*
import salvo.core.deque.*
import salvo.core.list.*
import salvo.core.map.*
import salvo.core.set.*
import salvo.core.sorted.*
import salvo.core.string.*
import salvo.runtime.*

data class Instant(
    val nanos: Long,
)

object __Codec_Instant : salvo.WireCodec<Instant> {
    override fun enc(v: Instant, out: salvo.WireOut) {
        salvo.LongCodec.enc(v.nanos, out)
    }
    override fun dec(inp: salvo.WireIn): Instant = Instant(salvo.LongCodec.dec(inp))
}
