// Generated by the Salvo compiler: the two clock readings std's `time`
// module is built on [time-types] [rs-time].
//
// Both answer nanoseconds in an `i64`, which is what `Instant`, `Tick` and
// `Duration` carry — one field each, so the seam between the language and the
// host is a number and nothing else.

use std::sync::OnceLock;
use std::time::{Instant, SystemTime, UNIX_EPOCH};

/// [time-ticker] The monotonic clock, in nanoseconds from an arbitrary
/// origin — this process's first reading, established here.
///
/// The origin has to live somewhere: Rust's `Instant` is opaque and cannot be
/// turned into a number, so a *process-wide* base is what makes two readings
/// comparable. One `OnceLock` for the whole program is the point — a base per
/// call site would put two origins in one program and make `between` answer
/// nonsense.
///
/// Never negative, and monotonically non-decreasing: `Instant` guarantees it,
/// and `duration_since` on the process base cannot underflow.
pub fn salvo_mono_nanos() -> i64 {
    static ORIGIN: OnceLock<Instant> = OnceLock::new();
    let origin = ORIGIN.get_or_init(Instant::now);
    Instant::now().duration_since(*origin).as_nanos() as i64
}

/// [time-clock] The wall clock, in nanoseconds since the Unix epoch.
///
/// Before 1970 answers a negative number rather than saturating at zero,
/// which is what a signed epoch reading means on the Kotlin side too — the
/// two backends must agree on the number, not merely on its sign.
pub fn salvo_epoch_nanos() -> i64 {
    match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(since) => since.as_nanos() as i64,
        Err(before) => -(before.duration().as_nanos() as i64),
    }
}
