// Generated by the Salvo compiler: enums for union types.

impl<T1: crate::wire::__Wire, T2: crate::wire::__Wire> crate::wire::__Wire for Union2<T1, T2> {
    fn __enc(&self, out: &mut Vec<u8>) {
        match self {
            Union2::U1(v) => {
                out.push(0);
                crate::wire::__Wire::__enc(v, out);
            }
            Union2::U2(v) => {
                out.push(1);
                crate::wire::__Wire::__enc(v, out);
            }
        }
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        match r.u8()? {
            0 => Some(Union2::U1(crate::wire::__Wire::__dec(r)?)),
            1 => Some(Union2::U2(crate::wire::__Wire::__dec(r)?)),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Union2<T1, T2> {
    U1(T1),
    U2(T2),
}

impl<T1, T2> Union2<T1, T2> {
    pub fn u1(&self) -> &T1 {
        match self {
            Union2::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u1_mut(&mut self) -> &mut T1 {
        match self {
            Union2::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2(&self) -> &T2 {
        match self {
            Union2::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2_mut(&mut self) -> &mut T2 {
        match self {
            Union2::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
}

impl<T1, T2> std::fmt::Display for Union2<T1, T2>
where
    T1: std::fmt::Display,
    T2: std::fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Union2::U1(v) => write!(f, "{}", v),
            Union2::U2(v) => write!(f, "{}", v),
        }
    }
}

impl<T1: crate::wire::__Wire, T2: crate::wire::__Wire, T3: crate::wire::__Wire> crate::wire::__Wire for Union3<T1, T2, T3> {
    fn __enc(&self, out: &mut Vec<u8>) {
        match self {
            Union3::U1(v) => {
                out.push(0);
                crate::wire::__Wire::__enc(v, out);
            }
            Union3::U2(v) => {
                out.push(1);
                crate::wire::__Wire::__enc(v, out);
            }
            Union3::U3(v) => {
                out.push(2);
                crate::wire::__Wire::__enc(v, out);
            }
        }
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        match r.u8()? {
            0 => Some(Union3::U1(crate::wire::__Wire::__dec(r)?)),
            1 => Some(Union3::U2(crate::wire::__Wire::__dec(r)?)),
            2 => Some(Union3::U3(crate::wire::__Wire::__dec(r)?)),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Union3<T1, T2, T3> {
    U1(T1),
    U2(T2),
    U3(T3),
}

impl<T1, T2, T3> Union3<T1, T2, T3> {
    pub fn u1(&self) -> &T1 {
        match self {
            Union3::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u1_mut(&mut self) -> &mut T1 {
        match self {
            Union3::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2(&self) -> &T2 {
        match self {
            Union3::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2_mut(&mut self) -> &mut T2 {
        match self {
            Union3::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3(&self) -> &T3 {
        match self {
            Union3::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3_mut(&mut self) -> &mut T3 {
        match self {
            Union3::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
}

impl<T1, T2, T3> std::fmt::Display for Union3<T1, T2, T3>
where
    T1: std::fmt::Display,
    T2: std::fmt::Display,
    T3: std::fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Union3::U1(v) => write!(f, "{}", v),
            Union3::U2(v) => write!(f, "{}", v),
            Union3::U3(v) => write!(f, "{}", v),
        }
    }
}

impl<T1: crate::wire::__Wire, T2: crate::wire::__Wire, T3: crate::wire::__Wire, T4: crate::wire::__Wire, T5: crate::wire::__Wire, T6: crate::wire::__Wire> crate::wire::__Wire for Union6<T1, T2, T3, T4, T5, T6> {
    fn __enc(&self, out: &mut Vec<u8>) {
        match self {
            Union6::U1(v) => {
                out.push(0);
                crate::wire::__Wire::__enc(v, out);
            }
            Union6::U2(v) => {
                out.push(1);
                crate::wire::__Wire::__enc(v, out);
            }
            Union6::U3(v) => {
                out.push(2);
                crate::wire::__Wire::__enc(v, out);
            }
            Union6::U4(v) => {
                out.push(3);
                crate::wire::__Wire::__enc(v, out);
            }
            Union6::U5(v) => {
                out.push(4);
                crate::wire::__Wire::__enc(v, out);
            }
            Union6::U6(v) => {
                out.push(5);
                crate::wire::__Wire::__enc(v, out);
            }
        }
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        match r.u8()? {
            0 => Some(Union6::U1(crate::wire::__Wire::__dec(r)?)),
            1 => Some(Union6::U2(crate::wire::__Wire::__dec(r)?)),
            2 => Some(Union6::U3(crate::wire::__Wire::__dec(r)?)),
            3 => Some(Union6::U4(crate::wire::__Wire::__dec(r)?)),
            4 => Some(Union6::U5(crate::wire::__Wire::__dec(r)?)),
            5 => Some(Union6::U6(crate::wire::__Wire::__dec(r)?)),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Union6<T1, T2, T3, T4, T5, T6> {
    U1(T1),
    U2(T2),
    U3(T3),
    U4(T4),
    U5(T5),
    U6(T6),
}

impl<T1, T2, T3, T4, T5, T6> Union6<T1, T2, T3, T4, T5, T6> {
    pub fn u1(&self) -> &T1 {
        match self {
            Union6::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u1_mut(&mut self) -> &mut T1 {
        match self {
            Union6::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2(&self) -> &T2 {
        match self {
            Union6::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2_mut(&mut self) -> &mut T2 {
        match self {
            Union6::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3(&self) -> &T3 {
        match self {
            Union6::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3_mut(&mut self) -> &mut T3 {
        match self {
            Union6::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4(&self) -> &T4 {
        match self {
            Union6::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4_mut(&mut self) -> &mut T4 {
        match self {
            Union6::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5(&self) -> &T5 {
        match self {
            Union6::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5_mut(&mut self) -> &mut T5 {
        match self {
            Union6::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6(&self) -> &T6 {
        match self {
            Union6::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6_mut(&mut self) -> &mut T6 {
        match self {
            Union6::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
}

impl<T1, T2, T3, T4, T5, T6> std::fmt::Display for Union6<T1, T2, T3, T4, T5, T6>
where
    T1: std::fmt::Display,
    T2: std::fmt::Display,
    T3: std::fmt::Display,
    T4: std::fmt::Display,
    T5: std::fmt::Display,
    T6: std::fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Union6::U1(v) => write!(f, "{}", v),
            Union6::U2(v) => write!(f, "{}", v),
            Union6::U3(v) => write!(f, "{}", v),
            Union6::U4(v) => write!(f, "{}", v),
            Union6::U5(v) => write!(f, "{}", v),
            Union6::U6(v) => write!(f, "{}", v),
        }
    }
}

impl<T1: crate::wire::__Wire, T2: crate::wire::__Wire, T3: crate::wire::__Wire, T4: crate::wire::__Wire, T5: crate::wire::__Wire, T6: crate::wire::__Wire, T7: crate::wire::__Wire> crate::wire::__Wire for Union7<T1, T2, T3, T4, T5, T6, T7> {
    fn __enc(&self, out: &mut Vec<u8>) {
        match self {
            Union7::U1(v) => {
                out.push(0);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U2(v) => {
                out.push(1);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U3(v) => {
                out.push(2);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U4(v) => {
                out.push(3);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U5(v) => {
                out.push(4);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U6(v) => {
                out.push(5);
                crate::wire::__Wire::__enc(v, out);
            }
            Union7::U7(v) => {
                out.push(6);
                crate::wire::__Wire::__enc(v, out);
            }
        }
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        match r.u8()? {
            0 => Some(Union7::U1(crate::wire::__Wire::__dec(r)?)),
            1 => Some(Union7::U2(crate::wire::__Wire::__dec(r)?)),
            2 => Some(Union7::U3(crate::wire::__Wire::__dec(r)?)),
            3 => Some(Union7::U4(crate::wire::__Wire::__dec(r)?)),
            4 => Some(Union7::U5(crate::wire::__Wire::__dec(r)?)),
            5 => Some(Union7::U6(crate::wire::__Wire::__dec(r)?)),
            6 => Some(Union7::U7(crate::wire::__Wire::__dec(r)?)),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Union7<T1, T2, T3, T4, T5, T6, T7> {
    U1(T1),
    U2(T2),
    U3(T3),
    U4(T4),
    U5(T5),
    U6(T6),
    U7(T7),
}

impl<T1, T2, T3, T4, T5, T6, T7> Union7<T1, T2, T3, T4, T5, T6, T7> {
    pub fn u1(&self) -> &T1 {
        match self {
            Union7::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u1_mut(&mut self) -> &mut T1 {
        match self {
            Union7::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2(&self) -> &T2 {
        match self {
            Union7::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2_mut(&mut self) -> &mut T2 {
        match self {
            Union7::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3(&self) -> &T3 {
        match self {
            Union7::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3_mut(&mut self) -> &mut T3 {
        match self {
            Union7::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4(&self) -> &T4 {
        match self {
            Union7::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4_mut(&mut self) -> &mut T4 {
        match self {
            Union7::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5(&self) -> &T5 {
        match self {
            Union7::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5_mut(&mut self) -> &mut T5 {
        match self {
            Union7::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6(&self) -> &T6 {
        match self {
            Union7::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6_mut(&mut self) -> &mut T6 {
        match self {
            Union7::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7(&self) -> &T7 {
        match self {
            Union7::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7_mut(&mut self) -> &mut T7 {
        match self {
            Union7::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
}

impl<T1, T2, T3, T4, T5, T6, T7> std::fmt::Display for Union7<T1, T2, T3, T4, T5, T6, T7>
where
    T1: std::fmt::Display,
    T2: std::fmt::Display,
    T3: std::fmt::Display,
    T4: std::fmt::Display,
    T5: std::fmt::Display,
    T6: std::fmt::Display,
    T7: std::fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Union7::U1(v) => write!(f, "{}", v),
            Union7::U2(v) => write!(f, "{}", v),
            Union7::U3(v) => write!(f, "{}", v),
            Union7::U4(v) => write!(f, "{}", v),
            Union7::U5(v) => write!(f, "{}", v),
            Union7::U6(v) => write!(f, "{}", v),
            Union7::U7(v) => write!(f, "{}", v),
        }
    }
}

impl<T1: crate::wire::__Wire, T2: crate::wire::__Wire, T3: crate::wire::__Wire, T4: crate::wire::__Wire, T5: crate::wire::__Wire, T6: crate::wire::__Wire, T7: crate::wire::__Wire, T8: crate::wire::__Wire> crate::wire::__Wire for Union8<T1, T2, T3, T4, T5, T6, T7, T8> {
    fn __enc(&self, out: &mut Vec<u8>) {
        match self {
            Union8::U1(v) => {
                out.push(0);
                crate::wire::__Wire::__enc(v, out);
            }
            Union8::U2(v) => {
                out.push(1);
                crate::wire::__Wire::__enc(v, out);
            }
            Union8::U3(v) => {
                out.push(2);
                crate::wire::__Wire::__enc(v, out);
            }
            Union8::U4(v) => {
                out.push(3);
                crate::wire::__Wire::__enc(v, out);
            }
            Union8::U5(v) => {
                out.push(4);
                crate::wire::__Wire::__enc(v, out);
            }
            Union8::U6(v) => {
                out.push(5);
                crate::wire::__Wire::__enc(v, out);
            }
            Union8::U7(v) => {
                out.push(6);
                crate::wire::__Wire::__enc(v, out);
            }
            Union8::U8(v) => {
                out.push(7);
                crate::wire::__Wire::__enc(v, out);
            }
        }
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        match r.u8()? {
            0 => Some(Union8::U1(crate::wire::__Wire::__dec(r)?)),
            1 => Some(Union8::U2(crate::wire::__Wire::__dec(r)?)),
            2 => Some(Union8::U3(crate::wire::__Wire::__dec(r)?)),
            3 => Some(Union8::U4(crate::wire::__Wire::__dec(r)?)),
            4 => Some(Union8::U5(crate::wire::__Wire::__dec(r)?)),
            5 => Some(Union8::U6(crate::wire::__Wire::__dec(r)?)),
            6 => Some(Union8::U7(crate::wire::__Wire::__dec(r)?)),
            7 => Some(Union8::U8(crate::wire::__Wire::__dec(r)?)),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Union8<T1, T2, T3, T4, T5, T6, T7, T8> {
    U1(T1),
    U2(T2),
    U3(T3),
    U4(T4),
    U5(T5),
    U6(T6),
    U7(T7),
    U8(T8),
}

impl<T1, T2, T3, T4, T5, T6, T7, T8> Union8<T1, T2, T3, T4, T5, T6, T7, T8> {
    pub fn u1(&self) -> &T1 {
        match self {
            Union8::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u1_mut(&mut self) -> &mut T1 {
        match self {
            Union8::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2(&self) -> &T2 {
        match self {
            Union8::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2_mut(&mut self) -> &mut T2 {
        match self {
            Union8::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3(&self) -> &T3 {
        match self {
            Union8::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3_mut(&mut self) -> &mut T3 {
        match self {
            Union8::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4(&self) -> &T4 {
        match self {
            Union8::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4_mut(&mut self) -> &mut T4 {
        match self {
            Union8::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5(&self) -> &T5 {
        match self {
            Union8::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5_mut(&mut self) -> &mut T5 {
        match self {
            Union8::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6(&self) -> &T6 {
        match self {
            Union8::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6_mut(&mut self) -> &mut T6 {
        match self {
            Union8::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7(&self) -> &T7 {
        match self {
            Union8::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7_mut(&mut self) -> &mut T7 {
        match self {
            Union8::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u8(&self) -> &T8 {
        match self {
            Union8::U8(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u8_mut(&mut self) -> &mut T8 {
        match self {
            Union8::U8(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
}

impl<T1, T2, T3, T4, T5, T6, T7, T8> std::fmt::Display for Union8<T1, T2, T3, T4, T5, T6, T7, T8>
where
    T1: std::fmt::Display,
    T2: std::fmt::Display,
    T3: std::fmt::Display,
    T4: std::fmt::Display,
    T5: std::fmt::Display,
    T6: std::fmt::Display,
    T7: std::fmt::Display,
    T8: std::fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Union8::U1(v) => write!(f, "{}", v),
            Union8::U2(v) => write!(f, "{}", v),
            Union8::U3(v) => write!(f, "{}", v),
            Union8::U4(v) => write!(f, "{}", v),
            Union8::U5(v) => write!(f, "{}", v),
            Union8::U6(v) => write!(f, "{}", v),
            Union8::U7(v) => write!(f, "{}", v),
            Union8::U8(v) => write!(f, "{}", v),
        }
    }
}

impl<T1: crate::wire::__Wire, T2: crate::wire::__Wire, T3: crate::wire::__Wire, T4: crate::wire::__Wire, T5: crate::wire::__Wire, T6: crate::wire::__Wire, T7: crate::wire::__Wire, T8: crate::wire::__Wire, T9: crate::wire::__Wire, T10: crate::wire::__Wire, T11: crate::wire::__Wire> crate::wire::__Wire for Union11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> {
    fn __enc(&self, out: &mut Vec<u8>) {
        match self {
            Union11::U1(v) => {
                out.push(0);
                crate::wire::__Wire::__enc(v, out);
            }
            Union11::U2(v) => {
                out.push(1);
                crate::wire::__Wire::__enc(v, out);
            }
            Union11::U3(v) => {
                out.push(2);
                crate::wire::__Wire::__enc(v, out);
            }
            Union11::U4(v) => {
                out.push(3);
                crate::wire::__Wire::__enc(v, out);
            }
            Union11::U5(v) => {
                out.push(4);
                crate::wire::__Wire::__enc(v, out);
            }
            Union11::U6(v) => {
                out.push(5);
                crate::wire::__Wire::__enc(v, out);
            }
            Union11::U7(v) => {
                out.push(6);
                crate::wire::__Wire::__enc(v, out);
            }
            Union11::U8(v) => {
                out.push(7);
                crate::wire::__Wire::__enc(v, out);
            }
            Union11::U9(v) => {
                out.push(8);
                crate::wire::__Wire::__enc(v, out);
            }
            Union11::U10(v) => {
                out.push(9);
                crate::wire::__Wire::__enc(v, out);
            }
            Union11::U11(v) => {
                out.push(10);
                crate::wire::__Wire::__enc(v, out);
            }
        }
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        match r.u8()? {
            0 => Some(Union11::U1(crate::wire::__Wire::__dec(r)?)),
            1 => Some(Union11::U2(crate::wire::__Wire::__dec(r)?)),
            2 => Some(Union11::U3(crate::wire::__Wire::__dec(r)?)),
            3 => Some(Union11::U4(crate::wire::__Wire::__dec(r)?)),
            4 => Some(Union11::U5(crate::wire::__Wire::__dec(r)?)),
            5 => Some(Union11::U6(crate::wire::__Wire::__dec(r)?)),
            6 => Some(Union11::U7(crate::wire::__Wire::__dec(r)?)),
            7 => Some(Union11::U8(crate::wire::__Wire::__dec(r)?)),
            8 => Some(Union11::U9(crate::wire::__Wire::__dec(r)?)),
            9 => Some(Union11::U10(crate::wire::__Wire::__dec(r)?)),
            10 => Some(Union11::U11(crate::wire::__Wire::__dec(r)?)),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Union11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> {
    U1(T1),
    U2(T2),
    U3(T3),
    U4(T4),
    U5(T5),
    U6(T6),
    U7(T7),
    U8(T8),
    U9(T9),
    U10(T10),
    U11(T11),
}

impl<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> Union11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> {
    pub fn u1(&self) -> &T1 {
        match self {
            Union11::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u1_mut(&mut self) -> &mut T1 {
        match self {
            Union11::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2(&self) -> &T2 {
        match self {
            Union11::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2_mut(&mut self) -> &mut T2 {
        match self {
            Union11::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3(&self) -> &T3 {
        match self {
            Union11::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3_mut(&mut self) -> &mut T3 {
        match self {
            Union11::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4(&self) -> &T4 {
        match self {
            Union11::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4_mut(&mut self) -> &mut T4 {
        match self {
            Union11::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5(&self) -> &T5 {
        match self {
            Union11::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5_mut(&mut self) -> &mut T5 {
        match self {
            Union11::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6(&self) -> &T6 {
        match self {
            Union11::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6_mut(&mut self) -> &mut T6 {
        match self {
            Union11::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7(&self) -> &T7 {
        match self {
            Union11::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7_mut(&mut self) -> &mut T7 {
        match self {
            Union11::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u8(&self) -> &T8 {
        match self {
            Union11::U8(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u8_mut(&mut self) -> &mut T8 {
        match self {
            Union11::U8(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u9(&self) -> &T9 {
        match self {
            Union11::U9(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u9_mut(&mut self) -> &mut T9 {
        match self {
            Union11::U9(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u10(&self) -> &T10 {
        match self {
            Union11::U10(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u10_mut(&mut self) -> &mut T10 {
        match self {
            Union11::U10(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u11(&self) -> &T11 {
        match self {
            Union11::U11(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u11_mut(&mut self) -> &mut T11 {
        match self {
            Union11::U11(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
}

impl<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> std::fmt::Display for Union11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>
where
    T1: std::fmt::Display,
    T2: std::fmt::Display,
    T3: std::fmt::Display,
    T4: std::fmt::Display,
    T5: std::fmt::Display,
    T6: std::fmt::Display,
    T7: std::fmt::Display,
    T8: std::fmt::Display,
    T9: std::fmt::Display,
    T10: std::fmt::Display,
    T11: std::fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Union11::U1(v) => write!(f, "{}", v),
            Union11::U2(v) => write!(f, "{}", v),
            Union11::U3(v) => write!(f, "{}", v),
            Union11::U4(v) => write!(f, "{}", v),
            Union11::U5(v) => write!(f, "{}", v),
            Union11::U6(v) => write!(f, "{}", v),
            Union11::U7(v) => write!(f, "{}", v),
            Union11::U8(v) => write!(f, "{}", v),
            Union11::U9(v) => write!(f, "{}", v),
            Union11::U10(v) => write!(f, "{}", v),
            Union11::U11(v) => write!(f, "{}", v),
        }
    }
}

impl<T1: crate::wire::__Wire, T2: crate::wire::__Wire, T3: crate::wire::__Wire, T4: crate::wire::__Wire, T5: crate::wire::__Wire, T6: crate::wire::__Wire, T7: crate::wire::__Wire, T8: crate::wire::__Wire, T9: crate::wire::__Wire, T10: crate::wire::__Wire, T11: crate::wire::__Wire, T12: crate::wire::__Wire, T13: crate::wire::__Wire, T14: crate::wire::__Wire, T15: crate::wire::__Wire, T16: crate::wire::__Wire> crate::wire::__Wire for Union16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> {
    fn __enc(&self, out: &mut Vec<u8>) {
        match self {
            Union16::U1(v) => {
                out.push(0);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U2(v) => {
                out.push(1);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U3(v) => {
                out.push(2);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U4(v) => {
                out.push(3);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U5(v) => {
                out.push(4);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U6(v) => {
                out.push(5);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U7(v) => {
                out.push(6);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U8(v) => {
                out.push(7);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U9(v) => {
                out.push(8);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U10(v) => {
                out.push(9);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U11(v) => {
                out.push(10);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U12(v) => {
                out.push(11);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U13(v) => {
                out.push(12);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U14(v) => {
                out.push(13);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U15(v) => {
                out.push(14);
                crate::wire::__Wire::__enc(v, out);
            }
            Union16::U16(v) => {
                out.push(15);
                crate::wire::__Wire::__enc(v, out);
            }
        }
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        match r.u8()? {
            0 => Some(Union16::U1(crate::wire::__Wire::__dec(r)?)),
            1 => Some(Union16::U2(crate::wire::__Wire::__dec(r)?)),
            2 => Some(Union16::U3(crate::wire::__Wire::__dec(r)?)),
            3 => Some(Union16::U4(crate::wire::__Wire::__dec(r)?)),
            4 => Some(Union16::U5(crate::wire::__Wire::__dec(r)?)),
            5 => Some(Union16::U6(crate::wire::__Wire::__dec(r)?)),
            6 => Some(Union16::U7(crate::wire::__Wire::__dec(r)?)),
            7 => Some(Union16::U8(crate::wire::__Wire::__dec(r)?)),
            8 => Some(Union16::U9(crate::wire::__Wire::__dec(r)?)),
            9 => Some(Union16::U10(crate::wire::__Wire::__dec(r)?)),
            10 => Some(Union16::U11(crate::wire::__Wire::__dec(r)?)),
            11 => Some(Union16::U12(crate::wire::__Wire::__dec(r)?)),
            12 => Some(Union16::U13(crate::wire::__Wire::__dec(r)?)),
            13 => Some(Union16::U14(crate::wire::__Wire::__dec(r)?)),
            14 => Some(Union16::U15(crate::wire::__Wire::__dec(r)?)),
            15 => Some(Union16::U16(crate::wire::__Wire::__dec(r)?)),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Union16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> {
    U1(T1),
    U2(T2),
    U3(T3),
    U4(T4),
    U5(T5),
    U6(T6),
    U7(T7),
    U8(T8),
    U9(T9),
    U10(T10),
    U11(T11),
    U12(T12),
    U13(T13),
    U14(T14),
    U15(T15),
    U16(T16),
}

impl<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> Union16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> {
    pub fn u1(&self) -> &T1 {
        match self {
            Union16::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u1_mut(&mut self) -> &mut T1 {
        match self {
            Union16::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2(&self) -> &T2 {
        match self {
            Union16::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2_mut(&mut self) -> &mut T2 {
        match self {
            Union16::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3(&self) -> &T3 {
        match self {
            Union16::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3_mut(&mut self) -> &mut T3 {
        match self {
            Union16::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4(&self) -> &T4 {
        match self {
            Union16::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4_mut(&mut self) -> &mut T4 {
        match self {
            Union16::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5(&self) -> &T5 {
        match self {
            Union16::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u5_mut(&mut self) -> &mut T5 {
        match self {
            Union16::U5(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6(&self) -> &T6 {
        match self {
            Union16::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u6_mut(&mut self) -> &mut T6 {
        match self {
            Union16::U6(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7(&self) -> &T7 {
        match self {
            Union16::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u7_mut(&mut self) -> &mut T7 {
        match self {
            Union16::U7(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u8(&self) -> &T8 {
        match self {
            Union16::U8(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u8_mut(&mut self) -> &mut T8 {
        match self {
            Union16::U8(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u9(&self) -> &T9 {
        match self {
            Union16::U9(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u9_mut(&mut self) -> &mut T9 {
        match self {
            Union16::U9(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u10(&self) -> &T10 {
        match self {
            Union16::U10(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u10_mut(&mut self) -> &mut T10 {
        match self {
            Union16::U10(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u11(&self) -> &T11 {
        match self {
            Union16::U11(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u11_mut(&mut self) -> &mut T11 {
        match self {
            Union16::U11(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u12(&self) -> &T12 {
        match self {
            Union16::U12(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u12_mut(&mut self) -> &mut T12 {
        match self {
            Union16::U12(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u13(&self) -> &T13 {
        match self {
            Union16::U13(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u13_mut(&mut self) -> &mut T13 {
        match self {
            Union16::U13(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u14(&self) -> &T14 {
        match self {
            Union16::U14(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u14_mut(&mut self) -> &mut T14 {
        match self {
            Union16::U14(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u15(&self) -> &T15 {
        match self {
            Union16::U15(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u15_mut(&mut self) -> &mut T15 {
        match self {
            Union16::U15(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u16(&self) -> &T16 {
        match self {
            Union16::U16(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u16_mut(&mut self) -> &mut T16 {
        match self {
            Union16::U16(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
}

impl<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> std::fmt::Display for Union16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>
where
    T1: std::fmt::Display,
    T2: std::fmt::Display,
    T3: std::fmt::Display,
    T4: std::fmt::Display,
    T5: std::fmt::Display,
    T6: std::fmt::Display,
    T7: std::fmt::Display,
    T8: std::fmt::Display,
    T9: std::fmt::Display,
    T10: std::fmt::Display,
    T11: std::fmt::Display,
    T12: std::fmt::Display,
    T13: std::fmt::Display,
    T14: std::fmt::Display,
    T15: std::fmt::Display,
    T16: std::fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Union16::U1(v) => write!(f, "{}", v),
            Union16::U2(v) => write!(f, "{}", v),
            Union16::U3(v) => write!(f, "{}", v),
            Union16::U4(v) => write!(f, "{}", v),
            Union16::U5(v) => write!(f, "{}", v),
            Union16::U6(v) => write!(f, "{}", v),
            Union16::U7(v) => write!(f, "{}", v),
            Union16::U8(v) => write!(f, "{}", v),
            Union16::U9(v) => write!(f, "{}", v),
            Union16::U10(v) => write!(f, "{}", v),
            Union16::U11(v) => write!(f, "{}", v),
            Union16::U12(v) => write!(f, "{}", v),
            Union16::U13(v) => write!(f, "{}", v),
            Union16::U14(v) => write!(f, "{}", v),
            Union16::U15(v) => write!(f, "{}", v),
            Union16::U16(v) => write!(f, "{}", v),
        }
    }
}
