// Generated by the Salvo compiler: sealed wrappers for union types.
package salvo

sealed interface Union2<out T1, out T2> {
    val value: Any?
    data class U1<out T1, out T2>(override val value: T1) : Union2<T1, T2>
    data class U2<out T1, out T2>(override val value: T2) : Union2<T1, T2>
}

class Union2Codec<T1, T2>(private val c1: WireCodec<T1>, private val c2: WireCodec<T2>) : WireCodec<Union2<T1, T2>> {
    override fun enc(v: Union2<T1, T2>, out: WireOut) {
        when (v) {
            is Union2.U1 -> { out.u8(0); c1.enc(v.value, out) }
            is Union2.U2 -> { out.u8(1); c2.enc(v.value, out) }
        }
    }
    override fun dec(inp: WireIn): Union2<T1, T2> = when (inp.u8()) {
            0 -> Union2.U1(c1.dec(inp))
            1 -> Union2.U2(c2.dec(inp))
            else -> throw WireError()
        }
}

sealed interface Union3<out T1, out T2, out T3> {
    val value: Any?
    data class U1<out T1, out T2, out T3>(override val value: T1) : Union3<T1, T2, T3>
    data class U2<out T1, out T2, out T3>(override val value: T2) : Union3<T1, T2, T3>
    data class U3<out T1, out T2, out T3>(override val value: T3) : Union3<T1, T2, T3>
}

class Union3Codec<T1, T2, T3>(private val c1: WireCodec<T1>, private val c2: WireCodec<T2>, private val c3: WireCodec<T3>) : WireCodec<Union3<T1, T2, T3>> {
    override fun enc(v: Union3<T1, T2, T3>, out: WireOut) {
        when (v) {
            is Union3.U1 -> { out.u8(0); c1.enc(v.value, out) }
            is Union3.U2 -> { out.u8(1); c2.enc(v.value, out) }
            is Union3.U3 -> { out.u8(2); c3.enc(v.value, out) }
        }
    }
    override fun dec(inp: WireIn): Union3<T1, T2, T3> = when (inp.u8()) {
            0 -> Union3.U1(c1.dec(inp))
            1 -> Union3.U2(c2.dec(inp))
            2 -> Union3.U3(c3.dec(inp))
            else -> throw WireError()
        }
}

sealed interface Union6<out T1, out T2, out T3, out T4, out T5, out T6> {
    val value: Any?
    data class U1<out T1, out T2, out T3, out T4, out T5, out T6>(override val value: T1) : Union6<T1, T2, T3, T4, T5, T6>
    data class U2<out T1, out T2, out T3, out T4, out T5, out T6>(override val value: T2) : Union6<T1, T2, T3, T4, T5, T6>
    data class U3<out T1, out T2, out T3, out T4, out T5, out T6>(override val value: T3) : Union6<T1, T2, T3, T4, T5, T6>
    data class U4<out T1, out T2, out T3, out T4, out T5, out T6>(override val value: T4) : Union6<T1, T2, T3, T4, T5, T6>
    data class U5<out T1, out T2, out T3, out T4, out T5, out T6>(override val value: T5) : Union6<T1, T2, T3, T4, T5, T6>
    data class U6<out T1, out T2, out T3, out T4, out T5, out T6>(override val value: T6) : Union6<T1, T2, T3, T4, T5, T6>
}

class Union6Codec<T1, T2, T3, T4, T5, T6>(private val c1: WireCodec<T1>, private val c2: WireCodec<T2>, private val c3: WireCodec<T3>, private val c4: WireCodec<T4>, private val c5: WireCodec<T5>, private val c6: WireCodec<T6>) : WireCodec<Union6<T1, T2, T3, T4, T5, T6>> {
    override fun enc(v: Union6<T1, T2, T3, T4, T5, T6>, out: WireOut) {
        when (v) {
            is Union6.U1 -> { out.u8(0); c1.enc(v.value, out) }
            is Union6.U2 -> { out.u8(1); c2.enc(v.value, out) }
            is Union6.U3 -> { out.u8(2); c3.enc(v.value, out) }
            is Union6.U4 -> { out.u8(3); c4.enc(v.value, out) }
            is Union6.U5 -> { out.u8(4); c5.enc(v.value, out) }
            is Union6.U6 -> { out.u8(5); c6.enc(v.value, out) }
        }
    }
    override fun dec(inp: WireIn): Union6<T1, T2, T3, T4, T5, T6> = when (inp.u8()) {
            0 -> Union6.U1(c1.dec(inp))
            1 -> Union6.U2(c2.dec(inp))
            2 -> Union6.U3(c3.dec(inp))
            3 -> Union6.U4(c4.dec(inp))
            4 -> Union6.U5(c5.dec(inp))
            5 -> Union6.U6(c6.dec(inp))
            else -> throw WireError()
        }
}

sealed interface Union7<out T1, out T2, out T3, out T4, out T5, out T6, out T7> {
    val value: Any?
    data class U1<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T1) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U2<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T2) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U3<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T3) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U4<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T4) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U5<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T5) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U6<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T6) : Union7<T1, T2, T3, T4, T5, T6, T7>
    data class U7<out T1, out T2, out T3, out T4, out T5, out T6, out T7>(override val value: T7) : Union7<T1, T2, T3, T4, T5, T6, T7>
}

class Union7Codec<T1, T2, T3, T4, T5, T6, T7>(private val c1: WireCodec<T1>, private val c2: WireCodec<T2>, private val c3: WireCodec<T3>, private val c4: WireCodec<T4>, private val c5: WireCodec<T5>, private val c6: WireCodec<T6>, private val c7: WireCodec<T7>) : WireCodec<Union7<T1, T2, T3, T4, T5, T6, T7>> {
    override fun enc(v: Union7<T1, T2, T3, T4, T5, T6, T7>, out: WireOut) {
        when (v) {
            is Union7.U1 -> { out.u8(0); c1.enc(v.value, out) }
            is Union7.U2 -> { out.u8(1); c2.enc(v.value, out) }
            is Union7.U3 -> { out.u8(2); c3.enc(v.value, out) }
            is Union7.U4 -> { out.u8(3); c4.enc(v.value, out) }
            is Union7.U5 -> { out.u8(4); c5.enc(v.value, out) }
            is Union7.U6 -> { out.u8(5); c6.enc(v.value, out) }
            is Union7.U7 -> { out.u8(6); c7.enc(v.value, out) }
        }
    }
    override fun dec(inp: WireIn): Union7<T1, T2, T3, T4, T5, T6, T7> = when (inp.u8()) {
            0 -> Union7.U1(c1.dec(inp))
            1 -> Union7.U2(c2.dec(inp))
            2 -> Union7.U3(c3.dec(inp))
            3 -> Union7.U4(c4.dec(inp))
            4 -> Union7.U5(c5.dec(inp))
            5 -> Union7.U6(c6.dec(inp))
            6 -> Union7.U7(c7.dec(inp))
            else -> throw WireError()
        }
}
