//! Kotlin backend for the Salvo compiler.

mod emit;
mod imports;
mod intrinsics;
pub mod stdlib;
pub mod ir_emit;

pub use emit::{
    emit_abi, emit_program, emit_program_reporting, host_package, platform_skeletons,
    EmittedFile,
};

use std::path::{Path, PathBuf};

use salvo_backend::{run_tool, Backend, BackendError, Emitted};
use salvo_core::{HostDeps, ModulePath, Program};

/// Where `kotlinc` puts the compiled classes inside the target directory
/// [kt-run]. Dot-prefixed so a target nested in the source tree stays
/// invisible to source discovery [mod-ignore].
const CLASSES_DIR: &str = ".salvo_classes";

/// [kt-std-library] The file in the target naming the compiled standard
/// library `prepare_run` readied for this build.
const STD_MARKER: &str = ".salvo_std_library";

/// [kt-gradle] The Gradle build written beside the emitted sources when
/// artifacts are declared, the Kotlin counterpart of Rust's `Cargo.toml`
/// [rs-cargo]: `settings.gradle.kts` makes the target its own Gradle root (so
/// no enclosing build is picked up), `build.gradle.kts` resolves the
/// artifacts. Both carry [`GRADLE_HEADER`], which is how a stale one is told
/// from a hand-written one.
const GRADLE_BUILD: &str = "build.gradle.kts";
const GRADLE_SETTINGS: &str = "settings.gradle.kts";
const GRADLE_HEADER: &str =
    "// Written by salvo from `[kotlin] artifacts` [kt-gradle]: resolves them for the\n\
     // Kotlin build. Regenerated on every build — edit salvo.toml, not this file.";
const ABI_GRADLE_HEADER: &str = "// GENERATED by salvo [platform-abi]: the host project of this platform root,\n\
    // so an IDE can open it. Rewritten by every build — do not edit.";
/// [platform-abi] The Kotlin the compiler is tested with, for the host
/// project's Gradle plugin.
const KOTLIN_VERSION: &str = "2.4.0";

/// [kt-gradle] Where the resolved classpath lands, relative to the target
/// (hidden, like the classes directory, so source discovery skips it).
const GRADLE_CLASSPATH: &str = ".salvo_gradle/classpath.txt";

/// The name Kotlin gives a file's top-level facade class: the file name with
/// its first letter capitalized and `Kt` appended (`other.kt` ->
/// `OtherKt`). A module's emitted file is named after its last segment.
fn facade_class(module: &ModulePath) -> String {
    let stem = module.0.last().map(String::as_str).unwrap_or("main");
    let mut chars = stem.chars();
    let capitalized = match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    };
    format!("{capitalized}Kt")
}

pub struct KotlinBackend;

impl Backend for KotlinBackend {
    fn name(&self) -> &'static str {
        "kotlin"
    }

    fn file_extension(&self) -> &'static str {
        "kt"
    }

    /// Kotlin compiles a top-level `main` in every module that declares
    /// one, so the entry selection changes only the launch class
    /// ([`Backend::entry_hint`]) and never the emitted code.
    fn emit(
        &self,
        program: &Program,
        target_dir: &Path,
        _entry: Option<&ModulePath>,
    ) -> Result<Emitted, BackendError> {
        let (files, warnings) =
            emit::emit_program_reporting(program).map_err(BackendError::Codegen)?;
        let written = salvo_backend::emit_util::write_emitted(target_dir, files)?;
        Ok(Emitted {
            files: written,
            warnings,
        })
    }

    /// The JVM entry class. Kotlin names a file's facade class after the
    /// **file**, not the function: module `other` is emitted as `other.kt`
    /// in package `salvo.other`, so its top-level `main` lands in
    /// `salvo.other.OtherKt`. (Before `salvo run` exercised it, this hint
    /// read `…MainKt` unconditionally — correct only because every entry
    /// file so far was `main.sv`.)
    fn entry_hint(
        &self,
        _target_dir: &Path,
        main_module: &ModulePath,
        _emitted: &[PathBuf],
    ) -> String {
        format!("salvo.{main_module}.{}", facade_class(main_module))
    }

    /// Kotlin needs no entry hint here: the host file for a module is the
    /// same file wherever the entry happens to be.
    fn platform_skeletons(
        &self,
        program: &Program,
        _entry: Option<&ModulePath>,
    ) -> Result<Vec<(PathBuf, String)>, BackendError> {
        let files = if std::env::var("SALVO_KOTLIN_IR").is_ok() {
            emit::ir_emit_skeletons(program).map_err(BackendError::Codegen)?
        } else {
            emit::platform_skeletons(program).map_err(BackendError::Codegen)?
        };
        Ok(salvo_backend::emit_util::as_pairs(files))
    }

    /// [platform-abi] [kt-abi] The declarations and runtime of `emit_abi`,
    /// plus a Gradle project over the root: the Kotlin JVM plugin at the
    /// version the compiler is tested with, the root itself as the source
    /// directory (implementation files and generated ones alike), and the
    /// declared artifacts and `libs` jars as dependencies — so an IDE opening
    /// the root resolves every name an implementation file uses.
    fn platform_abi(
        &self,
        program: &Program,
        _entry: Option<&ModulePath>,
        host: &HostDeps,
    ) -> Result<Vec<(PathBuf, String)>, BackendError> {
        let files = emit::emit_abi(program).map_err(BackendError::Codegen)?;
        if files.is_empty() {
            return Ok(Vec::new());
        }
        // [platform-stamp] What a consumer compares before building this root.
        let (stamp, mut out) = salvo_backend::emit_util::stamp_abi_files(program, files);
        let mut deps = String::new();
        for coord in &host.kotlin_artifacts {
            deps.push_str(&format!("    implementation(\"{coord}\")\n"));
        }
        for dir in &host.kotlin_libs {
            deps.push_str(&format!(
                "    implementation(fileTree(\"{}\") {{ include(\"*.jar\") }})\n",
                dir.display()
            ));
        }
        out.push((
            PathBuf::from(GRADLE_BUILD),
            format!(
                "{ABI_GRADLE_HEADER}\n// {stamp}\n\
                 plugins {{ kotlin(\"jvm\") version \"{KOTLIN_VERSION}\" }}\n\n\
                 repositories {{ mavenCentral() }}\n\n\
                 // Implementation files (`<m>.kt`) and the generated declarations\n\
                 // (`*.sv.kt`) are one source set, as they are one compilation in the\n\
                 // build.\n\
                 kotlin {{\n\
                 \x20   sourceSets[\"main\"].kotlin {{\n\
                 \x20       setSrcDirs(listOf(\".\"))\n\
                 \x20       include(\"**/*.kt\")\n\
                 \x20       exclude(\".gradle/**\")\n\
                 \x20   }}\n\
                 }}\n\
                 sourceSets[\"main\"].java.setSrcDirs(emptyList<String>())\n\
                 sourceSets[\"main\"].resources.setSrcDirs(emptyList<String>())\n\
                 // Hidden, so the Salvo build never mistakes output for platform code.\n\
                 layout.buildDirectory.set(file(\".gradle/build\"))\n\n\
                 dependencies {{\n{deps}}}\n"
            ),
        ));
        out.push((
            PathBuf::from(GRADLE_SETTINGS),
            format!("{ABI_GRADLE_HEADER}\n// {stamp}\n\nrootProject.name = \"salvo-platform\"\n"),
        ));
        Ok(out)
    }

    /// [kt-gradle] With artifacts declared [platform-host-deps], a Gradle
    /// build beside the sources resolves them; without, a build a previous
    /// run wrote is removed (only ours, recognised by its header).
    fn write_host_manifest(
        &self,
        target_dir: &Path,
        _main_module: &ModulePath,
        host: &HostDeps,
    ) -> Result<Vec<PathBuf>, BackendError> {
        let files = [GRADLE_BUILD, GRADLE_SETTINGS];
        if !host.has_kotlin_artifacts() {
            for name in files {
                salvo_backend::emit_util::remove_if_ours(&target_dir.join(name), GRADLE_HEADER)?;
            }
            return Ok(Vec::new());
        }
        std::fs::create_dir_all(target_dir)?;
        std::fs::write(
            target_dir.join(GRADLE_BUILD),
            host.gradle_build_script(GRADLE_HEADER, Path::new(GRADLE_CLASSPATH)),
        )?;
        std::fs::write(
            target_dir.join(GRADLE_SETTINGS),
            format!("{GRADLE_HEADER}\n\nrootProject.name = \"salvo-host\"\n"),
        )?;
        Ok(files.iter().map(PathBuf::from).collect())
    }

    /// [kt-std-library] Compiles the standard library into the cache, when it
    /// is not there yet, and records it in the target for `program_command`.
    fn prepare_run(&self, program: &Program, target_dir: &Path) -> Result<(), BackendError> {
        let marker = target_dir.join(STD_MARKER);
        let _ = std::fs::remove_file(&marker);
        let Some(root) = stdlib::default_cache_root() else {
            return Ok(());
        };
        let files = stdlib::std_library_files(program).map_err(BackendError::Codegen)?;
        let library = stdlib::prepare(&root, files).map_err(BackendError::Other)?;
        std::fs::write(&marker, library.entry().to_string_lossy().as_bytes())?;
        Ok(())
    }

    /// [kt-run] `kotlinc` every emitted `.kt` file into a classes directory
    /// inside the target, then `kotlin -cp` that directory with the entry
    /// class. Companion files [backend-companion] are `.kt` too, so they
    /// are part of `emitted` and compile with the rest — including the
    /// platform host [platform-tree].
    /// [kt-classpath] The declared `libs` directories' jars
    /// [platform-host-deps] go on the classpath of both the compile and the
    /// run; with none declared the invocations are as before.
    fn program_command(
        &self,
        target_dir: &Path,
        main_module: &ModulePath,
        emitted: &[PathBuf],
        host: &HostDeps,
    ) -> Result<std::process::Command, BackendError> {
        use std::ffi::OsStr;

        let classes = target_dir.join(CLASSES_DIR);
        let mut sources: Vec<PathBuf> = emitted
            .iter()
            .filter(|p| p.extension().is_some_and(|e| e == "kt"))
            .map(|p| target_dir.join(p))
            .collect();
        // [kt-std-library] With a library readied, compile only the files it
        // does not cover — when every one it does cover is identical.
        let library = std::fs::read_to_string(target_dir.join(STD_MARKER))
            .ok()
            .and_then(|entry| stdlib::load(Path::new(entry.trim())));
        let library = library.and_then(|lib| {
            let texts: Vec<(PathBuf, String)> = emitted
                .iter()
                .filter(|p| p.extension().is_some_and(|e| e == "kt"))
                .filter_map(|p| Some((p.clone(), std::fs::read_to_string(target_dir.join(p)).ok()?)))
                .collect();
            let own: Vec<PathBuf> = lib
                .own_files(texts.iter().map(|(p, t)| (p.as_path(), t.as_str())))?
                .into_iter()
                .map(|p| target_dir.join(p))
                .collect();
            Some((lib.classes, own))
        });
        if let Some((_, own)) = &library {
            sources = own.clone();
        }
        let lib_classes: Option<PathBuf> = library.map(|(c, _)| c);
        if sources.is_empty() {
            return Err(BackendError::Other(
                "nothing to run: no Kotlin sources were emitted".to_string(),
            ));
        }
        // [kt-gradle] Gradle resolves the declared artifacts first; their
        // jars come before the `libs` directories' on both classpaths.
        let mut jars = Vec::new();
        if host.has_kotlin_artifacts() {
            if !target_dir.join(GRADLE_BUILD).is_file() {
                return Err(BackendError::Other(format!(
                    "artifacts are declared but `{}` was not written [kt-gradle]",
                    target_dir.join(GRADLE_BUILD).display()
                )));
            }
            let out = target_dir.join(GRADLE_CLASSPATH);
            let _ = std::fs::remove_file(&out);
            let code = salvo_backend::run_host_tool(
                &host.gradle_program(),
                "[kotlin] gradle",
                &[
                    OsStr::new("--quiet"),
                    OsStr::new("--project-dir"),
                    target_dir.as_os_str(),
                    OsStr::new("salvoClasspath"),
                ],
            )?;
            if code != 0 {
                return Err(BackendError::Other(format!(
                    "Gradle failed with exit code {code} resolving `[kotlin] artifacts` [kt-gradle]"
                )));
            }
            let listed = std::fs::read_to_string(&out).map_err(|e| {
                BackendError::Other(format!(
                    "Gradle ran but wrote no classpath to `{}`: {e} [kt-gradle]",
                    out.display()
                ))
            })?;
            jars.extend(listed.lines().filter(|l| !l.trim().is_empty()).map(PathBuf::from));
        }
        jars.extend(host.kotlin_jars());
        let classpath = |leading: &Path| {
            std::env::join_paths(
                std::iter::once(leading.to_path_buf()).chain(lib_classes.iter().cloned()).chain(jars.iter().cloned()),
            )
                .map_err(|e| BackendError::Other(format!("cannot build a classpath: {e}")))
        };

        let mut args: Vec<&OsStr> = sources.iter().map(|p| p.as_os_str()).collect();
        args.push(OsStr::new("-d"));
        args.push(classes.as_os_str());
        // [kt-run] The program is generated: a warning about it is the
        // compiler's to fix, not the user's to read. The emitter's own tests
        // still see them.
        args.push(OsStr::new("-nowarn"));
        let jar_cp;
        if !jars.is_empty() || lib_classes.is_some() {
            jar_cp = std::env::join_paths(lib_classes.iter().cloned().chain(jars.iter().cloned()))
                .map_err(|e| BackendError::Other(format!("cannot build a classpath: {e}")))?;
            args.push(OsStr::new("-cp"));
            args.push(jar_cp.as_os_str());
        }
        let code = run_tool("kotlinc", &args)?;
        if code != 0 {
            return Err(BackendError::Other(format!(
                "kotlinc failed with exit code {code}"
            )));
        }

        let entry = self.entry_hint(target_dir, main_module, emitted);
        let mut command = std::process::Command::new("kotlin");
        command.arg("-cp").arg(classpath(&classes)?).arg(&entry);
        Ok(command)
    }
}
