// Generated by the Salvo compiler: sealed wrappers for union types.
package salvo

sealed interface Union2<out T1, out T2> {
    val value: Any?
    data class U1<out T1, out T2>(override val value: T1) : Union2<T1, T2>
    data class U2<out T1, out T2>(override val value: T2) : Union2<T1, T2>
}
