// Generated by the Salvo compiler: enums for union types.

impl<T1: crate::wire::__Wire, T2: crate::wire::__Wire, T3: crate::wire::__Wire, T4: crate::wire::__Wire> crate::wire::__Wire for Union4<T1, T2, T3, T4> {
    fn __enc(&self, out: &mut Vec<u8>) {
        match self {
            Union4::U1(v) => {
                out.push(0);
                crate::wire::__Wire::__enc(v, out);
            }
            Union4::U2(v) => {
                out.push(1);
                crate::wire::__Wire::__enc(v, out);
            }
            Union4::U3(v) => {
                out.push(2);
                crate::wire::__Wire::__enc(v, out);
            }
            Union4::U4(v) => {
                out.push(3);
                crate::wire::__Wire::__enc(v, out);
            }
        }
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        match r.u8()? {
            0 => Some(Union4::U1(crate::wire::__Wire::__dec(r)?)),
            1 => Some(Union4::U2(crate::wire::__Wire::__dec(r)?)),
            2 => Some(Union4::U3(crate::wire::__Wire::__dec(r)?)),
            3 => Some(Union4::U4(crate::wire::__Wire::__dec(r)?)),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Union4<T1, T2, T3, T4> {
    U1(T1),
    U2(T2),
    U3(T3),
    U4(T4),
}

impl<T1, T2, T3, T4> Union4<T1, T2, T3, T4> {
    pub fn u1(&self) -> &T1 {
        match self {
            Union4::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u1_mut(&mut self) -> &mut T1 {
        match self {
            Union4::U1(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2(&self) -> &T2 {
        match self {
            Union4::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u2_mut(&mut self) -> &mut T2 {
        match self {
            Union4::U2(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3(&self) -> &T3 {
        match self {
            Union4::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u3_mut(&mut self) -> &mut T3 {
        match self {
            Union4::U3(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4(&self) -> &T4 {
        match self {
            Union4::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn u4_mut(&mut self) -> &mut T4 {
        match self {
            Union4::U4(v) => v,
            _ => panic!("unreachable union arm"),
        }
    }
    pub fn to_str(&self, f1: &mut dyn FnMut(&T1) -> String, f2: &mut dyn FnMut(&T2) -> String, f3: &mut dyn FnMut(&T3) -> String, f4: &mut dyn FnMut(&T4) -> String) -> String {
        match self {
            Union4::U1(v) => f1(v),
            Union4::U2(v) => f2(v),
            Union4::U3(v) => f3(v),
            Union4::U4(v) => f4(v),
        }
    }
}

impl<T1, T2, T3, T4> std::fmt::Display for Union4<T1, T2, T3, T4>
where
    T1: std::fmt::Display,
    T2: std::fmt::Display,
    T3: std::fmt::Display,
    T4: std::fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Union4::U1(v) => write!(f, "{}", v),
            Union4::U2(v) => write!(f, "{}", v),
            Union4::U3(v) => write!(f, "{}", v),
            Union4::U4(v) => write!(f, "{}", v),
        }
    }
}
