// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 5cd1832c3b5d03f1
use crate::unions::*;
use crate::core_actor::__Stateful_Faults as _;
use crate::core_actor::__Stateless_Faults as _;
use crate::core_bytes::Bytes;
use crate::core_list::at;
use crate::runtime::RuntimeHostPlatformSync as _;
use crate::runtime::__Stateful_RuntimeHost as _;
use crate::runtime::__Stateful_SchedTable as _;
use crate::runtime::__Stateless_RuntimeHost as _;
use crate::runtime::__Stateless_SchedTable as _;
use crate::runtime_routing::__Stateful_RouteTable as _;
use crate::runtime_routing::__Stateless_RouteTable as _;
use crate::runtime_routing::deliver;

#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct NodeEndpoint {
    pub host: String,
    pub port: i32,
}

impl crate::wire::__Wire for NodeEndpoint {
    fn __enc(&self, out: &mut Vec<u8>) {
        crate::wire::__Wire::__enc(&self.host, out);
        crate::wire::__Wire::__enc(&self.port, out);
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        Some(Self {
            host: crate::wire::__Wire::__dec(r)?,
            port: crate::wire::__Wire::__dec(r)?,
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Unreachable {
    pub to: NodeEndpoint,
}

impl crate::wire::__Wire for Unreachable {
    fn __enc(&self, out: &mut Vec<u8>) {
        crate::wire::__Wire::__enc(&self.to, out);
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        Some(Self {
            to: crate::wire::__Wire::__dec(r)?,
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct WireFailed {
    pub to: NodeEndpoint,
    pub reason: String,
}

impl crate::wire::__Wire for WireFailed {
    fn __enc(&self, out: &mut Vec<u8>) {
        crate::wire::__Wire::__enc(&self.to, out);
        crate::wire::__Wire::__enc(&self.reason, out);
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        Some(Self {
            to: crate::wire::__Wire::__dec(r)?,
            reason: crate::wire::__Wire::__dec(r)?,
        })
    }
}

pub type NetError = Union2<Unreachable, WireFailed>;

/// Factories for the host: one per arm of the union [platform-factory].
impl NetError {
    pub fn unreachable(value: Unreachable) -> Self {
        crate::unions::Union2::U1(value)
    }
    pub fn wire_failed(value: WireFailed) -> Self {
        crate::unions::Union2::U2(value)
    }
}

pub trait __Stateless_Inbound: Send + Sync {
    fn receive_frame(&self, from: NodeEndpoint, frame: Bytes);
}

pub trait __Stateful_Inbound: Send {
    fn receive_frame(&mut self, from: NodeEndpoint, frame: Bytes);
}

pub struct __Stub_Inbound {
    addr: usize,
}

impl __Stub_Inbound {
    pub fn new(addr: usize) -> Self {
        Self { addr }
    }
}

impl __Stateless_Inbound for __Stub_Inbound {
    fn receive_frame(&self, from: NodeEndpoint, frame: Bytes) {
        crate::scheduler::salvo_send_wire(self.addr, __Msg_Inbound::ReceiveFrame(from, frame), crate::net::__PROTO_Inbound);
    }
}

pub struct Inbound {
    inner: __Inner_Inbound,
}

pub enum __Inner_Inbound {
    Shared(std::sync::Arc<dyn __Stateless_Inbound>),
    Locked(std::sync::Arc<std::sync::Mutex<dyn __Stateful_Inbound>>),
}

impl Clone for Inbound {
    fn clone(&self) -> Self {
        Self { inner: match &self.inner {
            __Inner_Inbound::Shared(h) => __Inner_Inbound::Shared(h.clone()),
            __Inner_Inbound::Locked(h) => __Inner_Inbound::Locked(h.clone()),
        } }
    }
}

impl Inbound {
    pub fn shared<__H: __Stateless_Inbound + 'static>(inner: __H) -> Self {
        Self { inner: __Inner_Inbound::Shared(std::sync::Arc::new(inner)) }
    }
    pub fn share_shared(inner: std::sync::Arc<dyn __Stateless_Inbound>) -> Self {
        Self { inner: __Inner_Inbound::Shared(inner) }
    }
    pub fn locked<__H: __Stateful_Inbound + 'static>(inner: __H) -> Self {
        Self { inner: __Inner_Inbound::Locked(std::sync::Arc::new(std::sync::Mutex::new(inner))) }
    }
    pub fn share_locked(inner: std::sync::Arc<std::sync::Mutex<dyn __Stateful_Inbound>>) -> Self {
        Self { inner: __Inner_Inbound::Locked(inner) }
    }
    pub fn receive_frame(&self, from: NodeEndpoint, frame: Bytes) {
        match &self.inner {
            __Inner_Inbound::Shared(h) => h.receive_frame(from, frame),
            __Inner_Inbound::Locked(h) => h.lock().unwrap().receive_frame(from, frame),
        }
    }
}

pub enum __Msg_Inbound {
    ReceiveFrame(NodeEndpoint, Bytes),
}

impl crate::wire::__Wire for __Msg_Inbound {
    fn __enc(&self, out: &mut Vec<u8>) {
        match self {
            __Msg_Inbound::ReceiveFrame(__p0, __p1) => {
                out.push(0);
                crate::wire::__Wire::__enc(__p0, out);
                crate::wire::__Wire::__enc(__p1, out);
            }
        }
    }
    fn __dec(r: &mut crate::wire::__Reader<'_>) -> Option<Self> {
        match r.u8()? {
            0 => Some(__Msg_Inbound::ReceiveFrame(crate::wire::__Wire::__dec(r)?, crate::wire::__Wire::__dec(r)?)),
            _ => None,
        }
    }
}

/// [protocol-hash] The canonical hash of `Inbound`.
pub const __PROTO_Inbound: &str = "8e46ddb2a3e90b03";

pub trait __Stateless_Transport: Send + Sync {
    fn listen(&self, at: &NodeEndpoint, sink: usize) -> Union2<(), Union2<Unreachable, WireFailed>>;
    fn unlisten(&self, at: &NodeEndpoint);
    fn deliver(&self, to: &NodeEndpoint, frame: Bytes) -> Union2<(), Union2<Unreachable, WireFailed>>;
    fn local_endpoint(&self) -> NodeEndpoint;
}

pub trait __Stateful_Transport: Send {
    fn listen(&mut self, at: &NodeEndpoint, sink: usize) -> Union2<(), Union2<Unreachable, WireFailed>>;
    fn unlisten(&mut self, at: &NodeEndpoint);
    fn deliver(&mut self, to: &NodeEndpoint, frame: Bytes) -> Union2<(), Union2<Unreachable, WireFailed>>;
    fn local_endpoint(&mut self) -> NodeEndpoint;
}

pub struct Transport {
    inner: __Inner_Transport,
}

pub enum __Inner_Transport {
    Shared(std::sync::Arc<dyn __Stateless_Transport>),
    Locked(std::sync::Arc<std::sync::Mutex<dyn __Stateful_Transport>>),
}

impl Clone for Transport {
    fn clone(&self) -> Self {
        Self { inner: match &self.inner {
            __Inner_Transport::Shared(h) => __Inner_Transport::Shared(h.clone()),
            __Inner_Transport::Locked(h) => __Inner_Transport::Locked(h.clone()),
        } }
    }
}

impl Transport {
    pub fn shared<__H: __Stateless_Transport + 'static>(inner: __H) -> Self {
        Self { inner: __Inner_Transport::Shared(std::sync::Arc::new(inner)) }
    }
    pub fn share_shared(inner: std::sync::Arc<dyn __Stateless_Transport>) -> Self {
        Self { inner: __Inner_Transport::Shared(inner) }
    }
    pub fn locked<__H: __Stateful_Transport + 'static>(inner: __H) -> Self {
        Self { inner: __Inner_Transport::Locked(std::sync::Arc::new(std::sync::Mutex::new(inner))) }
    }
    pub fn share_locked(inner: std::sync::Arc<std::sync::Mutex<dyn __Stateful_Transport>>) -> Self {
        Self { inner: __Inner_Transport::Locked(inner) }
    }
    pub fn listen(&self, at: &NodeEndpoint, sink: usize) -> Union2<(), Union2<Unreachable, WireFailed>> {
        match &self.inner {
            __Inner_Transport::Shared(h) => h.listen(at, sink),
            __Inner_Transport::Locked(h) => h.lock().unwrap().listen(at, sink),
        }
    }
    pub fn unlisten(&self, at: &NodeEndpoint) {
        match &self.inner {
            __Inner_Transport::Shared(h) => h.unlisten(at),
            __Inner_Transport::Locked(h) => h.lock().unwrap().unlisten(at),
        }
    }
    pub fn deliver(&self, to: &NodeEndpoint, frame: Bytes) -> Union2<(), Union2<Unreachable, WireFailed>> {
        match &self.inner {
            __Inner_Transport::Shared(h) => h.deliver(to, frame),
            __Inner_Transport::Locked(h) => h.lock().unwrap().deliver(to, frame),
        }
    }
    pub fn local_endpoint(&self) -> NodeEndpoint {
        match &self.inner {
            __Inner_Transport::Shared(h) => h.local_endpoint(),
            __Inner_Transport::Locked(h) => h.lock().unwrap().local_endpoint(),
        }
    }
}

/// The adapter a `use` of a platform handler of `Transport` constructs [platform-abi].
pub struct __Platform_Transport<T>(pub T);

/// What a `threadsafe platform handler` of `Transport` implements [platform-abi].
pub trait TransportPlatformSync: Send + Sync {
    fn listen(&self, at: &NodeEndpoint, sink: usize) -> Union2<(), Union2<Unreachable, WireFailed>>;
    fn unlisten(&self, at: &NodeEndpoint);
    fn deliver(&self, to: &NodeEndpoint, frame: Bytes) -> Union2<(), Union2<Unreachable, WireFailed>>;
    fn local_endpoint(&self) -> NodeEndpoint;
}

impl<T: TransportPlatformSync> __Stateless_Transport for __Platform_Transport<T> {
    fn listen(&self, at: &NodeEndpoint, sink: usize) -> Union2<(), Union2<Unreachable, WireFailed>> {
        self.0.listen(at, sink)
    }
    fn unlisten(&self, at: &NodeEndpoint) {
        self.0.unlisten(at)
    }
    fn deliver(&self, to: &NodeEndpoint, frame: Bytes) -> Union2<(), Union2<Unreachable, WireFailed>> {
        self.0.deliver(to, frame)
    }
    fn local_endpoint(&self) -> NodeEndpoint {
        self.0.local_endpoint()
    }
}

/// Factories for the host: one per arm of the union [platform-factory].
pub struct Listen;

impl Listen {
    pub fn ok(value: ()) -> Union2<(), Union2<Unreachable, WireFailed>> {
        crate::unions::Union2::U1(value)
    }
    pub fn err(value: Union2<Unreachable, WireFailed>) -> Union2<(), Union2<Unreachable, WireFailed>> {
        crate::unions::Union2::U2(value)
    }
}

/// Factories for the host: one per arm of the union [platform-factory].
pub struct Deliver;

impl Deliver {
    pub fn ok(value: ()) -> Union2<(), Union2<Unreachable, WireFailed>> {
        crate::unions::Union2::U1(value)
    }
    pub fn err(value: Union2<Unreachable, WireFailed>) -> Union2<(), Union2<Unreachable, WireFailed>> {
        crate::unions::Union2::U2(value)
    }
}

pub fn bind_outbound_platform(node: i64, out: i32, hook: fn(i32, &Bytes, Bytes)) {
    crate::platform_net::bind_outbound(node, out, hook)
}

pub type __Platform_HostTcpTransport = crate::net::__Platform_Transport<crate::platform_net::HostTcpTransport>;

impl __Platform_HostTcpTransport {
    pub fn new(bind: NodeEndpoint) -> Self {
        crate::net::__Platform_Transport(crate::platform_net::HostTcpTransport::new(bind))
    }
}
