// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
package salvo.net

import salvo.*

data class NodeEndpoint(
    val host: String,
    val port: Int,
)

object __Codec_NodeEndpoint : salvo.WireCodec<NodeEndpoint> {
    override fun enc(v: NodeEndpoint, out: salvo.WireOut) {
        salvo.StrCodec.enc(v.host, out)
        salvo.IntCodec.enc(v.port, out)
    }
    override fun dec(inp: salvo.WireIn): NodeEndpoint = NodeEndpoint(salvo.StrCodec.dec(inp), salvo.IntCodec.dec(inp))
}

data class Unreachable(
    val to: NodeEndpoint,
)

object __Codec_Unreachable : salvo.WireCodec<Unreachable> {
    override fun enc(v: Unreachable, out: salvo.WireOut) {
        __Codec_NodeEndpoint.enc(v.to, out)
    }
    override fun dec(inp: salvo.WireIn): Unreachable = Unreachable(__Codec_NodeEndpoint.dec(inp))
}

data class WireFailed(
    val to: NodeEndpoint,
    val reason: String,
)

object __Codec_WireFailed : salvo.WireCodec<WireFailed> {
    override fun enc(v: WireFailed, out: salvo.WireOut) {
        __Codec_NodeEndpoint.enc(v.to, out)
        salvo.StrCodec.enc(v.reason, out)
    }
    override fun dec(inp: salvo.WireIn): WireFailed = WireFailed(__Codec_NodeEndpoint.dec(inp), salvo.StrCodec.dec(inp))
}

interface Inbound {
    fun receiveFrame(from: NodeEndpoint, frame: salvo.SalvoBytes)
}

class __Stub_Inbound(private val addr: Int) : Inbound {
    override fun receiveFrame(from: NodeEndpoint, frame: salvo.SalvoBytes) {
        salvo.SalvoSched.sendWire(addr, __Msg_Inbound.ReceiveFrame(from, frame), __PROTO_Inbound, __Codec___Msg_Inbound)
    }
}

class __Mon_Inbound(private val inner: Inbound) : Inbound {
    override fun receiveFrame(from: NodeEndpoint, frame: salvo.SalvoBytes) =
        synchronized(inner) { inner.receiveFrame(from, frame) }
}

sealed class __Msg_Inbound {
    class ReceiveFrame(val from: NodeEndpoint, val frame: salvo.SalvoBytes) : __Msg_Inbound()
}

object __Codec___Msg_Inbound : salvo.WireCodec<__Msg_Inbound> {
    override fun enc(v: __Msg_Inbound, out: salvo.WireOut) {
        when (v) {
            is __Msg_Inbound.ReceiveFrame -> { out.u8(0); __Codec_NodeEndpoint.enc(v.from, out); salvo.BytesCodec.enc(v.frame, out) }
        }
    }
    override fun dec(inp: salvo.WireIn): __Msg_Inbound = when (inp.u8()) {
            0 -> __Msg_Inbound.ReceiveFrame(__Codec_NodeEndpoint.dec(inp), salvo.BytesCodec.dec(inp))
        else -> throw salvo.WireError()
    }
}

/** [protocol-hash] The canonical hash of `Inbound`. */
const val __PROTO_Inbound: String = "8e46ddb2a3e90b03"

interface Transport {
    fun listen(at: NodeEndpoint, sink: Int): Union2<Unit, Union2<Unreachable, WireFailed>>
    fun unlisten(at: NodeEndpoint)
    fun deliver(to: NodeEndpoint, frame: salvo.SalvoBytes): Union2<Unit, Union2<Unreachable, WireFailed>>
    fun localEndpoint(): NodeEndpoint
}

class __Mon_Transport(private val inner: Transport) : Transport {
    override fun listen(at: NodeEndpoint, sink: Int): Union2<Unit, Union2<Unreachable, WireFailed>> =
        synchronized(inner) { inner.listen(at, sink) }
    override fun unlisten(at: NodeEndpoint) =
        synchronized(inner) { inner.unlisten(at) }
    override fun deliver(to: NodeEndpoint, frame: salvo.SalvoBytes): Union2<Unit, Union2<Unreachable, WireFailed>> =
        synchronized(inner) { inner.deliver(to, frame) }
    override fun localEndpoint(): NodeEndpoint =
        synchronized(inner) { inner.localEndpoint() }
}

// The interface a `platform handler` of `Transport` implements [platform-abi].
interface TransportPlatform {
    fun listen(at: NodeEndpoint, sink: Int): Union2<Unit, Union2<Unreachable, WireFailed>>
    fun unlisten(at: NodeEndpoint)
    fun deliver(to: NodeEndpoint, frame: salvo.SalvoBytes): Union2<Unit, Union2<Unreachable, WireFailed>>
    fun localEndpoint(): NodeEndpoint
}

open class __Platform_Transport(private val impl: TransportPlatform) : Transport {
    override fun listen(at: NodeEndpoint, sink: Int): Union2<Unit, Union2<Unreachable, WireFailed>> = impl.listen(at, sink)
    override fun unlisten(at: NodeEndpoint) = impl.unlisten(at)
    override fun deliver(to: NodeEndpoint, frame: salvo.SalvoBytes): Union2<Unit, Union2<Unreachable, WireFailed>> = impl.deliver(to, frame)
    override fun localEndpoint(): NodeEndpoint = impl.localEndpoint()
}

class __Platform_HostTcpTransport(bind: NodeEndpoint) : salvo.net.__Platform_Transport(salvo.platform.net.HostTcpTransport(bind))
