// GENERATED by salvo [platform-abi]: the host project of this platform root,
// so an IDE can open it. Rewritten by every build — do not edit.
// salvo-abi 1 6998aba5f5c25421

rootProject.name = "salvo-platform"
