// GENERATED by salvo for the host project of this platform root [platform-abi]:
// the declarations the platform code uses, as the build emits them. Rewritten
// by every build — do not edit; the build never reads this file.
// salvo-abi 1 5cd1832c3b5d03f1
package salvo.stream

import salvo.*
import salvo.core.bytes.addPlatform
import salvo.core.bytes.clearPlatform
import salvo.core.bytes.getPlatform
import salvo.core.bytes.mutBytes
import salvo.core.bytes.next
import salvo.core.bytes.sizePlatform
import salvo.core.checked.Checked
import salvo.core.checked.checked
import salvo.core.checked.ignore
import salvo.core.checked.toStr
import salvo.core.deque.get
import salvo.core.deque.getPlatform
import salvo.core.deque.sizePlatform
import salvo.core.deque.toStr
import salvo.core.iterator.Finished
import salvo.core.iterator.emitted
import salvo.core.iterator.finished
import salvo.core.list.addPlatform
import salvo.core.list.first
import salvo.core.list.get
import salvo.core.list.getPlatform
import salvo.core.list.sizePlatform
import salvo.core.list.toStr
import salvo.core.map.get
import salvo.core.map.getPlatform
import salvo.core.map.sizePlatform
import salvo.core.map.toStr
import salvo.core.set.addPlatform
import salvo.core.set.next
import salvo.core.set.sizePlatform
import salvo.core.set.toStr
import salvo.core.sorted.addPlatform
import salvo.core.sorted.getPlatform
import salvo.core.string.clearPlatform
import salvo.core.string.lines
import salvo.core.string.next
import salvo.core.string.sizePlatform
import salvo.runtime.streams.Streams
import salvo.runtime.streams.decode
import salvo.runtime.streams.freshHandle
import salvo.runtime.streams.readLine
import salvo.runtime.streams.receive

// Factories for the host: one per arm of the union [platform-factory].
object StreamErrors {
    fun invalidUtf8(value: InvalidUtf8): Union2<InvalidUtf8, StreamFailed> = salvo.Union2.U1(value)
    fun streamFailed(value: StreamFailed): Union2<InvalidUtf8, StreamFailed> = salvo.Union2.U2(value)
}

data class InvalidUtf8(
    val source: String,
)

object __Codec_InvalidUtf8 : salvo.WireCodec<InvalidUtf8> {
    override fun enc(v: InvalidUtf8, out: salvo.WireOut) {
        salvo.StrCodec.enc(v.source, out)
    }
    override fun dec(inp: salvo.WireIn): InvalidUtf8 = InvalidUtf8(salvo.StrCodec.dec(inp))
}

data class StreamFailed(
    val source: String,
    val message: String,
)

object __Codec_StreamFailed : salvo.WireCodec<StreamFailed> {
    override fun enc(v: StreamFailed, out: salvo.WireOut) {
        salvo.StrCodec.enc(v.source, out)
        salvo.StrCodec.enc(v.message, out)
    }
    override fun dec(inp: salvo.WireIn): StreamFailed = StreamFailed(salvo.StrCodec.dec(inp), salvo.StrCodec.dec(inp))
}
