[package]
name = "salvo-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The Salvo language compiler CLI"

[[bin]]
name = "salvo"
path = "src/main.rs"

[dependencies]
salvo-syntax = { workspace = true }
salvo-core = { workspace = true }
salvo-backend = { workspace = true }
salvo-backend-kotlin = { workspace = true }
salvo-backend-rust = { workspace = true }
salvo-test = { workspace = true }
clap = { workspace = true }
include_dir = { workspace = true }
lsp-server = { workspace = true }
lsp-types = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
salvo-testkit = { workspace = true }
